### ISSUE TITLE
bigip_iapplx_package module not working - Unable to set terminal parameters

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-ansible#1147]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_iapplx_package
##### ANSIBLE VERSION

```
/home/ansible/demo # ansible --version
ansible 2.7.4
  config file = /home/ansible/demo/ansible.cfg
  configured module search path = [u'/home/ansible/demo/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 13:24:18) [GCC 6.4.0]
```

##### PYTHON VERSION

```
/home/ansible/demo # python -V
Python 2.7.15
```

##### BIGIP VERSION

```
[root@vadc03:localdbmgr DOWN:Standalone] config # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0
  Build       0.0.116
  Edition     Final
  Date        Wed Nov 14 18:41:56 PST 2018


```

##### LIBRARY VERSIONS

```
/home/ansible/demo # pip freeze | egrep '(f5-sdk|bigsuds)'
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### CONFIGURATION

[defaults]
inventory = ./hosts
library   = ./library
roles_path = ./roles
retry_files_enabled = False
host_key_checking = False
vault_password_file = ./.vault-pass.txt
remote_tmp = /tmp/.ansible/tmp
deprecation_warnings=False
playbook_vars_root = top

[ssh_connection]
ssh_executable = /usr/bin/ssh
control_path_dir=/tmp/.ansible/cp
##### OS / ENVIRONMENT

Docker container running on MacOS

##### SUMMARY

Trying to run a playbook to install DO using the bigip_ipplx_package module and use SSH transport. 
Receive error that ansible is unable to set terminal parameters.

##### STEPS TO REPRODUCE

Run playbook

```
---
- name: test as3 deployment
  hosts: "{{ host }}"
  connection: local
  gather_facts: no


  environment:
    F5_USER:                "{{ username }}"
    F5_PASSWORD:            "{{ password }}"
    F5_VALIDATE_CERTS:      "no"
    F5_SERVER:              "{{ inventory_hostname }}"
    F5_SERVER_PORT:         443


  vars:
      demoState: "present"
    doRpmFile: "f5-declarative-onboarding-1.0.0-1.noarch.rpm"


  tasks:
    - name: Install AS3
      bigip_iapplx_package:
        provider:
          user: admin
          transport: cli
          server: "{{ host }}"
          ssh_keyfile: "/home/ansible/tmp/my_ssh_key.pem"
        package: "{{ doRpmFile }}"
      delegate_to: localhost

```

##### EXPECTED RESULTS

the declarative onboarding package would be uploaded to the bigip
##### ACTUAL RESULTS

```
/home/ansible/demo # ansible-playbook test_do_deploy.yml -e host=vadc03 -vvvv
ansible-playbook 2.7.4
  config file = /home/ansible/demo/ansible.cfg
  configured module search path = [u'/home/ansible/demo/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15 (default, Aug 22 2018, 13:24:18) [GCC 6.4.0]
Using /home/ansible/demo/ansible.cfg as config file
setting up inventory plugins
/home/ansible/demo/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/home/ansible/demo/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/ansible/demo/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test_do_deploy.yml ****************************************************************************************************************************
1 plays in test_do_deploy.yml

PLAY [test as3 deployment] ******************************************************************************************************************************
META: ran handlers
Trying secret FileVaultSecret(filename='/home/ansible/demo/.vault-pass.txt') for vault_id=default

TASK [Install AS3] **************************************************************************************************************************************
task path: /home/ansible/demo/test_do_deploy.yml:28
<localhost> connection transport is cli
<vadc03> using connection plugin network_cli
<vadc03> starting connection from persistent connection plugin
<vadc03> local domain socket does not exist, starting it
<vadc03> control socket path is /root/.ansible/pc/0d19e63836
<vadc03> 
The full traceback is:
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 106, in start
    self.connection._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 331, in _connect
    self._terminal.on_open_shell()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/terminal/bigip.py", line 62, in on_open_shell
    raise AnsibleConnectionFailure('unable to set terminal parameters')
AnsibleConnectionFailure: unable to set terminal parameters

fatal: [192.168.0.247]: FAILED! => {
    "msg": "unable to set terminal parameters"
}

PLAY RECAP **********************************************************************************************************************************************
192.168.0.247              : ok=0    changed=0    unreachable=0    failed=1   


```

**Comment by wojtek0806** [comment]
please install and use https://galaxy.ansible.com/f5devcentral/f5ansible and report back if the issue persists

**Comment by wojtek0806** [comment]
scratch that the issue was not related, please try with the role and see if this works for you

**Comment by wojtek0806** [comment]
i have found an issue and fixed the role can you reinstall it please:

ansible-galaxy install -f f5devcentral.f5ansible,master

**Comment by wojtek0806** [comment]
@ajgerace have you had a chance to test it ?

**Comment by ajgerace** [comment]
Yes and I'm receiving the same error message when I use the role.

Can you confirm this should work with a provider transport of CLI?

**Comment by wojtek0806** [comment]
from what i can see it does not support CLI only rest

**Comment by wojtek0806** [comment]
Ok so I checked it out and transport cli is only used in bigip_command module. From what I recall @caphrim007  has never intended to have CLI used as transport in any other module besides command module.

**Comment by ajgerace** [comment]
ok, I guess we can close this out.

Thanks
