### ISSUE TITLE
remove import workaround when 2.8 hits

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-ansible#1155]
added workaround to allow galaxy role usage without forcing users to install ansible galaxy devel code. 

Without the workaround using f5ansible galaxy role resulted in the below issue:

````
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 549, in _execute
    self._handler = self._get_action_handler(connection=self._connection, templar=templar)
  File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 915, in _get_action_handler
    shared_loader_obj=self._shared_loader_obj,
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/loader.py", line 378, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.ansible/roles/f5devcentral.f5ansible/action_plugins/bigip.py", line 30, in <module>
    from ansible.plugins.action.network import ActionModule as ActionNetworkModule
ModuleNotFoundError: No module named 'ansible.plugins.action.network'

fatal: [bigip_v12_docker]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
````

**Comment by wojtek0806** [comment]
after assessing this carefully, it has been decided that this workaround stays
