### ISSUE TITLE
key error in bigip_device_facts when ltm pool has no pool members attached

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-ansible#1159]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

`````The full traceback is:
Traceback (most recent call last):
  File "/Users/wypior/.ansible/tmp/ansible-tmp-1547663971.912448-176381936012361/AnsiballZ_bigip_device_facts.py", line 113, in <module>
    _ansiballz_main()
  File "/Users/wypior/.ansible/tmp/ansible-tmp-1547663971.912448-176381936012361/AnsiballZ_bigip_device_facts.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/wypior/.ansible/tmp/ansible-tmp-1547663971.912448-176381936012361/AnsiballZ_bigip_device_facts.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 15466, in <module>
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 15457, in main
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 15201, in exec_module
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 15280, in execute_managers
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 11104, in exec_module
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 11112, in _exec_module
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 6573, in to_return
  File "/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py", line 10880, in available_member_count
KeyError: 'availableMemberCnt'

fatal: [bigip_12]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/wypior/.ansible/tmp/ansible-tmp-1547663971.912448-176381936012361/AnsiballZ_bigip_device_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/Users/wypior/.ansible/tmp/ansible-tmp-1547663971.912448-176381936012361/AnsiballZ_bigip_device_facts.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/wypior/.ansible/tmp/ansible-tmp-1547663971.912448-176381936012361/AnsiballZ_bigip_device_facts.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 15466, in <module>\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 15457, in main\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 15201, in exec_module\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 15280, in execute_managers\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 11104, in exec_module\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 11112, in _exec_module\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 6573, in to_return\n  File \"/tmp/ansible_bigip_device_facts_payload_4ejqaxpd/__main__.py\", line 10880, in available_member_count\nKeyError: 'availableMemberCnt'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by wojtek0806** [comment]
the issue lies with the 'stats' output rather than the pool attribute, the stats endpoint for pool in v12  does not have `availableMemberCnt` in its output
