### ISSUE TITLE
Error UnboundLocalError: local variable 'client' referenced before assignment

### ISSUE THREAD

**Issue by sdaynjax** [F5Networks/f5-ansible#1244]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_snmp_community
bigip_snmp_trap

##### ANSIBLE VERSION

```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/e00gx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017

```

##### OS / ENVIRONMENT

Red Hat Enterprise 7

##### SUMMARY

When running playbook to config ltm with snmp community and trap I'm getting an error message 

"module_stderr": "Traceback (most recent call last):\n  File \"/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_snmp_community_payload_VOeUtQ/__main__.py\", line 761, in <module>\n  File \"/tmp/ansible_bigip_snmp_community_payload_VOeUtQ/__main__.py\", line 756, in main\nUnboundLocalError: local variable 'client' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

##### STEPS TO REPRODUCE

```
   - name: Create an SMNP v2c read-only community
     bigip_snmp_community:
       name: comm1
       version: v2c
       source: all
       access: ro
       state: present
     delegate_to: localhost
     
   - name: Create snmp v2 trap
     bigip_snmp_trap:
       community: comm1
       destination: 
        - 10.1.1.1
        - 10.1.1.2
       name: snmp-trap1
       network: management
       port: 162
       snmp_version: 2c
     delegate_to: localhost
```

##### EXPECTED RESULTS

I expect to have the snmp community and version configured as well as the trap destination

##### ACTUAL RESULTS

```
TASK [Create an SMNP v2c read-only community] ************************************************************************************************************
task path: /automation/ansible/playbooks/f5/Test/test_build_ltm.yml:46
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: e00gx
<localhost> EXEC /bin/sh -c 'echo ~e00gx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048 `" && echo ansible-tmp-1551200988.18-144324530890048="` echo /home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_snmp_community.py
<localhost> PUT /home/e00gx/.ansible/tmp/ansible-local-25340_ebC5o/tmpHW6UYq TO /home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/ /home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py", line 113, in <module>
    _ansiballz_main()
  File "/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_bigip_snmp_community_payload_VOeUtQ/__main__.py", line 761, in <module>
  File "/tmp/ansible_bigip_snmp_community_payload_VOeUtQ/__main__.py", line 756, in main
UnboundLocalError: local variable 'client' referenced before assignment

fatal: [10.62.232.235 -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/e00gx/.ansible/tmp/ansible-tmp-1551200988.18-144324530890048/AnsiballZ_bigip_snmp_community.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_snmp_community_payload_VOeUtQ/__main__.py\", line 761, in <module>\n  File \"/tmp/ansible_bigip_snmp_community_payload_VOeUtQ/__main__.py\", line 756, in main\nUnboundLocalError: local variable 'client' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by wojtek0806** [comment]
As per https://clouddocs.f5.com/products/orchestration/ansible/devel/usage/filing-issues.html please download the latest ansible galaxy role retest and post results with the role in use if the issue persists.

Once this information is provided we will re-open
