### ISSUE TITLE
bigip_data_group fails creating data group

### ISSUE THREAD

**Issue by Cajga** [F5Networks/f5-ansible#1256]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_data_group

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.8.0.dev0
  config file = /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/ansible.cfg
  configured module search path = [u'/sysadmin/user/EL7/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /sysadmin/user/repos/ansible/lib/ansible
  executable location = /sysadmin/user/repos/ansible/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
$ python -V
Python 2.7.5
```

##### BIGIP VERSION

```
[root@lbx01:Standby:Changes Pending] config # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.1
  Build       0.0.7
  Edition     Point Release 1
  Date        Tue Jan 15 19:49:59 PST 2019


```

##### CONFIGURATION
$ cat ansible.cfg 
[defaults]
retry_files_enabled = False
host_key_checking=False

$ ansible-galaxy install f5devcentral.f5ansible
- downloading role 'f5ansible', owned by f5devcentral
- downloading role from https://github.com/f5devcentral/ansible-role-f5ansible/archive/v2019.3.1.tar.gz
- extracting f5devcentral.f5ansible to /sysadmin/user/EL7/.ansible/roles/f5devcentral.f5ansible
- f5devcentral.f5ansible (v2019.3.1) was installed successfully

##### OS / ENVIRONMENT
RHEL7.5

##### SUMMARY
bigip_data_group cannot create a data group as it fails with error

##### STEPS TO REPRODUCE
call ansible-playbook in the way described below. The bug always comes.

```
$ cat data_group_issue
[load_balancers]
lbx01.example.com
$ cat address_data_group.yaml 
- name: Create address data group
  hosts: lbx01.example.com
  connection: local

  roles:
    - role: f5devcentral.f5ansible

  vars:
    provider:
      password: password
      server: lbx01.example.com
      user: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: Configure data groups on masters
      bigip_data_group:
        name: test
        type: address
        records:
          - key: 10.0.0.0/8
            value: "Internal network"
        provider: "{{ provider }}"
```

##### EXPECTED RESULTS
A data group with address type gets created in the LB

##### ACTUAL RESULTS

It fails with error message:
```
TypeError: coercing to Unicode: need string or buffer, _io.StringIO found\n
```

```
$ ansible-playbook -vvvv -i data_group_issue address_data_group.yaml 
ansible-playbook 2.8.0.dev0
  config file = /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/ansible.cfg
  configured module search path = [u'/sysadmin/user/EL7/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /sysadmin/user/repos/ansible/lib/ansible
  executable location = /sysadmin/user/repos/ansible/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/data_group_issue as it did not pass it's verify_file() method
script declined parsing /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/data_group_issue as it did not pass it's verify_file() method
auto declined parsing /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/data_group_issue as it did not pass it's verify_file() method
Parsed /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/data_group_issue inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /sysadmin/user/repos/ansible/lib/ansible/plugins/callback/default.pyc

PLAYBOOK: address_data_group.yaml *********************************************************************************************************************************************************************************
Positional arguments: address_data_group.yaml
become_method: sudo
inventory: (u'/sysadmin/user/EL7/local/ansible/f5-datagroup_issue/data_group_issue',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in address_data_group.yaml

PLAY [Create address data group] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
task path: /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/address_data_group.yaml:1
<lbx01.example.com> ESTABLISH LOCAL CONNECTION FOR USER: user
<lbx01.example.com> EXEC /bin/sh -c 'echo ~user && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863145.95-38021345179579 `" && echo ansible-tmp-1551863145.95-38021345179579="` echo /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863145.95-38021345179579 `" ) && sleep 0'
<lbx01.example.com> Attempting python interpreter discovery
<lbx01.example.com> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /sysadmin/user/repos/ansible/lib/ansible/modules/system/setup.py
<lbx01.example.com> PUT /sysadmin/user/EL7/.ansible/tmp/ansible-local-32746ZVGfvJ/tmpl7BZEk TO /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863145.95-38021345179579/AnsiballZ_setup.py
<lbx01.example.com> EXEC /bin/sh -c 'chmod u+x /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863145.95-38021345179579/ /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863145.95-38021345179579/AnsiballZ_setup.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '/usr/bin/python /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863145.95-38021345179579/AnsiballZ_setup.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c 'rm -f -r /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863145.95-38021345179579/ > /dev/null 2>&1 && sleep 0'
ok: [lbx01.example.com]
META: ran handlers

TASK [f5devcentral.f5ansible : Check ansible version] *************************************************************************************************************************************************************
task path: /sysadmin/user/EL7/.ansible/roles/f5devcentral.f5ansible/tasks/main.yaml:7
skipping: [lbx01.example.com] => {}

TASK [Configure data groups on masters] ***************************************************************************************************************************************************************************
task path: /sysadmin/user/EL7/local/ansible/f5-datagroup_issue/address_data_group.yaml:17
<lbx01.example.com> connection transport is rest
<lbx01.example.com> ESTABLISH LOCAL CONNECTION FOR USER: user
<lbx01.example.com> EXEC /bin/sh -c 'echo ~user && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905 `" && echo ansible-tmp-1551863149.29-91888859985905="` echo /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905 `" ) && sleep 0'
Using module file /sysadmin/user/EL7/.ansible/roles/f5devcentral.f5ansible/library/bigip_data_group.py
<lbx01.example.com> PUT /sysadmin/user/EL7/.ansible/tmp/ansible-local-32746ZVGfvJ/tmpxOjFM6 TO /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py
<lbx01.example.com> EXEC /bin/sh -c 'chmod u+x /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/ /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c '/usr/bin/python /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py && sleep 0'
<lbx01.example.com> EXEC /bin/sh -c 'rm -f -r /sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py", line 114, in <module>
    _ansiballz_main()
  File "/sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 1307, in <module>
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 1300, in main
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 1244, in exec_module
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 769, in exec_module
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 818, in present
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 956, in create
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 1082, in create_on_device
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 1015, in _upload_to_file
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py", line 1008, in upload_file_to_device
  File "/tmp/ansible_bigip_data_group_payload_SgT1A2/ansible_bigip_data_group_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 402, in upload_file
TypeError: coercing to Unicode: need string or buffer, _io.StringIO found

fatal: [lbx01.example.com]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/sysadmin/user/EL7/.ansible/tmp/ansible-tmp-1551863149.29-91888859985905/AnsiballZ_bigip_data_group.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 1307, in <module>\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 1300, in main\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 1244, in exec_module\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 769, in exec_module\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 818, in present\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 956, in create\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 1082, in create_on_device\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 1015, in _upload_to_file\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/__main__.py\", line 1008, in upload_file_to_device\n  File \"/tmp/ansible_bigip_data_group_payload_SgT1A2/ansible_bigip_data_group_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 402, in upload_file\nTypeError: coercing to Unicode: need string or buffer, _io.StringIO found\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
lbx01.example.com          : ok=1    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

```

**Comment by wojtek0806** [comment]
this is not a bug in the code but a documentation issue in the EXAMPLES section. 

For this to work you need to specify if this is internal data group:

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_data_group.py#L49
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_data_group.py#L63

The examples are misleading, i will change them. Please test with internal: yes and see if the results are correct now.

**Comment by Cajga** [comment]
Hi @wojtek0806,

Thanks for the prompt support, you are right, internal: yes fixes the problem.

May I ask when do you plan to push your current dev to ansible dev repo?
The bigip_data_group which is there right now does not allow us to define a network (ie.: 10.0.0.8/8) when address type is selected and this has been fixed already in your repo.
Also, the bigip_profile_client_ssl fixes one of the issues that I run into (to be able to define the renegotiate option).

**Comment by Cajga** [comment]
Opps, it looks I was too early to say that it has been fixed. In case we use the records_src as a source the problem is still there with the current devel as well (defining the records with records works fine).
I will open another report for this.
