### ISSUE TITLE
Module fails with 'cannot import name F5SDK' when used with another role

### ISSUE THREAD

**Issue by gullanetworkcode** [F5Networks/f5-ansible#1283]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_gtm_server

##### ANSIBLE VERSION
```
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION
```
Python 2.7.15rc1
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018

```

##### OS / ENVIRONMENT
XUBUNTU

##### SUMMARY
When using the f5-ansible galaxy role along with another role using the built in modules the f5-ansible galaxy role fails

##### STEPS TO REPRODUCE

This is the playbook:-
```
- name: GTM build
  hosts: gtm_external
  connection: local
  gather_facts: no

  tasks:
  - include_role:
      name: f5_gtm_config

  - include_role:
      name: f5devcentral.f5ansible
      tasks_from: gtm_servers
```
this is the actual playbook in the role `gtm_servers`:-
```
- name: Create GTM servers (LTMs)
  bigip_gtm_server:
    provider: "{{ f5_provider }}"
    name: "{{ item.key }}"
    devices: "{{ item.value.devices }}"
    datacenter: "{{ item.value.datacenter }}"
    virtual_server_discovery: "{{ item.value.virtual_server_discovery }}"
    iquery_options:
      allow_path: "{{ item.value.iquery_allow_path }}"
      allow_service_check: "{{ item.value.iquery_allow_service_check }}"
      allow_snmp: "{{ item.value.iquery_allow_snmp }}"
    link_discovery: "{{ item.value.link_discovery }}"
  with_dict: "{{ f5_gtm_servers_ltms }}"
  delegate_to: localhost
  notify: save_config
```

##### EXPECTED RESULTS
Plays to run!!
##### ACTUAL RESULTS

```
ASK [f5devcentral.f5ansible : Create GTM servers (GTMs)] *************************************************************************************************************************************
task path: /home/paulh/tfs/NetworkAutomation/Ansible/Prod/roles/f5devcentral.f5ansible/tasks/gtm_servers.yml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: paulh
<localhost> EXEC /bin/sh -c 'echo ~paulh && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990 `" && echo ansible-tmp-1554475449.99-173833543279990="` echo /home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_gtm_server.py
<localhost> PUT /home/paulh/.ansible/tmp/ansible-local-6709lr29pd/tmpIxFAiQ TO /home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/ /home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py", line 113, in <module>
    _ansiballz_main()
  File "/home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_bigip_gtm_server_payload_aR1wyn/__main__.py", line 225, in <module>
ImportError: cannot import name HAS_F5SDK

failed: [crlaplcsgtm001.mgmt.cig.local -> localhost] (item={'value': {u'datacenter': u'CRL', u'link_discovery': u'disabled', u'iquery_allow_snmp': True, u'iquery_allow_service_check': True, u'state': u'enabled', u'virtual_server_discovery': u'disabled', u'address': u'149.255.185.53', u'translation': u'10.128.0.235', u'iquery_allow_path': True}, 'key': u'CRLAPLCSGTM001'}) => {
    "changed": false, 
    "item": {
        "key": "CRLAPLCSGTM001", 
        "value": {
            "address": "######", 
            "datacenter": "CRL", 
            "iquery_allow_path": true, 
            "iquery_allow_service_check": true, 
            "iquery_allow_snmp": true, 
            "link_discovery": "disabled", 
            "state": "enabled", 
            "translation": "10.128.0.235", 
            "virtual_server_discovery": "disabled"
        }
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1554475449.99-173833543279990/AnsiballZ_bigip_gtm_server.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_gtm_server_payload_aR1wyn/__main__.py\", line 225, in <module>\nImportError: cannot import name HAS_F5SDK\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
<localhost> EXEC /bin/sh -c 'echo ~paulh && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609 `" && echo ansible-tmp-1554475450.47-214117296236609="` echo /home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_gtm_server.py
<localhost> PUT /home/paulh/.ansible/tmp/ansible-local-6709lr29pd/tmpwwRTKu TO /home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/ /home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py", line 113, in <module>
    _ansiballz_main()
  File "/home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_bigip_gtm_server_payload__eDYff/__main__.py", line 225, in <module>
ImportError: cannot import name HAS_F5SDK

failed: [crlaplcsgtm001.mgmt.cig.local -> localhost] (item={'value': {u'datacenter': u'VAL', u'link_discovery': u'disabled', u'iquery_allow_snmp': True, u'iquery_allow_service_check': True, u'state': u'enabled', u'virtual_server_discovery': u'disabled', u'address': u'149.255.184.85', u'translation': u'10.32.0.235', u'iquery_allow_path': True}, 'key': u'VALAPLCSGTM001'}) => {
    "changed": false, 
    "item": {
        "key": "VALAPLCSGTM001", 
        "value": {
            "address": "#######", 
            "datacenter": "VAL", 
            "iquery_allow_path": true, 
            "iquery_allow_service_check": true, 
            "iquery_allow_snmp": true, 
            "link_discovery": "disabled", 
            "state": "enabled", 
            "translation": "10.32.0.235", 
            "virtual_server_discovery": "disabled"
        }
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1554475450.47-214117296236609/AnsiballZ_bigip_gtm_server.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_gtm_server_payload__eDYff/__main__.py\", line 225, in <module>\nImportError: cannot import name HAS_F5SDK\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
        to retry, use: --limit @/home/paulh/tfs/NetworkAutomation/Ansible/Prod/f5_test_role_tasks.retry

PLAY RECAP ************************************************************************************************************************************************************************************
crlaplcsgtm001.mgmt.cig.local : ok=7    changed=0    unreachable=0    failed=1   
```
(I've #### some of the addresses)

**Comment by wojtek0806** [comment]
you cannot use this role in other roles i am afraid, if you want to use development version of our modules you need to copy entire library folder from our development  branch and configure ansible.cfg file to point to where you copied the module code.

**Comment by gullanetworkcode** [comment]
Does that I also can’t use just one module out of the development code and use the included modules for everything else? Also, how can I find out when the development module that works is in the main ansible deploy?

Thanks for your patience :0)
