### ISSUE TITLE
bigip_wait SSH protocol banner error

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-ansible#1354]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_wait

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### PYTHON VERSION
```
$ python -V
Python 2.7.12

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.0.4
  Edition     Point Release 4
  Date        Wed Jan 16 18:04:36 PST 2019

```

##### CONFIGURATION
Running ansible from jenkins pipeline

##### OS / ENVIRONMENT
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

##### SUMMARY
bigip_wait task fails with below error

AnsibleConnectionFailure: Error reading SSH protocol banner
fatal: [3.112.198.76]: FAILED! => {
    "msg": "Error reading SSH protocol banner"
}

##### STEPS TO REPRODUCE
1. In Jenkinsfile pipeline, run terraform apply to boot up BIG-IP instance in AWS
2. In same pipeline, run ansible-playbook command to configure BIG-IP, but need to add wait so playbook does not fail
 

```
---
#Allow time for instance to boot

- name: Wait for BIG-IP to be ready, don't start checking for 90 seconds
  bigip_wait:
    delay: 90
    provider:
      server: "{{ inventory_hostname }}"
      server_port: 8443
      ssh_keyfile: "{{ ansible_ssh_private_key_file }}"
      transport: cli
      user: admin
    validate_certs: no
  delegate_to: localhost

- name: Set BIG-IP admin password
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ ansible_ssh_private_key_file }}"
      transport: cli
      user: admin
    commands: modify auth user admin password {{ ADMIN_PASSWORD }}
    validate_certs: no
  delegate_to: localhost

- name: enable iApps LX Package management in UI
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ ansible_ssh_private_key_file }}"
      transport: cli
      user: admin
    commands: run /util bash -c "touch /var/config/rest/iapps/enable"
    validate_certs: no
  delegate_to: localhost
```

##### EXPECTED RESULTS
bigip_wait delays for 90s then attempts to check for readiness 

##### ACTUAL RESULTS

```
PLAY [Onboarding BIG-IP] *******************************************************
META: ran handlers

TASK [f5_onboarding : Wait for BIG-IP to be ready, don't start checking for 90 seconds] ***
task path: /var/lib/jenkins/workspace/terry-pipeline1/terraform-ansible-aws/F5_Standalone_1Nic/ansible/playbooks/roles/f5_onboarding/tasks/main.yml:4
<localhost> connection transport is cli
<IP> using connection plugin network_cli
<IP> starting connection from persistent connection plugin
<IP> local domain socket does not exist, starting it
<IP> control socket path is /var/lib/jenkins/.ansible/pc/71f6ce7b88
<IP> 
The full traceback is:
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 106, in start
    self.connection._connect()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/network_cli.py", line 309, in _connect
    ssh = self.paramiko_conn._connect()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 255, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 378, in _connect_uncached
    raise AnsibleConnectionFailure(msg)
AnsibleConnectionFailure: Error reading SSH protocol banner
fatal: [IP]: FAILED! => {
    "msg": "Error reading SSH protocol banner"
}
	to retry, use: --limit @/var/lib/jenkins/workspace/terry-pipeline1/terraform-ansible-aws/F5_Standalone_1Nic/ansible/playbooks/site.retry

PLAY RECAP *********************************************************************
IP1             : ok=5    changed=0    unreachable=0    failed=0   
IP2 (BIG-IP)               : ok=0    changed=0    unreachable=0    failed=1   
IP3                 : ok=5    changed=0    unreachable=0    failed=0   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:262)
	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:400)
	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:321)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Ansible playbook execution failed
Finished: FAILURE
```

**Comment by focrensh** [comment]
Tracking under FMFA-268

**Comment by crosbygw** [comment]
@tkam8 
This module is using cli transport (ssh) so you should not include server port or validate_certs. Try the following and let me know how it works out.
-GC
```
- name: Wait for BIG-IP to be ready, don't start checking for 90 seconds
  bigip_wait:
    delay: 90
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ ansible_ssh_private_key_file }}"
      transport: cli
      user: admin
  delegate_to: localhost
```

**Comment by crosbygw** [comment]
@tkam8 
Checking to see if you have had a chance to try playbook without specifying port?

**Comment by crosbygw** [comment]
Closing issue, please reopen if suggestion does not resolve error.
