### ISSUE TITLE
icontrol REST not handling 'bytes' from response object in Python 3

### ISSUE THREAD

**Issue by nahun** [F5Networks/f5-ansible#1397]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
icontrol module_util

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /home/wheeler-admin/desktop/ansible/network/python3/ansible-network/ansible.cfg
  configured module search path = ['/usr/local/share/ansible/modules', '/home/wheeler-admin/desktop/ansible/network/python3/ansible-network/modules']
  ansible python module location = /home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible
  executable location = /home/wheeler-admin/tmp/ansible-p3/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 3.5.2
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0
  Build       0.0.116
  Edition     Final
  Date        Wed Nov 14 18:41:56 PST 2018
```

##### ROLE VERSION

This appears to be fixed in the latest versions that will go into Ansible 2.9, but I think a fix may be warranted for Ansible 2.8.x.

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Only in Python 3 does the icontrol module_util fail. It complains that the response object must be a string and not bytes.

##### STEPS TO REPRODUCE
I'm testing directly to the module with module args
```
$ cat args.json
{
    "ANSIBLE_MODULE_ARGS": {
        "provider": {
        "server": "<BIG-IP HOSTNAME>",
        "user": "admin",
        "password": "<BIG-IP PASSWORD>"
    },
    "gather_subset": ["system-info"]
    }
}
```

##### EXPECTED RESULTS
Return BIG-IP facts

##### ACTUAL RESULTS

```
$ python ~/tmp/ansible-p3/lib/python3.5/site-packages/ansible/modules/network/f5/bigip_device_facts.py args.json 
Traceback (most recent call last):
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/modules/network/f5/bigip_device_facts.py", line 15475, in <module>
    main()
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/modules/network/f5/bigip_device_facts.py", line 15468, in main
    results = mm.exec_module()
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/modules/network/f5/bigip_device_facts.py", line 15214, in exec_module
    result = self.execute_managers(managers)
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/modules/network/f5/bigip_device_facts.py", line 15290, in execute_managers
    prov = modules_provisioned(client)
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/module_utils/network/f5/icontrol.py", line 559, in modules_provisioned
    resp = client.api.get(uri)
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/module_utils/network/f5/bigip.py", line 32, in api
    session, err = self.connect_via_token_auth()
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/module_utils/network/f5/bigip.py", line 62, in connect_via_token_auth
    session.request.headers['X-F5-Auth-Token'] = response.json()['token']['token']
  File "/home/wheeler-admin/tmp/ansible-p3/lib/python3.5/site-packages/ansible/module_utils/network/f5/icontrol.py", line 114, in json
    return _json.loads(self._content or 'null')
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

In the Ansible 2.8.1 release if I modify line 114 in icontrol.py module_util to decode the content it then works fine in Python 3.
```
return _json.loads(self._content.decode('utf-8') or 'null')
```

**Comment by wojtek0806** [comment]
git history and git blame log indicate no change. 
if this was an issue in  2.8 we would know about it already as the file in question is used as means to connect to device by all modules.  What is in devel is the exact thing you have in 2.8. I would suggest first of all running a playbook with ansible and seeing if this is an issue. if so post the playbook and results as per issue template. then we can revisit

**Comment by nahun** [comment]
So far this appears to be limited to Python 3.5.2. I have replicated on two machines with that version.

Using Python 3.5.7 and 3.6.7 everything is fine.

Python 3.5.2 is the default for Ubuntu 16.04 so I would think others would complain as well so maybe its still somehow related to my environment. I tried a v13.1.0.1 and v14.1.0 BIG-IP though with the same results.

I'll continue some more testing to narrow it down just in case others hit the same issue its at least on the Internet somewhere.

**Comment by wojtek0806** [comment]
do not waste your time on this. unless you can replicate it by running ansible framework with a playbook ( running ansible task) which is the only supported way by the way, we will not be changing this and definitely not backporting to 2.8
