### ISSUE TITLE
bigip_device_info - nodes

### ISSUE THREAD

**Issue by mojr13** [F5Networks/f5-ansible#1401]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_device_info

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/slsp.sk/414292/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION
```

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.5
  Build       0.0.5
  Edition     Point Release 5
  Date        Tue May 14 11:15:38 PDT 2019

```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: b66a4e5337d6200d94408d187ea6a7e69a8c4f20
        commit_message: Merging upstream changes - 2019-06-29T07:00:32Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/b66a4e5337d6200d94408d187ea6a7e69a8c4f20
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 8474
        forks_count: 0
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-06-29T03:03:45.596933-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-06-29T07:03:45.604565Z
        open_issues_count: 0
        path: (u'/home/slsp.sk/414292/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles')
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master

```

##### CONFIGURATION

Nothing

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When running bigip_device_facts for nodes it ends whith an error. Virtual servers and pools work fine.

##### STEPS TO REPRODUCE

```
  - name: Collect BIG-IP facts
    bigip_device_facts:
      gather_subset:
        - nodes
      provider:
        password: "{{f5password}}"
        server: "{{f5ip}}"
        user: ansible
        validate_certs: no
        timeout: 100
    delegate_to: localhost
    register: nodess

```

##### EXPECTED RESULTS

Save nodes json to variable nodess
##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1562052522.16-99923531694534/AnsiballZ_bigip_device_facts.py", line 114, in <module>
    _ansiballz_main()
  File "/home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1562052522.16-99923531694534/AnsiballZ_bigip_device_facts.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1562052522.16-99923531694534/AnsiballZ_bigip_device_facts.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 15475, in <module>
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 15468, in main
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 15214, in exec_module
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 15293, in execute_managers
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 11305, in exec_module
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 11311, in _exec_module
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 11323, in read_facts
  File "/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py", line 11366, in read_stats_from_device
TypeError: 'NoneType' object has no attribute '__getitem__'

fatal: [sk23f5l01v.dctest.slsp.sk -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1562052522.16-99923531694534/AnsiballZ_bigip_device_facts.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1562052522.16-99923531694534/AnsiballZ_bigip_device_facts.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1562052522.16-99923531694534/AnsiballZ_bigip_device_facts.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 15475, in <module>\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 15468, in main\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 15214, in exec_module\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 15293, in execute_managers\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 11305, in exec_module\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 11311, in _exec_module\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 11323, in read_facts\n  File \"/tmp/ansible_bigip_device_facts_payload_6j1YdK/__main__.py\", line 11366, in read_stats_from_device\nTypeError: 'NoneType' object has no attribute '__getitem__'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by wojtek0806** [comment]
FMFA-304

**Comment by nitinthewiz** [comment]
Not able to reproduce.

I setup the environment exactly as specified but was unable to repro the issue.

Environ - 

```
ansible 2.8.1
  config file = /root/ansible.cfg
  configured module search path = [u'/root/f5-ansible/library/modules']
  ansible python module location = /root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/ansible
  executable location = /root/.pyenv/versions/2.7.5/bin/ansible
  python version = 2.7.5 (default, Jul 22 2019, 22:04:24) [GCC 7.4.0]
```

```
Python 2.7.5
```
```
ansible-galaxy install git+https://github.com/f5devcentral/ansible-role-f5ansible.git,b66a4e5337d6200d94408d187ea6a7e69a8c4f20
```

```
BIG-IP | 14.1.0.5 | 0.0.5
```

I was able to observe the nodes output - 

```
"nodes": [
        {
            "address": "6.5.7.8",
            "availability_status": "unknown",
            "connection_limit": 0,
            "dynamic_ratio": 1,
            "enabled_status": "enabled",
            "full_path": "/Common/onenode",
            "monitor_rule": "none",
            "monitor_status": "unchecked",
            "monitor_type": "and_list",
            "monitors": [],
            "name": "onenode",
            "rate_limit": 0,
            "ratio": 1,
            "session_status": "enabled",
            "status_reason": "Node address does not have service checking enabled"
        }
    ],
```

@mojr13 can you provide more details about the setup - 
What BIG-IP is this on? 
What permissions does the ansible user have?
What nodes are currently present on the device (tmsh config if possible)?

**Comment by mojr13** [comment]
Hello,
I am sorry but I cannot send you our tmsh config :(

I was doing some troubleshooting, and it looks like there is a problem with certain names of nodes that contain % character (maybe they are not escaped correctly?)
I was able to reproduci this bug on a lab F5 with a single not with parameters:

name: 10.10.10.10%2452
ip: 10.10.10.10%2452

(the %2452 is designation for route domain)

**Comment by nitinthewiz** [comment]
Excellent! Thank you!

I had a feeling the name or some other such property was the issue.

We do not have an escape sequence for the percentage sign in the name as of right now. This is a utils level change, and I'll be discussing it with my team before we implement it.

Thanks for linking to the other issue. I went through it and yes, it will also get resolved when we fix this issue.
