### ISSUE TITLE
bigip_device_info performance issues

### ISSUE THREAD

**Issue by perzizzle** [F5Networks/f5-ansible#1535]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_device_info

##### ANSIBLE VERSION

```
ansible 2.8.6
  config file = /Users/michael.perzel/stash/ansible/tests/ansible.cfg
  configured module search path = ['/Users/michael.perzel/stash/ansible/library']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### PYTHON VERSION

```
Python 2.7.16
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2
  Build       0.0.37
  Edition     Final
  Date        Wed Aug  7 09:56:44 PDT 2019
```

##### CONFIGURATION

All defaults
##### OS / ENVIRONMENT

RHEL 7

##### SUMMARY

I am working on migrating some playbooks from bigip_facts to bigip_device_info. When I compare run times of a test playbook, I'm seeing runtimes of 20s for bigip_facts and 40s for bigip_device_facts. We use these modules to do rolling application deploys so at the volume of jobs we run this has a large impact on throughput.

##### STEPS TO REPRODUCE

```
Playbook:
---
- name: Test enable disable node
  hosts: "{{ host_limit }}"
  gather_facts: false
  roles:
    - disableNode
    - enableNode

bigip_facts based role
---
- name: Determine if node is in ltm
  local_action:
    module: bigip_facts
    provider:
      server: '{{ item }}'
      user: '{{ f5_ltm_username }}'
      password: '{{ f5_ltm_password }}'
      validate_certs: no
    include: node
    filter: '{{ inventory_hostname }}'
  register: node_facts
  with_items: "{{ f5_ltm_server }}"

- name: Disable node in LTM
  local_action:
    module: bigip_node
    provider:
      server: '{{ item.1 }}'
      user: '{{ f5_ltm_username }}'
      password: '{{ f5_ltm_password }}'
      validate_certs: no
    state: offline
    partition: Common
    name: "{{ inventory_hostname }}"
  with_indexed_items: "{{ f5_ltm_server }}"
  when: node_facts.results[ item.0 ].ansible_facts.node

bigip_device_info based role:
- name: Determine if node is in ltm
  local_action:
    module: bigip_device_facts
    provider:
      server: '{{ item }}'
      user: '{{ f5_ltm_username }}'
      password: '{{ f5_ltm_password }}'
      validate_certs: no
    gather_subset: 
      - nodes
  register: node_facts
  with_items: "{{ f5_ltm_server }}"

- name: Disable node in LTM
  local_action:
    module: bigip_node
    provider:
      server: '{{ item.1 }}'
      user: '{{ f5_ltm_username }}'
      password: '{{ f5_ltm_password }}'
      validate_certs: no
    state: offline
    partition: Common
    name: "{{ inventory_hostname }}"
  with_indexed_items: "{{ f5_ltm_server }}"
  vars:
    node_query: "[?name=='{{ inventory_hostname }}'].enabled_status"
    node_result: "{{ node_facts['results'][item.0]['nodes'] | json_query(node_query) }}"
  register: output
  when: node_result
```

##### EXPECTED RESULTS

Ideally, I would see very similar run times since they are doing functionally similar work.

##### ACTUAL RESULTS

The test LTM I am working with has 14 nodes total defined. The test playbook disables 6 nodes, and then enables 6 nodes. See run times below. Planning on doing additional testing with a larger production config, I assume the results will be even worse.

```
bigip_facts run:
ansible-playbook testEnableDisableNode.yml --inventory    
21.36s user 10.37s system 46% cpu 1:08.18 total

bigip_device_info run:
ansible-playbook testEnableDisableNode.yml --inventory    
40.90s user 26.30s system 26% cpu 4:17.99 total
```

**Comment by wojtek0806** [comment]
This is because there is more information collected in bigip_device_info, if you need to collect specific info just use include keyword to limit the scope otherwise the module grabs all, this is working as intended.

**Comment by perzizzle** [comment]
In the example its already using the include, gather_subset option to only return nodes. There's only 14 nodes on the test LTM in question so its not very much data. Looking at the data returned by the 2 modules they aren't very different in terms of node data.

**Comment by jbericat** [comment]
Hello,

I've been experiencing quite a similar issue while gathering the "ltm-pools" subset (like 10-15 minutes to obtain data). I was also able to reproduce the very same error on a F5-BIGIP-VE device. 

That's the Ansible script I'm running-off:

```yml
---
- hosts: localhost
  connection: local
  vars:
    provider:
      user: admin
      password: XXXXXXXXXXX
      server: bigip1.eve.lan
      server_port: 443
      validate_certs: no
  tasks: 
    - name: "1.1 - Collecting pool server info from device"
      bigip_device_info:
        provider: "{{ provider }}"
        gather_subset:
          - ltm-pools
      register: pool_info
      delegate_to: localhost
    - name: "1.2 - Print gathered pool info"
      debug:
        msg: "{{ pool_info }}"
```

On my side, I got almost 1800 ltm-pools enabled on the device. Would you say that this is a bit too much? The point is that if I try to run the same operation using the REST api, either from the localhost or from a remote host (browser), then the results come INSTANTLY. Here is how I did it from localhost (that is, the BIGIP device itself):

**1. SSH into the bigip device**

**2. Obtain an Auth Token**

`curl -sk https://localhost/mgmt/shared/authn/login -X POST -H "Content-Type: application/json" -d '-u admin {"loginProviderName":"tmos"}'`

Results:

`{"username":"admin","loginReference":{"link":"https://localhost/mgmt/cm/system/authn/providers/tmos/1f44a60e-11a7-3c51-a49f-82983026b41b/login"},"loginProviderName":"tmos","token":{"token":"SM7PEVOBG5E4IYQ4BGITGREDNX","name":"SM7PEVOBG5E4IYQ4BGITGREDNX","userName":"admin","authProviderName":"tmos","user":{"link":"https://localhost/mgmt/shared/authz/users/admin"},"timeout":1200,"startTime":"2022-06-22T02:19:10.225+0200","address":"127.0.0.1","partition":"[All]","generation":1,"lastUpdateMicros":1655857150224121,"expirationMicros":1655858350225000,"kind":"shared:authz:tokens:authtokenitemstate","selfLink":"https://localhost/mgmt/shared/authz/tokens/SM7PEVOBG5E4IYQ4BGITGREDNX"},"generation":0,"lastUpdateMicros":0}`

**4. Retrieve the ltm-pools list**

`curl -sk -H "X-F5-Auth-Token: XXXXXXXXXXXXXXXXXXXXXXXX" https://localhost/mgmt/tm/ltm/pool`

Results:

```
[root@hostname:INOPERATIVE:Disconnected] config # ls -lah /var/tmp/ltm-pools.json 
-rw-r--r--. 1 root root 1.6M Jun 21 20:24 /var/tmp/ltm-pools.json

```

So, my conclusion here is that there must be something wrong either on the "device_info" module from the BIGIP imperative collection, or in the device configuration itself. Also, on the `/var/log/javarestd.0.log` file there are tons of errors like this one, which appeared while the script was running.

```
[SEVERE][1437][21 Jun 2022 23:00:07 UTC][com.f5.rest.workers.asm.AsmConfigWorker] nanoTime:[28928974957949] threadId:[22]  Exception:[org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
	at com.f5.asmconfig.client.AsmClient.<init>(AsmClient.java:42)
	at com.f5.asmconfig.client.AsmClient.<init>(AsmClient.java:50)
	at com.f5.rest.workers.asm.WrapAsmClient.getClient(AsmConfigWorker.java:306)
	at com.f5.rest.workers.asm.AsmConfigWorker.restCallWithRetry(AsmConfigWorker.java:170)
	at com.f5.rest.workers.asm.AsmConfigWorker.forwardCall(AsmConfigWorker.java:200)
	at com.f5.rest.workers.asm.AsmConfigWorker$1.run(AsmConfigWorker.java:156)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:580)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
	... 13 more
]client:[9037788] 
[SEVERE][1438][21 Jun 2022 23:00:07 UTC][8100/tm/asm/owasp/task OWASPTaskScheduleWorker] Unexptected exception in getting all the polcies: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
	at com.f5.asmconfig.client.AsmClient.<init>(AsmClient.java:42)
	at com.f5.asmconfig.client.AsmClient.<init>(AsmClient.java:50)
	at com.f5.rest.workers.asm.WrapAsmClient.getClient(AsmConfigWorker.java:306)
	at com.f5.rest.workers.asm.AsmConfigWorker.restCallWithRetry(AsmConfigWorker.java:170)
	at com.f5.rest.workers.asm.AsmConfigWorker.forwardCall(AsmConfigWorker.java:200)
	at com.f5.rest.workers.asm.AsmConfigWorker$1.run(AsmConfigWorker.java:156)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 184 path $.errorStack
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
		at com.google.gson.Gson.fromJson(Gson.java:888)
		at com.google.gson.Gson.fromJson(Gson.java:853)
		at com.google.gson.Gson.fromJson(Gson.java:802)
		at com.f5.rest.common.RestOperation.getBody(RestOperation.java:1571)
		at com.f5.rest.common.RestOperation.setErrorResponseBody(RestOperation.java:2573)
		at com.f5.rest.common.RestOperation.fail(RestOperation.java:2456)
		at com.f5.rest.common.RestOperation.fail(RestOperation.java:2413)
		at com.f5.rest.common.RestWorker$5.failed(RestWorker.java:865)
		at com.f5.rest.common.RestWorker$5.failed(RestWorker.java:850)
		at com.f5.rest.common.RestOperation.fail(RestOperation.java:2493)
		at com.f5.rest.common.RestOperation.fail(RestOperation.java:2413)
		at com.f5.rest.workers.asm.AsmConfigWorker.forwardCall(AsmConfigWorker.java:246)
		... 8 more
	Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 184 path $.errorStack
		at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
		at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
		at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
		... 20 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:580)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
	... 13 more
```

Does anyone see where is the issue from that logfile? I'd appreciate help. Thanks!

**ANSIBLE VERSION**

6.12.1

**AWX VERSION** (TO-DO TEST WITHOUT AWX!!!!!)

19.0.4

**PYTHON VERSION**

Python 2.8.8

**BIGIP VERSION**

BIG-IP 15.1.5.1 Build 0.0.14 Point Release 1 (VIRTUAL EDITION)

**F5 MODULES COLLECTION**

f5networks.f5_bigip

**COMPONENT NAME**

bigip_device_info
