### ISSUE TITLE
Error installing collection

### ISSUE THREAD

**Issue by sbyount** [F5Networks/f5-ansible#1583]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-galaxy collection install f5networks.f5_modules

##### ANSIBLE VERSION
```
ansible 2.9.1
  config file = /Users/UID/STRATOS/ansible/ansible.cfg
  configured module search path = ['/Users/UID/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/UID/STRATOS/ansible/venv/bin/ansible
  python version = 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) [Clang 6.0 (clang-600.0.57)]
```

##### PYTHON VERSION
```
Python 3.7.3
```

##### BIGIP VERSION
N/A

##### OS / ENVIRONMENT
MAC 10.14.6

##### STEPS TO REPRODUCE
(venv) HOST:ansible UID$ ansible-galaxy collection install f5networks.f5_modules -c -vvv
ansible-galaxy 2.9.1
  config file = /Users/UID/STRATOS/ansible/ansible.cfg
  configured module search path = ['/Users/UID/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/UID/STRATOS/ansible/venv/bin/ansible-galaxy
  python version = 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) [Clang 6.0 (clang-600.0.57)]
Using /Users/UID/STRATOS/ansible/ansible.cfg as config file
Process install dependency map
Opened /Users/UID/.ansible/galaxy_token
Processing requirement collection 'f5networks.f5_modules'
Opened /Users/UID/.ansible/galaxy_token
Opened /Users/UID/.ansible/galaxy_token
Collection 'f5networks.f5_modules' obtained from server default https://galaxy.ansible.com/api/
Starting collection install process
Opened /Users/UID/.ansible/galaxy_token
Installing 'f5networks.f5_modules:1.0.0' to '/Users/UID/.ansible/collections/ansible_collections/f5networks/f5_modules'
Downloading https://galaxy.ansible.com/download/f5networks-f5_modules-1.0.0.tar.gz to /Users/UID/.ansible/tmp/ansible-local-17499ct1fyek9/tmpx3xx82g1
ERROR! Unexpected Exception, this is probably a bug: The read operation timed out
the full traceback was:
- Can upload traceback if needed.

##### EXPECTED RESULTS
Collection installed

##### ACTUAL RESULTS
See error above.  Collection will not install.

**Comment by sbyount** [comment]
Also, I am able to install other collections successfully.  e.g. ansible-galaxy install ansible-network.arista_eos

**Comment by wojtek0806** [comment]
the timeouts are galaxy related not collection, but it seems you have solved it yourself.

**Comment by sbyount** [comment]
Well it won’t install

**Comment by sbyount** [comment]
ERROR! Unexpected Exception, this is probably a bug: The read operation timed out
the full traceback was:

Can upload traceback if needed.

**Comment by wojtek0806** [comment]
no issues installing , the error you pointed is a timeout on galaxy not the collection problem:
```
ansible 2.9.0
python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]

┌─(test_env)[][±][devel ↑2 ↓3 ✓][~/Work/f5_modules_collection]
└─▪ ansible-galaxy collection install f5networks.f5_modules
Process install dependency map
Starting collection install process
Installing 'f5networks.f5_modules:1.0.0' to '/Users/test/Work/collections/ansible_collections/f5networks/f5_modules'
```

**Comment by wojtek0806** [comment]
For completeness:

```┌─(test_env)[redacted][redacted][±][devel ↑2 ↓3 ✓][~/Work/f5_modules_collection]
└─▪ ansible --version
ansible 2.9.1
  config file = /Users/redacted/devsettings/ansible.cfg
  configured module search path = ['/Users/redacted/Work/f5-ansible/library/modules']
  ansible python module location = /Users/redacted/environments/test_env/lib/python3.7/site-packages/ansible
  executable location = /Users/redacted/environments/test_env/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]
```
```
┌─(test_env)[redacted][redacted][±][devel ↑2 ↓3 ✓][~/Work/f5_modules_collection]
└─▪ ansible-galaxy collection install f5networks.f5_modules
Process install dependency map
Starting collection install process
Installing 'f5networks.f5_modules:1.0.0' to '/Users/redacted/Work/collections/ansible_collections/f5networks/f5_modules'
```
```
┌─(test_env)[redacted][redacted][±][devel ↑2 ↓3 ✓][~/Work/f5_modules_collection]
└─▪ rm -rf  ~/Work/collections/ansible_collections/
```
```
┌─(test_env)[redacted][redacted][±][devel ↑2 ↓3 ✓][~/Work/f5_modules_collection]
└─▪ ansible-galaxy collection install f5networks.f5_modules -c -vvvv
ansible-galaxy 2.9.1
  config file = /Users/redacted/devsettings/ansible.cfg
  configured module search path = ['/Users/redacted/Work/f5-ansible/library/modules']
  ansible python module location = /Users/redacted/environments/test_env/lib/python3.7/site-packages/ansible
  executable location = /Users/redacted/environments/test_env/bin/ansible-galaxy
  python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]
Using /Users/redacted/devsettings/ansible.cfg as config file
Process install dependency map
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /Users/redacted/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Processing requirement collection 'f5networks.f5_modules'
Collection requirement 'f5networks.f5_modules' is the name of a collection
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
Opened /Users/redacted/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/f5networks/f5_modules/versions
Opened /Users/redacted/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/f5networks/f5_modules/versions/1.0.0
Collection 'f5networks.f5_modules' obtained from server default https://galaxy.ansible.com/api/
Starting collection install process
Opened /Users/redacted/.ansible/galaxy_token
Installing 'f5networks.f5_modules:1.0.0' to '/Users/wypior/Work/collections/ansible_collections/f5networks/f5_modules'
Downloading https://galaxy.ansible.com/download/f5networks-f5_modules-1.0.0.tar.gz to /Users/redacted/.ansible/tmp/ansible-local-96133atdxj2at/tmpl44c8pdi
Validating downloaded file hash 3008f70d6dd25b430443626be1ec24462f1a258a4f9d1ac7d760ef35879ac6c0 with expected hash 3008f70d6dd25b430443626be1ec24462f1a258a4f9d1ac7d760ef35879ac6c0
```
Not an F5 collection issue, raise any timeout problems with the Ansible core

**Comment by sbyount** [comment]
Please explain to me how I am able to install FIVE other collections (avi, arista, cisco_ios, cisco_nxos, and cisco_xr) without any issues, but cannot install F5

ERROR! Unexpected Exception, this is probably a bug: The read operation timed out
the full traceback was:

Traceback (most recent call last):
  File "/Users/UID/STRATOS/ansible/venv/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 370, in run
    context.CLIARGS['func']()
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 826, in execute_install
    no_deps, force, force_deps)
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 435, in install_collections
    collection.install(output_path, b_temp_path)
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 158, in install
    headers=headers)
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/galaxy/collection.py", line 861, in _download_file
    unredirected_headers=['Authorization'])
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/module_utils/urls.py", line 1390, in open_url
    unredirected_headers=unredirected_headers)
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/module_utils/urls.py", line 1294, in open
    r = urllib_request.urlopen(*urlopen_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/UID/STRATOS/ansible/venv/lib/python3.7/site-packages/ansible/module_utils/urls.py", line 467, in https_open
    return self.do_open(self._build_https_connection, req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by wojtek0806** [comment]
for the 'n' th time this is a problem with a connection to galaxy, raise this with ansible core.

**Comment by wojtek0806** [comment]
you could try installing the devel version of collection without downloading from galaxy, see if this works:
https://github.com/F5Networks/f5-ansible#collections-daily-build

**Comment by sbyount** [comment]
https://github.com/ansible/galaxy/issues/2132

**Comment by wojtek0806** [comment]
have you managed to install the devel collection ok ?
