### ISSUE TITLE
BigIq_regkey_license_assignment URL using control chars.

### ISSUE THREAD

**Issue by Andrew-Callan** [F5Networks/f5-ansible#1624]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- bigiq_regkey_license_assignment

##### ANSIBLE VERSION

```
ansible 2.9.3
  config file = /Users/andrewcallan/Desktop/Esoc_f5_setup/ansible.cfg
  configured module search path = ['/Users/andrewcallan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.3/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Dec 27 2019, 18:06:00) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### PYTHON2 VERSION
```
Python 2.7.16
```

##### PYTHON3 VERSION
```
Python 3.7.6
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.3
  Build       0.0.5
  Edition     Point Release 3
  Date        Tue Dec 17 19:48:55 PST 2019
```

##### CONFIGURATION

Configs within ansible.cfg:
```
[defaults]
collections_paths = ./collections
```
Ansible environment variable ANSIBLE_HOST_KEY_CHECKING=False
##### OS / ENVIRONMENT
Tried on both macOS Catalina 10.15.2 and CentOS Linux release 7.7.1908

##### STEPS TO REPRODUCE

run Ansible-galaxy install collection f5networks.f5_modules -p ./collections from cli in playbook directory and run 

export ANSIBLE_HOST_KEY_CHECKING=False && ansible-playbook main.yml -vvv

```
Task that fails:
- name: Subscribe BigIP systems to BigIQ
  collections:
    - f5.networks.f5_module
  f5networks.f5_modules.bigiq_regkey_license_assignment:
     pool: "{{ regkey_pool_name }}"
     key: "{{ bigip_license_list[1] }}"
    device: "{{ bigip1_provider.server }}"
    device_username: "{{ bigip1_provider.user }}"
    device_password: "{{ bigip1_provider.password }}"
    managed: no
    state: present
    provider: "{{ bigiq_provider }}"
  delegate_to: localhost

Pertinent sections of group_vars/all.yml

bigiq_provider:
  password: xxx
  server: x.x.x.x
  user: admin
  validate_certs: no
  server_port: 443

bigip1_provider:
  password: yyy
  server: y.y.y.y
  user: admin
  validate_certs: no
  server_port: 443

regkey_pool_name: poolname
bigip_license_list:
  - XX-XX-XX-XX-XX
  - YY-YY-YY-YY-YY
```

##### EXPECTED RESULTS
BigIP is subscribed to license pool of BigIQ.

##### ACTUAL RESULTS

```
task path: /Users/<user>/Desktop/<client>_f5_setup/bigip_subscribe.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: <user>
<127.0.0.1> EXEC /bin/sh -c 'echo ~<user> && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/<user>/.ansible/tmp/ansible-tmp-1579792259.316888-272528702151522 `" && echo ansible-tmp-1579792259.316888-272528702151522="` echo /Users/<user>/.ansible/tmp/ansible-tmp-1579792259.316888-272528702151522 `" ) && sleep 0'
Using module file /usr/local/Cellar/ansible/2.9.3/libexec/lib/python3.8/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /Users/<user>/.ansible/tmp/ansible-local-46258n8eve9qv/tmpxiysyczi TO /Users/<user>/.ansible/tmp/ansible-tmp-1579792259.316888-272528702151522/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/<user>/.ansible/tmp/ansible-tmp-1579792259.316888-272528702151522/ /Users/<user>/.ansible/tmp/ansible-tmp-1579792259.316888-272528702151522/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-bvgqpocpasxnoqjxoiwzbuztyyvlwuhh ; /usr/local/Cellar/ansible/2.9.3/libexec/bin/python3.8 /Users/<user>/.ansible/tmp/ansible-tmp-1579792259.316888-272528702151522/AnsiballZ_setup.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/<user>/.ansible/tmp/ansible-tmp-1579792259.316888-272528702151522/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers
Read vars_file 'group_vars/all.yml'
Read vars_file 'group_vars/all.yml'

TASK [bigip_subscribe : Subscribe BigIP systems to BigIQ] *****************************************************************************************************************************************************************************
task path: /Users/<user>/Desktop/<client>_f5_setup/roles/bigip_subscribe/tasks/main.yml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: <user>
<localhost> EXEC /bin/sh -c 'echo ~<user> && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822 `" && echo ansible-tmp-1579792260.3226502-82572178910822="` echo /Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822 `" ) && sleep 0'
Using module file /Users/<user>/Desktop/<client>_f5_setup/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py
<localhost> PUT /Users/<user>/.ansible/tmp/ansible-local-46258n8eve9qv/tmpc6xfnys6 TO /Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/ /Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-glcwiaanqwmgwrycobhmkjacsesxnkqs ; /usr/local/Cellar/ansible/2.9.3/libexec/bin/python3.8 /Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigiq_regkey_license_assignment', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py", line 629, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py", line 622, in main
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py", line 437, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py", line 457, in present
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py", line 462, in exists
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py", line 307, in member_id
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py", line 276, in pool_id
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 232, in get
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 193, in send
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible/module_utils/urls.py", line 1294, in open
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible/module_utils/urls.py", line 467, in https_open
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1241, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1092, in putrequest
    self._validate_path(url)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1183, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. "/mgmt/cm/device/licensing/pool/regkey/licenses?$filter=(name eq 'sharkdemokeypool')&$top=1" (found at least ' ')

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/<user>/.ansible/tmp/ansible-tmp-1579792260.3226502-82572178910822/AnsiballZ_bigiq_regkey_license_assignment.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigiq_regkey_license_assignment', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py\", line 629, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py\", line 622, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py\", line 437, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py\", line 457, in present\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py\", line 462, in exists\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py\", line 307, in member_id\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py\", line 276, in pool_id\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 232, in get\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 193, in send\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py\", line 542, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload_n_0j1o74/ansible_f5networks.f5_modules.bigiq_regkey_license_assignment_payload.zip/ansible/module_utils/urls.py\", line 467, in https_open\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py\", line 1319, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers,\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py\", line 1230, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py\", line 1241, in _send_request\n    self.putrequest(method, url, **skips)\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py\", line 1092, in putrequest\n    self._validate_path(url)\n  File \"/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py\", line 1183, in _validate_path\n    raise InvalidURL(f\"URL can't contain control characters. {url!r} \"\nhttp.client.InvalidURL: URL can't contain control characters. \"/mgmt/cm/device/licensing/pool/regkey/licenses?$filter=(name eq 'sharkdemokeypool')&$top=1\" (found at least ' ')\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```
##### CODE CAUSING ISSUE
On line 270 in collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_regkey_license_assignment.py 

On line 270 There are spaces used instead of %20. Making this change fixes the issue.

Line 270 before change:
```
filter = "(name eq '{0}')".format(self.pool)
```
Line 270 after change:
```
filter = "(name%20eq%20'{0}')".format(self.pool)
```

**Comment by onurbrc** [comment]
@wojtek0806 do you have any news about this issue? What about @Andrew-Callan's solution? 
Thanks.

**Comment by focrensh** [comment]
Apologies for the delay. We are tracking this issue with FMFA-540 internally.
