### ISSUE TITLE
bigip_device_certificate fails with Attribute Error

### ISSUE THREAD

**Issue by gullanetworkcode** [F5Networks/f5-ansible#1656]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_certificate

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### PYTHON VERSION
```
Python 2.7.5
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.5
  Build       0.0.6
  Edition     Final
  Date        Fri Aug  2 14:49:14 PDT 2019

```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.7 (Maipo)

##### SUMMARY
Module errors with Attribute Error

##### STEPS TO REPRODUCE
```
---

- name: Playbook testing device cert creation
  hosts: PLL_F5N_IT_GTMS
  connection: local
  gather_facts: no

  tasks:
    - name: Create a new custom named certificate to replace not expired certificate
      bigip_device_certificate:
        days_valid: 365
        new_cert: yes
        force: yes
        issuer:
          common_name: pllaplitgtm001.mgmt.cig.local
          division: Infrastructure
          organization: Acme-Corp
          locality: City
          state: State
          country: United Kingdom
          email: it@acmecorp.co.uk
        provider:
          user: "{{ f5n_user }}"
          password: "{{ f5n_password }}"
          server: "{{ inventory_hostname }}"
          transport: cli
          server_port: 22
      delegate_to: localhost

```

##### EXPECTED RESULTS
Creates/replaces device certificate

##### ACTUAL RESULTS

```
[paulh@plllintsapp041 ansible]$ ansible-playbook -i inv_lv f5_device_cert_test.yml --vault-id @prompt --limit pllaplitgtm001.mgmt.cig.local -vvv
ansible-playbook 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
Vault password (default): 
host_list declined parsing /home/paulh/NetworkAutomation/Ansible/Prod/inv_lv as it did not pass its verify_file() method
script declined parsing /home/paulh/NetworkAutomation/Ansible/Prod/inv_lv as it did not pass its verify_file() method
auto declined parsing /home/paulh/NetworkAutomation/Ansible/Prod/inv_lv as it did not pass its verify_file() method
Parsed /home/paulh/NetworkAutomation/Ansible/Prod/inv_lv inventory source with ini plugin

PLAYBOOK: f5_device_cert_test.yml **************************************************************************************************************************
1 plays in f5_device_cert_test.yml

PLAY [Playbook testing device cert creation] ***************************************************************************************************************
META: ran handlers

TASK [Create a new custom named certificate to replace not expired certificate] ****************************************************************************
task path: /home/paulh/NetworkAutomation/Ansible/Prod/f5_device_cert_test.yml:9
<pllaplitgtm001.mgmt.cig.local> using connection plugin network_cli
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: paulh
<localhost> EXEC /bin/sh -c 'echo ~paulh && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528 `" && echo ansible-tmp-1582203684.68-261823524799528="` echo /home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_device_certificate.py
<localhost> PUT /home/paulh/.ansible/tmp/ansible-local-7363KNRNnG/tmpMGdUzQ TO /home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/ /home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py", line 102, in <module>
    _ansiballz_main()
  File "/home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_certificate', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py", line 627, in <module>
  File "/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py", line 620, in main
  File "/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py", line 420, in exec_module
  File "/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py", line 429, in present
  File "/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py", line 464, in expired
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

fatal: [pllaplitgtm001.mgmt.cig.local -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/paulh/.ansible/tmp/ansible-tmp-1582203684.68-261823524799528/AnsiballZ_bigip_device_certificate.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_certificate', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py\", line 627, in <module>\n  File \"/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py\", line 620, in main\n  File \"/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py\", line 420, in exec_module\n  File \"/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py\", line 429, in present\n  File \"/tmp/ansible_bigip_device_certificate_payload_TaWKH1/ansible_bigip_device_certificate_payload.zip/ansible/modules/network/f5/bigip_device_certificate.py\", line 464, in expired\nAttributeError: 'datetime.datetime' object has no attribute 'timestamp'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP *************************************************************************************************************************************************
pllaplitgtm001.mgmt.cig.local : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by tsvsj** [comment]
This module is not compatible with Python version < 3.3. Therefore there is no method `datetime.timestamp()` in your version. Move on to Python 3 in virtualenv and the module should work fine. 

Also note, that the python module `paramiko` needs to be installed, as it is used by the `cli` transport method.

**Comment by wojtek0806** [comment]
@gullanetworkcode we are slowly removing py 2.x support from the modules so using py 3.x is strongly recommended, also install the appropriate packages, i believe paramiko should be installed automatically with ansible if it is not then install this package. After you do this and the problem persists report back and we will revisit
