### ISSUE TITLE
how to create ucs backup and qkview , please help me if know any dedicated module to create UCS and qkview locally on F5 box

### ISSUE THREAD

**Issue by rabindra-chauhan** [F5Networks/f5-ansible#1702]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Please review the following 2 modules in the docs:

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_ucs_module.html#bigip-ucs-module

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_ucs_fetch_module.html#bigip-ucs-fetch-module

**Comment by rabindra-chauhan** [comment]
its failing with below error code 

.46.100.172> using connection plugin network_cli
<10.46.100.172> starting connection from persistent connection plugin
<10.46.100.172> local domain socket does not exist, starting it
<10.46.100.172> control socket path is /home/i508357/.ansible/pc/8caf02b276
<10.46.100.172> local domain socket listeners started successfully
<10.46.100.172> unable to load cliconf for network_os bigip
<10.46.100.172> 
<10.46.100.172> local domain socket path is /home/i508357/.ansible/pc/8caf02b276
<10.46.100.172> socket_path: /home/i508357/.ansible/pc/8caf02b276
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: i508357
<localhost> EXEC /bin/sh -c 'echo ~i508357 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889 `" && echo ansible-tmp-1585799303.4584534-279777979129889="` echo /home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889 `" ) && sleep 0'
Using module file /home/i508357/git/ccloud-net/venv/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_ucs.py
<localhost> PUT /home/i508357/.ansible/tmp/ansible-local-1219d53xt7ya/tmpz3mqpowy TO /home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/ /home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/i508357/git/ccloud-net/venv/bin/python3 /home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py", line 102, in <module>
    _ansiballz_main()
  File "/home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_ucs', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 718, in <module>
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 711, in main
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 310, in exec_module
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 327, in is_version_v1
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 529, in tmos_version
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/bigip.py", line 34, in api
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/bigip.py", line 58, in connect_via_token_auth
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 238, in post
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 193, in send
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/urls.py", line 1294, in open
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/urls.py", line 467, in https_open
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
fatal: [qa-de-1a-f512-01 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3.6/urllib/request.py\", line 1318, in do_open\n    encode_chunked=req.has_header('Transfer-encoding'))\n  File \"/usr/lib/python3.6/http/client.py\", line 1254, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib/python3.6/http/client.py\", line 1300, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.6/http/client.py\", line 1249, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.6/http/client.py\", line 1036, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.6/http/client.py\", line 974, in send\n    self.connect()\n  File \"/usr/lib/python3.6/http/client.py\", line 1407, in connect\n    super().connect()\n  File \"/usr/lib/python3.6/http/client.py\", line 946, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/usr/lib/python3.6/socket.py\", line 724, in create_connection\n    raise err\n  File \"/usr/lib/python3.6/socket.py\", line 713, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/i508357/.ansible/tmp/ansible-tmp-1585799303.4584534-279777979129889/AnsiballZ_bigip_ucs.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_ucs', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py\", line 718, in <module>\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py\", line 711, in main\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py\", line 310, in exec_module\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py\", line 327, in is_version_v1\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 529, in tmos_version\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 34, in api\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 58, in connect_via_token_auth\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 238, in post\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 193, in send\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/lib/python3.6/urllib/request.py\", line 223, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/usr/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_ucs_payload_buxewaif/ansible_bigip_ucs_payload.zip/ansible/module_utils/urls.py\", line 467, in https_open\n  File \"/usr/lib/python3.6/urllib/request.py\", line 1320, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno 111] Connection refused>\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ************************************************************************************************************************************************
qa-de-1a-f512-01           : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
