### ISSUE TITLE
bigip_software_install failing intermittently with error 54, Connection reset by peer (ansible 2.9) (Only with "activated" option)

### ISSUE THREAD

**Issue by arunhotra** [F5Networks/f5-ansible#1828]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_software_install
##### ANSIBLE VERSION

```
2.9.2
```

##### PYTHON VERSION

```
3.7
```

##### BIGIP VERSION

```
13.1

```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

While trying to upgrade BIG-IP, intermittently i am getting the following message and the playbook is stopping execution due to an error.I also increased the timeout value thinking that might help but it did not. Is there any documentation on when we would get this specific error and what can be done to get rid of it.

This goes away when the state is changed to "installed". However, changing to "installed" means we have to run a tmsh command to switchboot and boot into a new volume. 

Is this a bug with the "activated" state ?
 
##### STEPS TO REPRODUCE

```
- name: Install software on "{{ inventory_hostname }}"
  bigip_software_install:
    image: "{{ ISO_IMAGE }}"
    volume: "{{ volume }}"
    state: activated
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      server_port: 443
      timeout: 7200
      validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade
```

##### EXPECTED RESULTS

Successful upgrade and reboot into new volume expected

##### ACTUAL RESULTS

The ansible playbook fails after the BIG-IP reboots with the following message. BIG-IP successfully reboots but ansible playbook errors out.

```
TASK [upgrade : Install software on "B4200-R46-S39.sea.pslab.local"] *****************************************************************************************************************************************************************************************************************************************
task path: /Users/ganti/Code/automated-upgrades/ansible-upgrades/roles/upgrade/tasks/upgrade-standby.yml:9
META: noop
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/network/f5/bigip_software_install.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ganti
<localhost> EXEC /bin/sh -c '/usr/local/opt/python/bin/python3.7 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 523, in <module>
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 516, in main
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 297, in exec_module
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 318, in present
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 402, in update
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 436, in wait_for_device_reboot
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py", line 470, in read_volume_from_device
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py", line 34, in api
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py", line 58, in connect_via_token_auth
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 238, in post
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 193, in send
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/urls.py", line 1294, in open
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/urls.py", line 467, in https_open
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 330, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 215, in parse_headers
    line = fp.readline(_MAXLINE + 1)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer
fatal: [B4200-R46-S39.sea.pslab.local -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 523, in <module>\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 516, in main\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 297, in exec_module\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 318, in present\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 402, in update\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 436, in wait_for_device_reboot\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/modules/network/f5/bigip_software_install.py\", line 470, in read_volume_from_device\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 34, in api\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/bigip.py\", line 58, in connect_via_token_auth\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 238, in post\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 193, in send\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 543, in _open\n    '_open', req)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_software_install_payload_9vtsodfn/ansible_bigip_software_install_payload.zip/ansible/module_utils/urls.py\", line 467, in https_open\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py\", line 1320, in do_open\n    r = h.getresponse()\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py\", line 1336, in getresponse\n    response.begin()\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py\", line 330, in begin\n    self.headers = self.msg = parse_headers(self.fp)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py\", line 215, in parse_headers\n    line = fp.readline(_MAXLINE + 1)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py\", line 589, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py\", line 1071, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py\", line 929, in read\n    return self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 54] Connection reset by peer\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}``

**Comment by trinaths** [comment]
Not an issue with the module. We have made improvements to this module. Suggest use the latest module version.

Suggest use declarative collection f5_bigip. 

As per error

> ConnectionResetError: [Errno 54] Connection reset by peer

This is an TCP connection issue.  

Closing this issue.
