### ISSUE TITLE
Having issues with the bigip_qkview module

### ISSUE THREAD

**Issue by narasims** [F5Networks/f5-ansible#1831]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_qkview
##### ANSIBLE VERSION

```
ansible 2.9.12
  config file = /home/narasims/.virtenv/Python36_Ansible29_NET/ansible.cfg
  configured module search path = ['/home/narasims/NET/library']
  ansible python module location = /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible
  executable location = /home/narasims/.virtenv/Python36_Ansible29_NET/bin/ansible
  python version = 3.6.9 (default, Sep 11 2019, 16:40:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### PYTHON VERSION

```
Python 3.6.9
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.5
  Build       0.0.3
  Edition     Point Release 5
  Date        Sat May  9 09:31:20 PDT 2020
```

##### CONFIGURATION

```
# config file for ansible -- http://ansible.com/
# ==============================================

[defaults]

library        = /home/narasims/NET/library
roles_path    = /home/narasims/NET/roles
collections_paths = /home/narasims/.virtenv/Python36_Ansible29_NET/share/ansible/collections
vault_identity_list = /home/narasims/NET/.vault_pass
callback_plugins   = /home/narasims/NET/plugins/callback_plugins
playbook_dir = /home/narasims/NET/playbooks'
forks          = 200
transport = smart
remote_user = narasims
remote_tmp     = /tmp/$USER/.ansible
gather_subset = !ohai,!facter
host_key_checking = False
timeout = 120
verbosity = 1
module_name = shell
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M by narasims on {host}
system_warnings = True
deprecation_warnings = True
command_warnings = False

callback_whitelist = timer
stdout_callback = debug
retry_files_enabled = False
var_compression_level = 9
jinja2_extensions = jinja2.ext.do

[privilege_escalation]
become_ask_pass=False
become_method=sudo
become_flags="-iS"

[ssh_connection]

ssh_args = -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=4h
control_path = /tmp/ansible-narasims-%%h
pipelining = True
transfer_method = smart

[persistent_connection]

connect_timeout = 30
connect_retries = 30
connect_interval = 1
```
##### OS / ENVIRONMENT

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
Red Hat Enterprise Linux Server release 7.7 (Maipo)
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```
##### SUMMARY

I was using the bigip_qkview module to fetch the qkview to a destination and it's throwing the following error.
```
MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 607, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 600, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 230, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 274, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 296, in present
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 322, in execute
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 369, in execute_on_device
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_gfphf64r/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 478, in _wait_for_async_task_to_finish_on_device
KeyError: '_taskState'
```
##### STEPS TO REPRODUCE

```
       - name: Fetch a qkview from the remote device
         f5networks.f5_modules.bigip_qkview:
           complete_information: yes
           dest: /home/narasims/NET/tmp/{{ inventory_hostname }}.qkview
           provider:
             server: "{{ inventory_hostname }}"
             user: "{{ bigip_ltm_admin_user }}"
             password: "{{ bigip_ltm_admin_pass }}"
             validate_certs: "no"
             timeout: 1600
         delegate_to: localhost
```

##### EXPECTED RESULTS

I'm expecting that it should run and copy the qkview file to the destination.
##### ACTUAL RESULTS

it gives the same error.

```
TASK [Fetch a qkview from the remote device] ********************************************************************************************************************************************************************************************
task path: /home/narasims/NET/playbooks/test-f5-preinstall.yml:97
<localhost> connection transport is rest
Using module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol
Using module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils
Using module_utils file ansible_collections/f5networks/f5_modules/plugins
Using module_utils file ansible_collections
Using module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/basic.py
Using module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/common
Using module_utils file ansible_collections/f5networks/f5_modules
Using module_utils file ansible_collections/f5networks
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/urls.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/_text.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/compat/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/file.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/process.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/_utils.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/compat/selectors.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/validation.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/parameters.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/distro/_distro.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/compat/_selectors2.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/collections.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/connection.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/network/common/utils.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/network/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/network/common/__init__.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/network/common/config.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/json.py
Using module_utils file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/module_utils/common/network.py
Using module file /home/narasims/.virtenv/Python36_Ansible29_NET/share/ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: narasims
<localhost> EXEC /bin/sh -c '/home/narasims/.virtenv/Python36_Ansible29_NET/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 607, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 600, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 230, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 274, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 296, in present
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 322, in execute
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 369, in execute_on_device
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 478, in _wait_for_async_task_to_finish_on_device
KeyError: '_taskState'
fatal: [csdc-viprgst-test.core.oclc.org]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 607, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 600, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 230, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 274, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 296, in present
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 322, in execute
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 369, in execute_on_device
  File "/tmp/ansible_f5networks.f5_modules.bigip_qkview_payload_7n164mkm/ansible_f5networks.f5_modules.bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 478, in _wait_for_async_task_to_finish_on_device
KeyError: '_taskState'
```

**Comment by focrensh** [comment]
Are you able to confirm this is happening quickly after running the module or does it seem to be related to the timeout?

**Comment by narasims** [comment]
It took time. that's the reason I changed 1600 secs from 600 secs. and that didn't help either

**Comment by focrensh** [comment]
Currently I am not able to reproduce this. Will you please provide which modules you have provisioned?

**Comment by narasims** [comment]
Both LTM and AFM is provisioned on this guest.
root@(dsdc-viprgst-test)(cfg-sync Disconnected)(/S1-green-P::Active)(/Common)(tmos)# show sys provision 
      
---------------------------------------------------------
Sys::Provision
Module  CPU (%)  Memory (MB)  Host-Memory (MB)  Disk (MB)
---------------------------------------------------------
afm           1          327              1007       3900
am            0            0                 0          0
apm           0            0                 0          0
asm           0            0                 0          0
avr           0            0                 0          0
dos           0            0                 0          0
fps           0            0                 0          0
gtm           0            0                 0          0
host         10         2489                 0      68920
ilx           0            0                 0          0
lc            0            0                 0          0
ltm           1            0                 0          0
sslo          0            0                 0          0
swg           0            0                 0          0
tmos         88         2858                 0          0
urldb         0            0                 0          0

**Comment by focrensh** [comment]
Unfortunately even with the same modules I am not able to reproduce this issue. Please proceed with opening a support case if you are still experiencing this issue. Thanks,

**Comment by SoumenAbhishek** [comment]
@focrensh @caphrim007 can you please try with multiple hosts. I believe you should be able to reproduce the issue
