### ISSUE TITLE
bigip_vcmp_guest "provisioned" fails with [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by arunhotra** [F5Networks/f5-ansible#1836]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_vcmp_guest

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = None
  configured module search path = ['/Users/ganti/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]

```

##### PYTHON VERSION

```
3.7.4
```

##### BIGIP VERSION

```
13.1

```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Get the following error with bigip_vcmp_guest (changing to provision mode). This error happens with collection 1.4 and 1.5 but not with 1.3. Unfortunately there are other bugs which have been fixed in 1.4 and 1.5 which we have to use for a vcmp upgrade.

##### STEPS TO REPRODUCE

```
- name: VCMP guest provision mode "{{ item }}"
  bigip_vcmp_guest:
    name: "{{ item }}"
    state: provisioned
    provider: 
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
  register: result
  tags:
    - upgrade-hosts
```

##### EXPECTED RESULTS

Successful change to state provisioned

##### ACTUAL RESULTS

```
TASK [upgrade-hosts : VCMP guest provision mode "abcd-8"] ******************************************************************************************************************************************************************************************************
task path: /Users/ganti/Documents/BootCamps+Shadows+Customers+Certifications+Code/Customers/abcd/abcd-Ansible-Upgrades/VCMP-upgrades/ansible-upgrades-vcmp/roles/upgrade-hosts/tasks/provision-mode-guests.yml:1
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/network/f5/bigip_vcmp_guest.py
Pipelining is enabled.
<VIP2400-R17-S40.sea.pslab.local> ESTABLISH LOCAL CONNECTION FOR USER: ganti
<VIP2400-R17-S40.sea.pslab.local> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py", line 1017, in <module>
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py", line 1010, in main
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py", line 552, in exec_module
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py", line 564, in present
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py", line 627, in exists
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 232, in get
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/network/f5/icontrol.py", line 193, in send
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/urls.py", line 1294, in open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/urls.py", line 467, in https_open
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>
fatal: [VIP2400-R17-S40.sea.pslab.local]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py\", line 1017, in <module>\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py\", line 1010, in main\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py\", line 552, in exec_module\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py\", line 564, in present\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/modules/network/f5/bigip_vcmp_guest.py\", line 627, in exists\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 232, in get\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 193, in send\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 154, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 429, in open\n    response = self._open(req, data)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 447, in _open\n    '_open', req)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 407, in _call_chain\n    result = func(*args)\n  File \"/var/folders/94/gcvyc1g9191_npwtrl55hsq54jxlgs/T/ansible_bigip_vcmp_guest_payload_qOmsow/ansible_bigip_vcmp_guest_payload.zip/ansible/module_utils/urls.py\", line 467, in https_open\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py\", line 1198, in do_open\n    raise URLError(err)\nurllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by focrensh** [comment]
Tracking via FMFA-593

**Comment by KrithikaChidambaram** [comment]
Hi, have you tried with the latest version. Please reach out if you still face the issue.

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
