### ISSUE TITLE
Ansible Bigip_data_group not acting as documentation states

### ISSUE THREAD

**Issue by zaskan** [F5Networks/f5-ansible#1850]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

bigip_data_group module
##### ANSIBLE VERSION

```
ansible-playbook 2.9.7
```

##### PYTHON VERSION

```
python version = 3.6.8
```

##### BIGIP VERSION

```

```

##### SUMMARY

In the documentation the internal keyword states that internal: no is the default. The playbook does not run in our environment without internal set to yes.
##### STEPS TO REPRODUCE

```
- name: Create Test  Datagroup
  bigip_data_group:
    name: test
    type: string
    internal: yes
    partition: Common
    records:
      - key: test
        value: "test"
    state: present    
    provider:
      server: bigip
      user: admin
      password: admin
      validate_certs: no
  delegate_to: localhost
```

##### EXPECTED RESULTS

The playbook should run in our environment with internal set to yes.
##### ACTUAL RESULTS

```
PLAY [Test CIS F5 Create datagroups] *******************************************
TASK [Gathering Facts] *********************************************************
task path: /tmp/awx_2448_r700waf2/project/ansible-role-F5-create-datagroups.yml:3
<10.60.200.12> ESTABLISH LOCAL CONNECTION FOR USER: awx
<10.60.200.12> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<10.60.200.12> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp `"&& mkdir /var/lib/awx/.ansible/tmp/ansible-tmp-1599670621.6655993-14-244202418161278 && echo ansible-tmp-1599670621.6655993-14-244202418161278="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1599670621.6655993-14-244202418161278 `" ) && sleep 0'
<bigip1> Attempting python interpreter discovery
<10.60.200.12> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.60.200.12> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /var/lib/awx/venv/ntwksre/lib/python3.6/site-packages/ansible/modules/system/setup.py
<10.60.200.12> PUT /var/lib/awx/.ansible/tmp/ansible-local-7olc5wa9y/tmp4_en_5rs TO /var/lib/awx/.ansible/tmp/ansible-tmp-1599670621.6655993-14-244202418161278/AnsiballZ_setup.py
<10.60.200.12> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1599670621.6655993-14-244202418161278/ /var/lib/awx/.ansible/tmp/ansible-tmp-1599670621.6655993-14-244202418161278/AnsiballZ_setup.py && sleep 0'
<10.60.200.12> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1599670621.6655993-14-244202418161278/AnsiballZ_setup.py && sleep 0'
<10.60.200.12> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1599670621.6655993-14-244202418161278/ > /dev/null 2>&1 && sleep 0'
ok: [bigip1]
META: ran handlers
TASK [ansible-role-F5-create-datagroups : debug] *******************************
task path: /tmp/awx_2448_r700waf2/project/roles/ansible-role-F5-create-datagroups/tasks/main.yml:3
ok: [bigip1] => {
    "msg": " Datagroup version test"
}
TASK [ansible-role-F5-create-datagroups : CIS_T3f5_PP1_Create_Datagroup_DG_CISR_TIER2] ***
task path: /tmp/awx_2448_r700waf2/project/roles/ansible-role-F5-create-datagroups/tasks/main.yml:7
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp `"&& mkdir /var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932 && echo ansible-tmp-1599670623.0560076-165-1985673600932="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932 `" ) && sleep 0'
Using module file /var/lib/awx/venv/ntwksre/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_data_group.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-7olc5wa9y/tmp04d69ex9 TO /var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/ /var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/lib/awx/venv/ntwksre/bin/python3 /var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_data_group', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 1372, in <module>
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 1365, in main
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 1309, in exec_module
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 834, in exec_module
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 883, in present
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 1021, in create
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 1147, in create_on_device
  File "/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py", line 1122, in _upload_to_file
KeyError: 'name'
failed: [bigip1 -> localhost] (item={'key': 'test', 'value': {'dg_partition': 'Common', 'dg_type': 'string', 'dg_key': 'test', 'dg_value': 'test', 'dg_internal': False, 'dg_state': 'present'}}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "key": "test",
        "value": {
            "dg_internal": false,
            "dg_key": "test",
            "dg_partition": "Common",
            "dg_state": "present",
            "dg_type": "string",
            "dg_value": "test"
        }
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1599670623.0560076-165-1985673600932/AnsiballZ_bigip_data_group.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_data_group', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 1372, in <module>\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 1365, in main\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 1309, in exec_module\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 834, in exec_module\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 883, in present\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 1021, in create\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 1147, in create_on_device\n  File \"/tmp/ansible_bigip_data_group_payload_vauo0lt7/ansible_bigip_data_group_payload.zip/ansible/modules/network/f5/bigip_data_group.py\", line 1122, in _upload_to_file\nKeyError: 'name'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
PLAY RECAP *********************************************************************
bigip1                     : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by nmenant** [comment]
I can't reproduce your issue: 

I tried the following (this is my full ansible yaml file): 

```
---

  - name: Define connection
    hosts: all
    connection: local
  
    collections:
      - f5networks.f5_module
  
    tasks:
    - bigip_data_group:
        name: test
        type: string
        internal: yes
        partition: Common
        records:
          - key: test
            value: "test"
        state: present
        provider:
          server: 192.168.143.153
          user: admin
          password: xxxx
          validate_certs: no
      delegate_to: localhost
```

and i get the right config created (internal datagroup with the right config)


```
(Ansible) PAR-ML-00026375:Ansible menant$ ansible-playbook -i inventory/hosts site.yaml
PLAY [Define connection] ************************************************************************************************************************************************
TASK [Gathering Facts] **************************************************************************************************************************************************
[WARNING]: Platform darwin on host 192.168.143.153 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter
could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [192.168.143.153]
TASK [bigip_data_group] *************************************************************************************************************************************************
changed: [192.168.143.153]
PLAY RECAP **************************************************************************************************************************************************************
192.168.143.153            : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

if i use: 

```
---

  - name: Define connection
    hosts: all
    connection: local
  
    collections:
      - f5networks.f5_module
  
    tasks:
    - bigip_data_group:
        name: test
        type: string
        internal: no
        partition: Common
        records:
          - key: test
            value: "test"
        state: present
        provider:
          server: 192.168.143.153
          user: admin
          password: Cn1c0las123
          validate_certs: no
      delegate_to: localhost
```

```
(Ansible) PAR-ML-00026375:Ansible menant$ ansible-playbook -i inventory/hosts site.yaml

PLAY [Define connection] ************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************
[WARNING]: Platform darwin on host 192.168.143.153 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter
could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [192.168.143.153]

TASK [bigip_data_group] *************************************************************************************************************************************************
changed: [192.168.143.153]

PLAY RECAP **************************************************************************************************************************************************************
192.168.143.153            : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
``` 

if i check my BIG-IP: 

![image](https://user-images.githubusercontent.com/13098758/93092877-48838300-f6a0-11ea-9d3a-39ce9e0ee387.png)

![image](https://user-images.githubusercontent.com/13098758/93092934-5e914380-f6a0-11ea-86a0-f315363889ea.png)


![image](https://user-images.githubusercontent.com/13098758/93092973-6e108c80-f6a0-11ea-8a5a-0388cd3e4e67.png)

**Comment by wilpig** [comment]
I had the same issue as @zaskan  and the solution for me came down to needing quotes on the key and value so it looks weird double quoted, but works.

`    - name: Create data group
      bigip_data_group:
        provider: "{{ provider }}"
        name: "{{ item.path.split('.')[:-1]|join(' ') }}"
        internal: no
        state: present
        type: string
        separator: ":="
        records:
          - key: '"/partition/vip_name"'
            value: '"This can say whatever I want"'`
