### ISSUE TITLE
python3.8.2 and above interpreter breaks bigip_device_info

### ISSUE THREAD

**Issue by penghon** [F5Networks/f5-ansible#1851]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_device_info

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Sep 14 2020, 15:56:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### PYTHON VERSION

```
tested both Python 3.8.2 and Python 3.8.5

```

##### BIGIP VERSION

```
Product: BIG-IP
Version: 15.1.0.4
Build: 0.0.6
Sequence: 15.1.0.4-0.0.6.0
BaseBuild: 0.0.6
Edition: Point Release 4
Date: Thu Jun 18 20:31:45 PDT 2020
Built: 200618203145
Changelist: 3340959
JobID: 1207062

```

##### CONFIGURATION

[defaults]
retry_files_enabled = False
roles_path = ./roles

[bigip]
phltm14 ansible_host=172.28.22.142  ansible_python_interpreter=/usr/bin/python3

##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

Using the python3 as the ansible python interpreter the module bigip_device_info fails. Issue can be easily reproduced. 

##### STEPS TO REPRODUCE

Just run ansible-playbook -i hosts playbook_bigipinfo.yaml  -vvv

F5 collection fails with same error as the Upstreamed module to redhat: 

TASK [bigip device info] *********************************************************************************************************************************
task path: /ansible/playbook_bigipinfo.yaml:16
<172.28.22.142> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.28.22.142> EXEC /bin/sh -c 'echo ~root && sleep 0'
<172.28.22.142> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187 `" && echo ansible-tmp-1600074439.2376635-141050040811187="` echo /root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
<172.28.22.142> PUT /root/.ansible/tmp/ansible-local-29786xoc6limd/tmpygxf2ji4 TO /root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py
<172.28.22.142> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/ /root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py && sleep 0'
<172.28.22.142> EXEC /bin/sh -c 'F5_USER=admin F5_SERVER=172.28.22.142 F5_PASSWORD=admin F5_VALIDATE_CERTS=False F5_SERVER_PORT=443 /usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py && sleep 0'
<172.28.22.142> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 16608, in <module>
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 16592, in main
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 16327, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 16406, in execute_managers
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13722, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13728, in _exec_module
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 7324, in to_return
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13668, in hardware_information
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13677, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13677, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13682, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13674, in _transform_name_attribute
RuntimeError: dictionary keys changed during iteration
fatal: [phltm14]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1600074439.2376635-141050040811187/AnsiballZ_bigip_device_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 16608, in <module>\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 16592, in main\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 16327, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 16406, in execute_managers\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 13722, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 13728, in _exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 7324, in to_return\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 13668, in hardware_information\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 13677, in _transform_name_attribute\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 13677, in _transform_name_attribute\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 13682, in _transform_name_attribute\n  File \"/tmp/ansible_bigip_device_info_payload_7zid0n3k/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py\", line 13674, in _transform_name_attribute\nRuntimeError: dictionary keys changed during iteration\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
---
- name: test the F5 bigip_device_info module
  hosts: bigip
  gather_facts: no
  environment:
    F5_USER: admin
    F5_SERVER: "{{ ansible_host }}"
    F5_PASSWORD: admin
    F5_VALIDATE_CERTS: no
    F5_SERVER_PORT: 443
  connection: local
  # uncomment to use F5 ansible collections
  #collections:
  # - f5networks.f5_modules

  tasks:
  - name: bigip device info
    bigip_device_info:
      gather_subset:
        - all
    register: info
  - debug:
      var: info

```

##### EXPECTED RESULTS

BIG-IP info is successfully retrieved.
##### ACTUAL RESULTS

```
[root@handyman2 ansible]# ansible-playbook -i hosts playbook_bigipinfo.yaml  -vvv
ansible-playbook 2.9.6
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.2 (default, Sep 14 2020, 15:56:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /ansible/ansible.cfg as config file
host_list declined parsing /ansible/hosts as it did not pass its verify_file() method
script declined parsing /ansible/hosts as it did not pass its verify_file() method
auto declined parsing /ansible/hosts as it did not pass its verify_file() method
Parsed /ansible/hosts inventory source with ini plugin

PLAYBOOK: playbook_bigipinfo.yaml ***********************************************************************************************************************
1 plays in playbook_bigipinfo.yaml

PLAY [test the F5 bigip_device_info module] *************************************************************************************************************
META: ran handlers

TASK [bigip device info] ********************************************************************************************************************************
task path: /ansible/playbook_bigipinfo.yaml:14
<172.28.22.142> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.28.22.142> EXEC /bin/sh -c 'echo ~root && sleep 0'
<172.28.22.142> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184 `" && echo ansible-tmp-1 600072999.1892283-98778665364184="` echo /root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/site-packages/ansible/modules/network/f5/bigip_device_info.py
<172.28.22.142> PUT /root/.ansible/tmp/ansible-local-28137e_2jhdz3/tmp3goiqwzf TO /root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/Ansiba llZ_bigip_device_info.py
<172.28.22.142> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/ /root/.ansible/tmp/ansible-tmp-1600072999.18 92283-98778665364184/AnsiballZ_bigip_device_info.py && sleep 0'
<172.28.22.142> EXEC /bin/sh -c 'F5_USER=admin F5_SERVER=172.28.22.142 F5_PASSWORD=admin F5_VALIDATE_CERTS=False F5_SERVER_PORT=443 /usr/bin/python3 /roo t/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/AnsiballZ_bigip_device_info.py && sleep 0'
<172.28.22.142> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/AnsiballZ_bigip_device_info.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/AnsiballZ_bigip_device_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/AnsiballZ_bigip_device_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1626 6, in <module>
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1625 9, in main
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1599 9, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1607 8, in execute_managers
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1344 5, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1345 1, in _exec_module
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 7092 , in to_return
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1339 1, in hardware_information
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1340 0, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1340 0, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1340 5, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 1339 7, in _transform_name_attribute
RuntimeError: dictionary keys changed during iteration
fatal: [phltm14]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/AnsiballZ_bigip_devic e_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1600072999.1892283-98778665364184/AnsiballZ_bigip_devi ce_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1600072999 .1892283-98778665364184/AnsiballZ_bigip_device_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_devi ce_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run _module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod _globals, init_globals,\n  File \"/usr/local/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_de vice_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16266, in <module>\n  File \"/tm p/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16259, in main \n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line  15999, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_de vice_info.py\", line 16078, in execute_managers\n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/m odules/network/f5/bigip_device_info.py\", line 13445, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_ payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 13451, in _exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansi ble_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 7092, in to_return\n  File \"/tmp/ansible_bigip_device_info_pay load_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 13391, in hardware_information\n  File \"/tmp /ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 13400, in _tran sform_name_attribute\n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_dev ice_info.py\", line 13400, in _transform_name_attribute\n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansible_bigip_device_info_payload.zip/a nsible/modules/network/f5/bigip_device_info.py\", line 13405, in _transform_name_attribute\n  File \"/tmp/ansible_bigip_device_info_payload_p20vfkqc/ansi ble_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 13397, in _transform_name_attribute\nRuntimeError: dictionary k eys changed during iteration\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **********************************************************************************************************************************************
phltm14                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by wojtek0806** [comment]
here is solution to your issue:

https://github.com/F5Networks/f5-ansible/issues/1804

**Comment by wojtek0806** [comment]
issue does not exist in current devel build of collection, tested on 3.8.5 ansible. Try with collection 1.5 and if the issue exists there, once we release 1.6 (current devel) it will be available on galaxy. For now check the readme file in this repo on how to download the latest development version
