### ISSUE TITLE
bigip_firewall_address_list errors on release 1.5.0 and 1.6.0-devel

### ISSUE THREAD

**Issue by DonPrice** [F5Networks/f5-ansible#1853]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_firewall_address_list

##### ANSIBLE VERSION

```
ansible 2.9.6
```

##### PYTHON VERSION

```
python version = 3.8.2
```

##### BIGIP VERSION

```
15.1.0.4
```

##### SUMMARY

When executing bigip_firewall_address_list.py an error is returned even though the change is implemented on the device.

##### STEPS TO REPRODUCE

```
- name: Security Configuration - Address List (internalV4_addresses)
      bigip_firewall_address_list:
              name: internalV4_addresses
              addresses:
                      - 10.0.1.0/24
                      - 10.0.200.0/24
```

##### EXPECTED RESULTS

Address List to create with CIDR IP's specified and not error.

##### ACTUAL RESULTS

```
10.0.1.142> EXEC /bin/sh -c 'echo ~donovanp && sleep 0'
<10.0.1.142> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414 `" && echo ansible-tmp-1600210120.3331816-150350883670414="` echo /home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414 `" ) && sleep 0'
Using module file /home/donovanp/pemBuild/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py
<10.0.1.142> PUT /home/donovanp/.ansible/tmp/ansible-local-3653033d0gi1ndx/tmp7xbqeaef TO /home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py
<10.0.1.142> EXEC /bin/sh -c 'chmod u+x /home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/ /home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py && sleep 0'
<10.0.1.142> EXEC /bin/sh -c 'F5_SERVER=10.0.1.142 F5_USER=admin F5_PASSWORD=xxxxxxxxx F5_VALIDATE_CERTS=false F5_SERVER_PORT=443 /usr/bin/python3 /home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py && sleep 0'
<10.0.1.142> EXEC /bin/sh -c 'rm -f -r /home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py", line 102, in <module>
    _ansiballz_main()
  File "/home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_firewall_address_list', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 987, in <module>
  File "/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 980, in main
  File "/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 786, in exec_module
  File "/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 609, in to_return
  File "/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py", line 620, in addresses
TypeError: 'NoneType' object is not iterable
fatal: [10.0.1.142]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/donovanp/.ansible/tmp/ansible-tmp-1600210120.3331816-150350883670414/AnsiballZ_bigip_firewall_address_list.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_firewall_address_list', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 987, in <module>\n  File \"/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 980, in main\n  File \"/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 786, in exec_module\n  File \"/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 609, in to_return\n  File \"/tmp/ansible_bigip_firewall_address_list_payload_ou7n7va8/ansible_bigip_firewall_address_list_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_firewall_address_list.py\", line 620, in addresses\nTypeError: 'NoneType' object is not iterable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}


```

**Comment by focrensh** [comment]
Tracking with FMFA-617
