### ISSUE TITLE
bigip_profile_http header_insert does not accept multiple colon (:) characters

### ISSUE THREAD

**Issue by Learloj** [F5Networks/f5-ansible#1910]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_profile_http

##### ANSIBLE VERSION

```
ansible 2.9.14
  config file = /Users/basr/.ansible.cfg
  configured module search path = ['/Users/basr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Oct 27 2020, 14:15:17) [Clang 12.0.0 (clang-1200.0.32.21)]
```

##### PYTHON VERSION

```
Python 3.9.0
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.3
  Build       0.0.12
  Edition     Point Release 3
  Date        Tue Apr 28 22:27:02 PDT 2020
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When trying to set a HTTP header via header_insert of which the value contains a colon, the module fails with an "Invalid header format" error.

This seems to be caused by ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py in check_header_validity:
```
def check_header_validity(header):
...
    try:
        name, value = header.split(':')
    except ValueError:
        raise F5ModuleError('Invalid header format: {0}'.format(header))
```

When you pass a header like `X-Graylog-Server-URL: https://fully.qualified.domain/`, this will break:
```
>>> header = "X-Graylog-Server-URL: https://fully.qualified.domain/"
>>> name, value = header.split(':')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack (expected 2)
```

##### STEPS TO REPRODUCE

```
- name: Create HTTP profile for external GUI
  bigip_profile_http:
    provider: "{{ bigip_provider }}"
    name: graylogcluster_http_tpl
    state: present
    parent: /Common/http
    partition: Services
    header_insert: X-Graylog-Server-URL: https://fully.qualified.domain/
```

##### EXPECTED RESULTS

HTTP profile to be created/updated, with the proper 'Request Header Insert' set to the requested URL.

##### ACTUAL RESULTS

```
TASK [f5 : Create HTTP profile for external GUI] *********************************************************************************************************************************************************************************************
task path: /Users/user/code/apps/graylog-cluster/ansible/roles/f5/tasks/configure.yaml:79
META: noop
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~user && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/user/.ansible/tmp `"&& mkdir "` echo /Users/user/.ansible/tmp/ansible-tmp-1605012356.4582982-5582-74549315388007 `" && echo ansible-tmp-1605012356.4582982-5582-74549315388007="` echo /Users/user/.ansible/tmp/ansible-tmp-1605012356.4582982-5582-74549315388007 `" ) && sleep 0'
Using module file /usr/local/lib/python3.9/site-packages/ansible/modules/network/f5/bigip_profile_http.py
<localhost> PUT /Users/user/.ansible/tmp/ansible-local-4278llxko9lg/tmp3k570imd TO /Users/user/.ansible/tmp/ansible-tmp-1605012356.4582982-5582-74549315388007/AnsiballZ_bigip_profile_http.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/user/.ansible/tmp/ansible-tmp-1605012356.4582982-5582-74549315388007/ /Users/user/.ansible/tmp/ansible-tmp-1605012356.4582982-5582-74549315388007/AnsiballZ_bigip_profile_http.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/opt/python@3.9/bin/python3.9 /Users/user/.ansible/tmp/ansible-tmp-1605012356.4582982-5582-74549315388007/AnsiballZ_bigip_profile_http.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/user/.ansible/tmp/ansible-tmp-1605012356.4582982-5582-74549315388007/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1750, in main
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1515, in exec_module
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1535, in present
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1546, in update
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1504, in should_update
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1490, in _update_changed_options
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1367, in compare
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 1416, in header_insert
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/modules/network/f5/bigip_profile_http.py", line 994, in header_insert
  File "/var/folders/9y/4d8l81192sz2l24kqk1jz2br0000gn/T/ansible_bigip_profile_http_payload_x5i3jqi4/ansible_bigip_profile_http_payload.zip/ansible/module_utils/network/f5/urls.py", line 34, in check_header_validity
    raise F5ModuleError('Invalid header format: {0}'.format(header))
[WARNING]: Module did not set no_log for update_password
fatal: [lb3]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_xff": null,
            "description": null,
            "dns_resolver": null,
            "encrypt_cookie_secret": null,
            "encrypt_cookies": null,
            "enforcement": null,
            "fallback_host": null,
            "fallback_status_codes": null,
            "header_erase": null,
            "header_insert": "X-Graylog-Server-URL: https://fully.qualified.domain/",
            "hsts_mode": null,
            "include_subdomains": null,
            "insert_xforwarded_for": null,
            "maximum_age": null,
            "name": "graylogcluster_http_tpl",
            "oneconnect_transformations": null,
            "parent": "/Common/http",
            "partition": "Services",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "lb3.domain.tld",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "user",
                "validate_certs": false
            },
            "proxy_type": null,
            "redirect_rewrite": null,
            "request_chunking": null,
            "response_chunking": null,
            "server_agent_name": null,
            "sflow": null,
            "state": "present",
            "update_password": "always",
            "xff_alternative_names": null
        }
    }
}

MSG:

Invalid header format: X-Graylog-Server-URL: https://fully.qualified.domain/
```

**Comment by Learloj** [comment]
It seems to me that a fix could be as easy as changing:
```
        name, value = header.split(':')
```
into:
```
        name, value = header.split(':', 1)
```

I've tested this in both python2 and 3, and both results in:
```
>>> header = "X-Graylog-Server-URL: https://fully.qualified.domain/"
>>> header.split(":", 1)
['X-Graylog-Server-URL', ' https://fully.qualified.domain/']
```

**Comment by jewettg** [comment]
I appreciate @Learloj for posting this bug.  I really hope this get included soon! ;-)

**Comment by focrensh** [comment]
Thank you for investigating this. Tracking via FMFA-669.Th

**Comment by wojtek0806** [comment]
you are working on wrong collection version, this issue has been addressed here:
https://github.com/F5Networks/f5-ansible/pull/1533

**Comment by jewettg** [comment]
@wojtek0806 and @focrensh 
I do not understand how this is fixed.  I have using collection version 1.6.0, which is the version on Ansible Galaxy.  I am still having difficulties. 

Version installed on my computer...

`$ ansible-galaxy collection list -p /etc/ansible/collections`
`#  /etc/ansible/collections/ansible_collections`
`Collection            Version`
`--------------------- -------`
`f5networks.f5_modules 1.6.0`

What Ansible-Galaxy is saying....

`$ ansible-galaxy collection list f5networks.f5_modules`
`# /etc/ansible/collections/ansible_collections`
`Collection            Version`
`--------------------- -------`
`f5networks.f5_modules 1.6.0`
