### ISSUE TITLE
teem SSL settings does not honor provider

### ISSUE THREAD

**Issue by VeselaHouba** [F5Networks/f5-ansible#1933]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
teem
https://github.com/F5Networks/f5-ansible/blob/11d18d2e324ab07acb0be15da1fb38016797f140/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py#L74

https://github.com/F5Networks/f5-ansible/blob/11d18d2e324ab07acb0be15da1fb38016797f140/ansible_collections/f5networks/f5_modules/plugins/module_utils/constants.py#L32

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/opt/f5-ansible/library']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Nov 25 2020, 02:57:50) [GCC 9.3.0]
```

##### PYTHON VERSION
```
Python 3.8.6
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3.4
  Build       0.0.5
  Edition     Point Release 4
  Date        Tue Jun 16 14:26:18 PDT 2020
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Teem component seems to require SSL validation, even though provider is set to `validate_certs: false`. Issue being thrown on `bigip_irule`, but probably affects another modules too.

##### STEPS TO REPRODUCE
f5_provider:
```
---
f5_provider:
  server: "{{ ansible_host }}"
  password: "{{ f5_provider_password }}"
  user: ansible
  validate_certs: false
```

iRules task
```
- name: Manage iRules
  bigip_irule:
    provider: "{{ f5_provider }}"
    module: ltm
    src: "{{ item.file|default(role_path+'/files/iRules/'+item.name+'.tcl') }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    partition: "{{ item.partition | default(omit) }}"
  with_items: "{{ f5_iRules_list }}"
  delegate_to: localhost
  loop_control:
    label: "{{ item.name }} | {{ item.state|default('present') }}"
```

##### EXPECTED RESULTS
```
ok: [<ansible_host> -> localhost] => (item=<irule_name> | present)
```

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1124)>
failed: [<ansible_host> -> localhost] (item=<irule_name> | present) => changed=false
  ansible_loop_var: item
  item:
	file: ../files/iRules/<irule_name>.tcl
	name: <irule_name>
  module_stderr: |-
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
		h.request(req.get_method(), req.selector, req.data, headers,
	  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
		self._send_request(method, url, body, headers, encode_chunked)
	  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
		self.endheaders(body, encode_chunked=encode_chunked)
	  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
		self._send_output(message_body, encode_chunked=encode_chunked)
	  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
		self.send(msg)
	  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
		self.connect()
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible/module_utils/urls.py", line 430, in connect
	  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
		return self.sslsocket_class._create(
	  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
		self.do_handshake()
	  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
		self._sslobj.do_handshake()
	ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1124)
 
	During handling of the above exception, another exception occurred:
 
	Traceback (most recent call last):
	  File "/root/.ansible/tmp/ansible-tmp-1607521826.7842958-237604005845375/AnsiballZ_bigip_irule.py", line 102, in <module>
		_ansiballz_main()
	  File "/root/.ansible/tmp/ansible-tmp-1607521826.7842958-237604005845375/AnsiballZ_bigip_irule.py", line 94, in _ansiballz_main
		invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
	  File "/root/.ansible/tmp/ansible-tmp-1607521826.7842958-237604005845375/AnsiballZ_bigip_irule.py", line 40, in invoke_module
		runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_irule', init_globals=None, run_name='main', alter_sys=True)
	  File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
		return _run_module_code(code, init_globals, run_name, mod_spec)
	  File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
		_run_code(code, mod_globals, init_globals,
	  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
		exec(code, run_globals)
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_irule.py", line 568, in <module>
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_irule.py", line 561, in main
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_irule.py", line 227, in exec_module
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_irule.py", line 295, in exec_module
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 128, in send_teem
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 69, in send
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible/module_utils/urls.py", line 1384, in open_url
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible/module_utils/urls.py", line 1294, in open
	  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
		return opener.open(url, data, timeout)
	  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
		response = self._open(req, data)
	  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
		result = self._call_chain(self.handle_open, protocol, protocol +
	  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
		result = func(*args)
	  File "/tmp/ansible_bigip_irule_payload_e98d3smv/ansible_bigip_irule_payload.zip/ansible/module_utils/urls.py", line 443, in https_open
	  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
		raise URLError(err)
	urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1124)>
  module_stdout: ''
  msg: |-
	MODULE FAILURE
	See stdout/stderr for the exact error
  rc: 1
```

### Workaround
When I manually overwrite 
```
sed -i 's/TEEM_VERIFY = True/TEEM_VERIFY = False/g' ansible_collections/f5networks/f5_modules/plugins/module_utils/constants.py 
```
Then there's no issue.

**Comment by wojtek0806** [comment]
the teem settings for connection are not to be modified, i will add better error handling to fix that

**Comment by VeselaHouba** [comment]
Just confirming that everything works fine now. Thanks @wojtek0806
