### ISSUE TITLE
bigiq_device_info returning 'dictionary keys changed during iteration' when choices == all

### ISSUE THREAD

**Issue by onurbrc** [F5Networks/f5-ansible#1934]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
```
bigiq_device_info
```

##### ANSIBLE VERSION

```
Ansible 2.10.3
Collections 1.6.0 
```

##### PYTHON VERSION
```
python3.8
```

##### BIGIQ VERSION

```
BIG-IQ Virtual Edition  7.1.0.2-0.0.21
```

##### CONFIGURATION
```
[defaults]
roles_path           = ./roles       # ANSIBLE_ROLES_PATH 
inventory            = ./inventory   # ANSIBLE_INVENTORY
collections_path     = ~/.ansible/collections     # ANSIBLE_COLLECTIONS_PATH
force_color          = 1
gathering            = smart
callback_whitelist   = profile_tasks
deprecation_warnings = False
command_warnings     = False
host_key_checking    = False

[ssh_connection]
ssh_args  = -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no

[inventory]
enable_plugins=generator,host_list,script,yaml,ini

```

##### SUMMARY
Trying to get device information about using **all** in gather_subset

##### STEPS TO REPRODUCE
Playbook:

```
  tasks:
    - name: Collect all BIG-IQ information
      bigiq_device_info:
        gather_subset:
            - all
        provider: "{{ connectionParams }}"
      delegate_to: localhost
      register: __output

    - name: Show result
      debug:
        msg: "{{ __output }}"
```

##### EXPECTED RESULTS
Success getting information 

##### ACTUAL RESULTS

Getting ***RuntimeError: dictionary keys changed during iteration***

Logs:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-tmp-1607638908.6029112-16302-211484396931924/AnsiballZ_bigiq_device_info.py", line 102, in <module>
    _ansiballz_main()
  File "/home/admin/.ansible/tmp/ansible-tmp-1607638908.6029112-16302-211484396931924/AnsiballZ_bigiq_device_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/admin/.ansible/tmp/ansible-tmp-1607638908.6029112-16302-211484396931924/AnsiballZ_bigiq_device_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigiq_device_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 2315, in <module>
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 2301, in main
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 2190, in exec_module
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 2234, in execute_managers
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 1679, in exec_module
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 1685, in _exec_module
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 946, in to_return
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 1625, in hardware_information
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 1634, in _transform_name_attribute
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 1634, in _transform_name_attribute
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 1639, in _transform_name_attribute
  File "/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py", line 1631, in _transform_name_attribute
RuntimeError: dictionary keys changed during iteration
fatal: [licensemanager.mydomain.com]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1607638908.6029112-16302-211484396931924/AnsiballZ_bigiq_device_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1607638908.6029112-16302-211484396931924/AnsiballZ_bigiq_device_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1607638908.6029112-16302-211484396931924/AnsiballZ_bigiq_device_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigiq_device_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 2315, in <module>\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 2301, in main\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 2190, in exec_module\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 2234, in execute_managers\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 1679, in exec_module\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 1685, in _exec_module\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 946, in to_return\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 1625, in hardware_information\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 1634, in _transform_name_attribute\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 1634, in _transform_name_attribute\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 1639, in _transform_name_attribute\n  File \"/tmp/ansible_bigiq_device_info_payload_g8mxdyfg/ansible_bigiq_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_info.py\", line 1631, in _transform_name_attribute\nRuntimeError: dictionary keys changed during iteration\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by wojtek0806** [comment]
yes we are aware of this bug, is on our to do list for next release
