### ISSUE TITLE
qkview fails in 2.10 (same config works with 2.8)

### ISSUE THREAD

**Issue by arunhotra** [F5Networks/f5-ansible#1954]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_qkview

##### ANSIBLE VERSION

```
NOT WORKING


ansible 2.10.3
  config file = /apps/usr/local/home/s002927/TEST/ansible.cfg
  configured module search path = ['/apps/usr/local/home/s002927/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /apps/usr/local/bin/python3/lib/python3.6/site-packages/ansible
  executable location = /apps/usr/local/bin/python3/bin/ansible
  python version = 3.6.9 (default, Jun 24 2020, 17:32:29) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]```

WORKING


ansible 2.8.0
  config file = None
  configured module search path = [u'/apps/usr/local/home/s002927/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /apps/usr/local/lib/python2.7/site-packages/ansible
  executable location = /apps/usr/local/bin/ansible
  python version = 2.7.11 (default, Jan  5 2016, 13:18:00) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]

```

##### BIGIP VERSION

```
 
----------------------------------------------------------
Sys::Software Status
Volume  Slot  Product   Version    Build  Active    Status
----------------------------------------------------------
HD1.1      1   BIG-IP  13.1.0.1    0.0.8      no  complete
HD1.2      1   BIG-IP    12.1.3  0.0.378      no  complete
HD1.3      1   BIG-IP  13.1.1.5    0.0.4     yes  complete

```

##### CONFIGURATION

Pasting from the logs

    "invocation": {
        "module_args": {
            "asm_request_log": false,
            "auth_provider": null,
            "complete_information": false,
            "dest": "/apps/usr/local/home/s002927/TEST/BACKUPS/C042ABCDEF/abxx.net.us.customername.net.qkview",
            "exclude": null,
            "exclude_core": false,
            "filename": "abxxx.customername.net.qkview",
            "force": true,
            "max_file_size": null,
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "abxxbcd.net.us.customername.net",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "server": null,
            "server_port": null,
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    }
}

##### OS / ENVIRONMENT

Linux jumphost

##### SUMMARY

Qkview fails - works in 2.8

##### STEPS TO REPRODUCE

Try on VCMP host

##### EXPECTED RESULTS

qkview 

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/apps/usr/local/bin/python3/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/apps/usr/local/bin/python3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/apps/usr/local/bin/python3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 591, in <module>
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 584, in main
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 220, in exec_module
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py", line 261, in exec_module
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 99, in send_teem
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 70, in send
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py", line 1399, in open_url
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py", line 1304, in open
  File "/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py", line 464, in https_open
  File "/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
Exception ignored in: <bound method iControlRestSession.__del__ of <ansible_collections.f5networks.f5_modules.plugins.module_utils.icontrol.iControlRestSession object at 0x7ff341d3ccf8>>
Traceback (most recent call last):
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 255, in __del__
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 230, in delete
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 194, in send
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py", line 1222, in open
  File "/apps/usr/local/bin/python3/lib/python3.6/netrc.py", line 32, in __init__
NameError: name 'open' is not defined
Exception ignored in: <bound method iControlRestSession.__del__ of <ansible_collections.f5networks.f5_modules.plugins.module_utils.icontrol.iControlRestSession object at 0x7ff3411c9c50>>
Traceback (most recent call last):
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 255, in __del__
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 230, in delete
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 194, in send
  File "/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py", line 1222, in open
  File "/apps/usr/local/bin/python3/lib/python3.6/netrc.py", line 32, in __init__
NameError: name 'open' is not defined
fatal: [d860059adc914.net.us.customer.net]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py\", line 1318, in do_open\n    encode_chunked=req.has_header('Transfer-encoding'))\n  File \"/apps/usr/local/bin/python3/lib/python3.6/http/client.py\", line 1254, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/http/client.py\", line 1300, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/http/client.py\", line 1249, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/http/client.py\", line 1036, in _send_output\n    self.send(msg)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/http/client.py\", line 974, in send\n    self.connect()\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py\", line 433, in connect\n  File \"/apps/usr/local/bin/python3/lib/python3.6/socket.py\", line 724, in create_connection\n    raise err\n  File \"/apps/usr/local/bin/python3/lib/python3.6/socket.py\", line 713, in create_connection\n    sock.connect(sa)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/apps/usr/local/bin/python3/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 591, in <module>\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 584, in main\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 220, in exec_module\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_qkview.py\", line 261, in exec_module\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 99, in send_teem\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 70, in send\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py\", line 1399, in open_url\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py\", line 1304, in open\n  File \"/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py\", line 223, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py\", line 464, in https_open\n  File \"/apps/usr/local/bin/python3/lib/python3.6/urllib/request.py\", line 1320, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error timed out>\nException ignored in: <bound method iControlRestSession.__del__ of <ansible_collections.f5networks.f5_modules.plugins.module_utils.icontrol.iControlRestSession object at 0x7ff341d3ccf8>>\nTraceback (most recent call last):\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 255, in __del__\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 230, in delete\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 194, in send\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py\", line 1222, in open\n  File \"/apps/usr/local/bin/python3/lib/python3.6/netrc.py\", line 32, in __init__\nNameError: name 'open' is not defined\nException ignored in: <bound method iControlRestSession.__del__ of <ansible_collections.f5networks.f5_modules.plugins.module_utils.icontrol.iControlRestSession object at 0x7ff3411c9c50>>\nTraceback (most recent call last):\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 255, in __del__\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 230, in delete\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 194, in send\n  File \"/tmp/ansible_bigip_qkview_payload__pr2e0ce/ansible_bigip_qkview_payload.zip/ansible/module_utils/urls.py\", line 1222, in open\n  File \"/apps/usr/local/bin/python3/lib/python3.6/netrc.py\", line 32, in __init__\nNameError: name 'open' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by trinaths** [comment]
Use the latest version of the collection (1.7) not the community based one. This issue fixed in https://github.com/F5Networks/f5-ansible/issues/1933
