### ISSUE TITLE
bigip_software_install with state activated fails code but does execute command

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [F5Networks/f5-ansible#1987]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_software_install

##### ANSIBLE VERSION

```
ansible 2.10.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### PYTHON VERSION

```
Python 3.6.8

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3.5
  Build       0.30.5
  Edition     Engineering Hotfix
  Date        Sun Dec 27 22:52:35 PST 2020

Hotfix List
ID727031-1
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT

```
Red Hat Enterprise Linux Server release 7.8 (Maipo)
```

##### SUMMARY
Executing code will still do the upgrade/reboot however the code fails so the pausing part of the upgrade between HA nodes which happens when using the Installed works correctly however the activated command which should do the same as installed but change boot drive and reboot throws error and doesnt wait.

##### STEPS TO REPRODUCE
Install Latest galaxy for F5 Collection
Run Playbook that does upgrade with the "activated" state 

```
  - name: Group 1 Activate Image (Will Cause Reboot)
    bigip_software_install:
      provider: "{{ provider }}"
      image: "{{ new_image }}"
      state: activated
      volume: "{{ dest_boot_loc }}"

```

##### EXPECTED RESULTS
Code executes with installs OS with partition boot active change and reboot with no errors.

##### ACTUAL RESULTS

```
TASK [Group 1 Activate Image (Will Cause Reboot)] ******************************************************************************************************************************************************************
task path: /git/f5-upgrade/upgrade.yaml:130
<illumio1-13> ESTABLISH LOCAL CONNECTION FOR USER: root
<illumio1-13> EXEC /bin/sh -c 'echo ~root && sleep 0'
<illumio1-13> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438 `" && echo ansible-tmp-1615415855.3834314-11458-251634091235438="` echo /root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py
<illumio1-13> PUT /root/.ansible/tmp/ansible-local-11274a7wb_aqn/tmpd6g6r2wi TO /root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py
<illumio1-13> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/ /root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py && sleep 0'
<illumio1-13> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py && sleep 0'
<illumio1-13> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_software_install', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py", line 717, in <module>
  File "/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py", line 710, in main
  File "/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py", line 440, in exec_module
  File "/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py", line 462, in present
  File "/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py", line 578, in update
  File "/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py", line 641, in wait_for_software_install_on_device
  File "/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py", line 528, in volume_exists
KeyError: 'media'
fatal: [illumio1-13]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1615415855.3834314-11458-251634091235438/AnsiballZ_bigip_software_install.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_software_install', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py\", line 717, in <module>\n  File \"/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py\", line 710, in main\n  File \"/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py\", line 440, in exec_module\n  File \"/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py\", line 462, in present\n  File \"/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py\", line 578, in update\n  File \"/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py\", line 641, in wait_for_software_install_on_device\n  File \"/tmp/ansible_bigip_software_install_payload_cmnxeal0/ansible_bigip_software_install_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_install.py\", line 528, in volume_exists\nKeyError: 'media'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

NO MORE HOSTS LEFT *************************************************************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************************************
illumio1-13                : ok=13   changed=4    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

```

**Comment by nmenant** [comment]
Tracking this issue internally with INFRAANO-248

**Comment by VDI-Tech-Guy** [comment]
Will also note BIG-IP Version didnt matter tested on 13.1.x, 14.1.x, 15.1.x and 16.0.1 all had same issue

**Comment by trinaths** [comment]
Resolved with PR: https://github.com/F5Networks/f5-ansible/pull/2068
