### ISSUE TITLE
bigip_apm_acl IndexError: list index out of range

### ISSUE THREAD

**Issue by ssaammoo** [F5Networks/f5-ansible#2006]
##### COMPONENT NAME

bigip_apm_acl

### Environment
Production
##### ANSIBLE VERSION

```
ansible 2.10.7
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.0.1.1
  Build       0.9.6
  Edition     Engineering Hotfix
  Date        Thu Mar 18 21:05:39 PDT 2021

Hotfix List
ID1002561-6
```
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.9 (Maipo)

##### SUMMARY

bigip_apm_acl is giving following error: IndexError: list index out of range
##### STEPS TO REPRODUCE

Run below Playbook

```
- name: Test APM ACL creation
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    acl_description: This ACL is created by Ansible
    f5_password: <F5 password>
    f5_servername: <F5 device hostname>
    f5_username: admin
    server_port: 443
    acl_order: 65535
    acl_name: test_acl
  tasks:
    - debug: 
        var: zain_acl
  
    - name: Manage user-defined APM ACLs
      f5networks.f5_modules.bigip_apm_acl:
        description: "{{ acl_description }}"
        name: "{{ acl_name }}"
        type: static 
        entries:
          - action: allow
            dst_addr: 192.168.0.7
            dst_port: "*"
            log: none
            protocol: all
            src_addr: any
            src_port: "*"
          - action: allow
            dst_addr: 192.168.0.19
            dst_port: "*"
            log: none
            protocol: all
            src_addr: any
            src_port: "*"
          - action: allow
            dst_addr: 192.168.0.20
            dst_port: "*"
            log: none
            protocol: all
            src_addr: any
            src_port: "*"
```

##### EXPECTED RESULTS

New ACL to be created with mentioned entries
##### ACTUAL RESULTS

Error the list is out of index

```
Loading collection ansible.netcommon from /root/.ansible/collections/ansible_collections/ansible/netcommon
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132 `" && echo ansible-tmp-1617565043.532786-49046-108620439017132="` echo /root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132 `" ) && sleep 0'
Including module_utils file ansible/__init__.py
Including module_utils file ansible/module_utils/__init__.py
Including module_utils file ansible/module_utils/basic.py
Including module_utils file ansible/module_utils/_text.py
Including module_utils file ansible/module_utils/common/_collections_compat.py
Including module_utils file ansible/module_utils/common/__init__.py
Including module_utils file ansible/module_utils/common/_json_compat.py
Including module_utils file ansible/module_utils/common/_utils.py
Including module_utils file ansible/module_utils/common/file.py
Including module_utils file ansible/module_utils/common/parameters.py
Including module_utils file ansible/module_utils/common/collections.py
Including module_utils file ansible/module_utils/common/process.py
Including module_utils file ansible/module_utils/common/sys_info.py
Including module_utils file ansible/module_utils/common/text/converters.py
Including module_utils file ansible/module_utils/common/text/__init__.py
Including module_utils file ansible/module_utils/common/text/formatters.py
Including module_utils file ansible/module_utils/common/validation.py
Including module_utils file ansible/module_utils/common/warnings.py
Including module_utils file ansible/module_utils/compat/selectors.py
Including module_utils file ansible/module_utils/compat/__init__.py
Including module_utils file ansible/module_utils/compat/_selectors2.py
Including module_utils file ansible/module_utils/distro/__init__.py
Including module_utils file ansible/module_utils/distro/_distro.py
Including module_utils file ansible/module_utils/parsing/convert_bool.py
Including module_utils file ansible/module_utils/parsing/__init__.py
Including module_utils file ansible/module_utils/pycompat24.py
Including module_utils file ansible/module_utils/six/__init__.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip.py
Including module_utils file ansible_collections/__init__.py
Including module_utils file ansible_collections/f5networks/__init__.py
Including module_utils file ansible_collections/f5networks/f5_modules/__init__.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/__init__.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/__init__.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/common.py
Including module_utils file ansible/module_utils/connection.py
Including module_utils file ansible/module_utils/common/json.py
Including module_utils file ansible_collections/ansible/netcommon/plugins/module_utils/network/common/config.py
Including module_utils file ansible_collections/ansible/__init__.py
Including module_utils file ansible_collections/ansible/netcommon/__init__.py
Including module_utils file ansible_collections/ansible/netcommon/plugins/__init__.py
Including module_utils file ansible_collections/ansible/netcommon/plugins/module_utils/__init__.py
Including module_utils file ansible_collections/ansible/netcommon/plugins/module_utils/network/__init__.py
Including module_utils file ansible_collections/ansible/netcommon/plugins/module_utils/network/common/__init__.py
Including module_utils file ansible_collections/ansible/netcommon/plugins/module_utils/network/common/utils.py
Including module_utils file ansible/module_utils/common/network.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/compare.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/constants.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py
Including module_utils file ansible/module_utils/urls.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/ipaddress.py
Including module_utils file ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py
Using module file /root/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py
<localhost> PUT /root/.ansible/tmp/ansible-local-48942anu8z719/tmpaa5ivbg6 TO /root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/ /root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_apm_acl', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 990, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 983, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 774, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 788, in present
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 805, in update
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 798, in should_update
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 741, in _update_changed_options
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 666, in compare
  File "/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py", line 695, in entries
IndexError: list index out of range
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1617565043.532786-49046-108620439017132/AnsiballZ_bigip_apm_acl.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_apm_acl', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 990, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 983, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 774, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 788, in present\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 805, in update\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 798, in should_update\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 741, in _update_changed_options\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 666, in compare\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_apm_acl_payload_jmtpxxv6/ansible_f5networks.f5_modules.bigip_apm_acl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_apm_acl.py\", line 695, in entries\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by ssaammoo** [comment]
any one can please works on this ?

**Comment by ssaammoo** [comment]
Any one can help me out please ?

**Comment by DerrickTJ** [comment]
Same as this ticket from what I can tell: https://github.com/F5Networks/f5-ansible/issues/1779

**Comment by trinaths** [comment]
Thanks for raising this issue, Created JIRA INFRAANO-324 for internal PM tracking
