### ISSUE TITLE
bigip_gtm_wide_ip.py throws TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ktreese** [F5Networks/f5-ansible#2029]
##### COMPONENT NAME
bigip_gtm_wide_ip

##### ANSIBLE VERSION

```
(ansible2.10)  ➜  f5-config git:(wips_pools) ✗ ansible --version
ansible 2.10.3
  config file = /Users/reesek/workspace/ansible/f5-config/ansible.cfg
  configured module search path = ['/Users/reesek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/reesek/opt/miniconda3/envs/ansible2.10/lib/python3.9/site-packages/ansible
  executable location = /Users/reesek/opt/miniconda3/envs/ansible2.10/bin/ansible
  python version = 3.9.0 (default, Nov 15 2020, 06:25:35) [Clang 10.0.0 ]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.2.1
  Build       0.0.10
  Edition     Point Release 1
  Date        Fri Jan 15 13:43:15 PST 2021
```
##### CONFIGURATION

I am using `f5networks.f5_modules 1.9.1-devel` as I await a release for bug fix F5Networks/f5-ansible/issues/1920

##### OS / ENVIRONMENT

MacOS

##### SUMMARY
Use of `irules` attribute in `bigip_gtm_wide_ip.py` results in the error:

```
TypeError: 'NoneType' object is not iterable
```

##### STEPS TO REPRODUCE

Create a simple task to create a gtm wide ip and specify a list of one or more irules:

```
    - name: Set lb method
      bigip_gtm_wide_ip:
        name: "*.apps-dev.ree.se.net"
        pool_lb_method: round-robin
        type: a
        irules:
          - app2app_dev_reese_poolselect
        persistence_ttl: 36000
        pools:
          - name: apps-dev.ree.se.net_pool
            order: 0
            ratio: 1
        provider: "{{ vcmp_guest_provider }}"
  run_once: true
  delegate_to: localhost
```

##### EXPECTED RESULTS

irules should be populated on the specified wide ip

##### ACTUAL RESULTS

```
TASK [dns : Set lb method] **************************************************************************************************************************************************************************************************
task path: /Users/reesek/Library/Mobile Documents/com~apple~CloudDocs/workspace/ansible/f5-config/roles/dns/tasks/gslb/wideips/wideip_list.yaml:15
The full traceback is:
Traceback (most recent call last):
  File "/Users/reesek/.ansible/tmp/ansible-tmp-1620744378.7560399-28514-258630295053803/AnsiballZ_bigip_gtm_wide_ip.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/reesek/.ansible/tmp/ansible-tmp-1620744378.7560399-28514-258630295053803/AnsiballZ_bigip_gtm_wide_ip.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/reesek/.ansible/tmp/ansible-tmp-1620744378.7560399-28514-258630295053803/AnsiballZ_bigip_gtm_wide_ip.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_gtm_wide_ip', init_globals=None, run_name='__main__', alter_sys=True)
  File "/Users/reesek/opt/miniconda3/envs/ansible2.10/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Users/reesek/opt/miniconda3/envs/ansible2.10/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/reesek/opt/miniconda3/envs/ansible2.10/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 938, in <module>
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 931, in main
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 706, in exec_module
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 728, in present
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 751, in update
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 744, in should_update
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 681, in _update_changed_options
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 581, in compare
  File "/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py", line 643, in irules
TypeError: 'NoneType' object is not iterable
fatal: [snddns-int01.ree.se.net]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/reesek/.ansible/tmp/ansible-tmp-1620744378.7560399-28514-258630295053803/AnsiballZ_bigip_gtm_wide_ip.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/reesek/.ansible/tmp/ansible-tmp-1620744378.7560399-28514-258630295053803/AnsiballZ_bigip_gtm_wide_ip.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/reesek/.ansible/tmp/ansible-tmp-1620744378.7560399-28514-258630295053803/AnsiballZ_bigip_gtm_wide_ip.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_gtm_wide_ip', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Users/reesek/opt/miniconda3/envs/ansible2.10/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Users/reesek/opt/miniconda3/envs/ansible2.10/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Users/reesek/opt/miniconda3/envs/ansible2.10/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 938, in <module>\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 931, in main\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 706, in exec_module\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 728, in present\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 751, in update\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 744, in should_update\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 681, in _update_changed_options\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 581, in compare\n  File \"/var/folders/dp/z8fqtkcx20jfzhylh96t6dzh0000gn/T/ansible_bigip_gtm_wide_ip_payload_1tljy5o4/ansible_bigip_gtm_wide_ip_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_gtm_wide_ip.py\", line 643, in irules\nTypeError: 'NoneType' object is not iterable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by ktreese** [comment]
@wojtek0806 While fixed, the module does not add irules to an already existing object.  It does add the irule, however, for newly created objects.  I'll open a new issue.
