### ISSUE TITLE
F5 -Ansible - The error was: ImportError: No module named ipaddress

### ISSUE THREAD

**Issue by riadsanchz** [F5Networks/f5-ansible#2032]
##### COMPONENT NAME

``` bigip_virtual_server/Task: CREATE VIP/ Module: mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_virtual_server```

### Environment

  Operating System: Red Hat Enterprise Linux
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.9:GA:server
            Kernel: Linux 3.10.0-1160.25.1.el7.x86_64
      Architecture: x86-64

##### ANSIBLE VERSION

```
[TESTDEV@dloappf5ansib01 demo]$ ansible --version
ansible 2.10.9
  config file = /home/TEST/TESTDEV/demo/ansible.cfg
  configured module search path = ['/home/TEST/TESTDEV/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May 17 2021, 15:40:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.2.1
  Build       0.0.10
  Edition     Point Release 1
  Date        Fri Jan 15 13:43:15 PST 2021
```
##### CONFIGURATION

```
[TESTDEV@dloappf5ansib01 demo]$ cat ansible.cfg 
[defaults]

inventory      = ./hosts
host_key_checking = false
collections_paths = ~/.ansible/collections
#deprecation_warnings = false-->
```
##### OS / ENVIRONMENT
```
  Operating System: Red Hat Enterprise Linux
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.9:GA:server
            Kernel: Linux 3.10.0-1160.25.1.el7.x86_64
      Architecture: x86-64
```

##### SUMMARY
Hello All - The SysAdmin Team had patched the RHEL server on May 8th that hosts Ansible and after the patch work my ansible playbooks are no longer working when the bigip_virtual_server module is executed. SysAdmin team advised this issue is related to 3rd party software which is F5 related. I am a newbie with Ansible Automation and cannot for teh life of me fifure out why this error is occurring if the ipaddress.py module is installed and why it is causing bigip_virtual_server.py to fail. RHEL Team stated ipaddress pacakage is installed: 
```

[TESTDEV@dloappf5ansib01 demo]$ python3 -m pip list
Package          Version
---------------- ---------
ansible          3.4.0
ansible-base     2.10.9
bigsuds          1.0.6
certifi          2020.12.5
cffi             1.14.5
chardet          4.0.0
cryptography     3.4.7
deepdiff         5.5.0
f5-icontrol-rest 1.3.13
f5-sdk           3.0.21
idna             2.10
ipaddress        1.0.23
Jinja2           3.0.0
MarkupSafe       2.0.0
netaddr          0.8.0
ordered-set      4.0.2
packaging        20.9
pip              21.1.1
pycparser        2.20
pyparsing        2.4.7
PyYAML           5.4.1
requests         2.25.1
setuptools       56.0.0
six              1.16.0
suds-jurko       0.6
urllib3          1.26.4 -->

```

##### STEPS TO REPRODUCE

```
I ran a very basic playbook to display the ImportError noted below. This error occurs with every playbook which has the bigip_virtual_server module. 

```

```
  [TESTDEV@dloappf5ansib01 demo]$ ansible-playbook f5-create-vip4.yaml -v
Using /home/TEST/TESTDEV/demo/ansible.cfg as config file

PLAY [Create a VIP, pool and pool members] ***********************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************
ok: [10.19.3.225]

TASK [Create pool] ***********************************************************************************************************************************************************************************
changed: [10.19.3.225] => {"changed": true, "lb_method": "least-connections-member", "monitor_type": "and_list", "monitors": ["/Common/http"], "name": "maria_pool", "partition": "Common", "priority_group_activation": 0, "slow_ramp_time": 120}

TASK [ADD POOL MEMBERS] ******************************************************************************************************************************************************************************
changed: [10.19.3.225] => (item={'host': '2.1.1.10', 'name': 'web01'}) => {"address": "2.1.1.10", "ansible_loop_var": "item", "changed": true, "fqdn_auto_populate": false, "item": {"host": "2.1.1.10", "name": "web01"}, "monitors": [], "session": "user-enabled", "state": "present"}
changed: [10.19.3.225] => (item={'host': '2.1.1.20', 'name': 'web02'}) => {"address": "2.1.1.20", "ansible_loop_var": "item", "changed": true, "fqdn_auto_populate": false, "item": {"host": "2.1.1.20", "name": "web02"}, "monitors": [], "session": "user-enabled", "state": "present"}

TASK [CREATE VIP] ************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named ipaddress
fatal: [10.19.3.225]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.19.3.225 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1621525469.0904236-100815-162137460210409/AnsiballZ_bigip_virtual_server.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1621525469.0904236-100815-162137460210409/AnsiballZ_bigip_virtual_server.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1621525469.0904236-100815-162137460210409/AnsiballZ_bigip_virtual_server.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_virtual_server', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_bigip_virtual_server_payload_jsWhG4/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py\", line 912, in <module>\r\n  File \"/tmp/ansible_bigip_virtual_server_payload_jsWhG4/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/ipaddress.py\", line 13, in <module>\r\nImportError: No module named ipaddress\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *******************************************************************************************************************************************************************************************
10.19.3.225                : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

##### EXPECTED RESULTS

``` 
 CREATE VIP
``` 
##### ACTUAL RESULTS
``` 
With high verbosity -vvvv

TASK [CREATE VIP] ************************************************************************************************************************************************************************************
task path: /home/TEST/TESTDEV/demo/f5-create-vip4.yaml:45
Loading collection ansible.netcommon from /home/TEST/TESTDEV/.ansible/collections/ansible_collections/ansible/netcommon
<10.19.3.225> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<10.19.3.225> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<10.19.3.225> ESTABLISH SSH CONNECTION FOR USER: admin
<10.19.3.225> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/TEST/TESTDEV/.ansible/cp/673137df6b 10.19.3.225 '/bin/sh -c '"'"'echo ~admin && sleep 0'"'"''
<10.19.3.225> (0, b'/home/admin\n', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.19.3.225> ESTABLISH SSH CONNECTION FOR USER: admin
<10.19.3.225> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/TEST/TESTDEV/.ansible/cp/673137df6b 10.19.3.225 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/admin/.ansible/tmp `"&& mkdir "` echo /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624 `" && echo ansible-tmp-1621527764.4868367-105424-246205877666624="` echo /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624 `" ) && sleep 0'"'"''
<10.19.3.225> (0, b'ansible-tmp-1621527764.4868367-105424-246205877666624=/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624\n', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
Using module file /home/TEST/TESTDEV/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py
<10.19.3.225> PUT /home/TEST/TESTDEV/.ansible/tmp/ansible-local-1052405s1xbwh_/tmpo7vvhqc3 TO /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py
<10.19.3.225> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/TEST/TESTDEV/.ansible/cp/673137df6b '[10.19.3.225]'
<10.19.3.225> (0, b'sftp> put /home/TEST/TESTDEV/.ansible/tmp/ansible-local-1052405s1xbwh_/tmpo7vvhqc3 /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py\n', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 3 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/admin size 0\r\ndebug3: Looking up /home/TEST/TESTDEV/.ansible/tmp/ansible-local-1052405s1xbwh_/tmpo7vvhqc3\r\ndebug3: Sent message fd 3 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:7 O:98304 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:8 O:131072 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:9 O:163840 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:10 O:196608 S:25214\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 32768 bytes at 65536\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 7 32768 bytes at 98304\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 8 32768 bytes at 131072\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 9 32768 bytes at 163840\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 10 25214 bytes at 196608\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.19.3.225> ESTABLISH SSH CONNECTION FOR USER: admin
<10.19.3.225> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/TEST/TESTDEV/.ansible/cp/673137df6b 10.19.3.225 '/bin/sh -c '"'"'chmod u+x /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/ /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py && sleep 0'"'"''
<10.19.3.225> (0, b'', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<10.19.3.225> ESTABLISH SSH CONNECTION FOR USER: admin
<10.19.3.225> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/TEST/TESTDEV/.ansible/cp/673137df6b -tt 10.19.3.225 '/bin/sh -c '"'"'/usr/bin/python /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py && sleep 0'"'"''
<10.19.3.225> (1, b'Traceback (most recent call last):\r\n  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 102, in <module>\r\n    _ansiballz_main()\r\n  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 40, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.f5networks.f5_modules.plugins.modules.bigip_virtual_server\', init_globals=None, run_name=\'__main__\', alter_sys=True)\r\n  File "/usr/lib/python2.7/runpy.py", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code\r\n    exec code in run_globals\r\n  File "/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py", line 912, in <module>\r\n  File "/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/ipaddress.py", line 13, in <module>\r\nImportError: No module named ipaddress\r\n', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 10.19.3.225 closed.\r\n')
<10.19.3.225> Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 60: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 4 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 105296
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
Shared connection to 10.19.3.225 closed.
<10.19.3.225> ESTABLISH SSH CONNECTION FOR USER: admin
<10.19.3.225> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/TEST/TESTDEV/.ansible/cp/673137df6b 10.19.3.225 '/bin/sh -c '"'"'rm -f -r /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/ > /dev/null 2>&1 && sleep 0'"'"''
<10.19.3.225> (0, b'', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 102, in <module>
    _ansiballz_main()
  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_virtual_server', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py", line 912, in <module>
  File "/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/ipaddress.py", line 13, in <module>
ImportError: No module named ipaddress
fatal: [10.19.3.225]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 10.19.3.225 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_virtual_server', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py\", line 912, in <module>\r\n  File \"/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/ipaddress.py\", line 13, in <module>\r\nImportError: No module named ipaddress\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *******************************************************************************************************************************************************************************************
10.19.3.225                : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by wojtek0806** [comment]
to help you move to 3.5+ python i added all the requriements for packages into requirements.bare.txt file in the repo, create a blank venv and use that file with pip to install and retest

**Comment by riadsanchz** [comment]
Hello wojtek0806 - 
The version I am using is 3.9.5 and I am still seeing the import error.
python version = 3.9.5 (default, May 17 2021, 15:40:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

**Comment by wojtek0806** [comment]
looking closer at your error logs:

````<10.19.3.225> ESTABLISH SSH CONNECTION FOR USER: admin
<10.19.3.225> SSH: EXEC sshpass -d10 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/home/TEST/TESTDEV/.ansible/cp/673137df6b -tt 10.19.3.225 '/bin/sh -c '"'"'/usr/bin/python /home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py && sleep 0'"'"''
<10.19.3.225> (1, b'Traceback (most recent call last):\r\n  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 102, in <module>\r\n    _ansiballz_main()\r\n  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/admin/.ansible/tmp/ansible-tmp-1621527764.4868367-105424-246205877666624/AnsiballZ_bigip_virtual_server.py", line 40, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.f5networks.f5_modules.plugins.modules.bigip_virtual_server\', init_globals=None, run_name=\'__main__\', alter_sys=True)\r\n  File "/usr/lib/python2.7/runpy.py", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code\r\n    exec code in run_globals\r\n  File "/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py", line 912, in <module>\r\n  File "/tmp/ansible_bigip_virtual_server_payload_eA3wOZ/ansible_bigip_virtual_server_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/ipaddress.py", line 13, in <module>\r\nImportError: No module named ipaddress\r\n', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 60: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 105296\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 10.19.3.225 closed.\r\n')
<10.19.3.225> Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

````
From the logs it looks like you are trying to execute this module on BIG-IP directly hence the import error. I missed the SSH attempt when I glanced at first and just saw py2.7 output:

```` File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
````

Since you confirmed you are running 3.9.5 , I suspect you are executing the module on BIGIP not on controller using REST. This is why when opening issues you must provide the full playbook, no matter how trivial. F5 modules do not run on SSH with exception of bigip_wait, bigip_command, bigip_device_certificate modules. I believe you need to have `connection: local` specified in your playbook. (guessing as you did not provide it)

**Comment by riadsanchz** [comment]
Hi wojtek0806 - your post helped me to solve the issue. I had to review https://galaxy.ansible.com/f5networks/f5_modules

Within the tasks I had to add f5networks.f5_modules and delegate_to: localhost and the ipaddress.py issue was resolved. Thank you!
