### ISSUE TITLE
bigip_pool_member results in KeyError: 'selfLink'

### ISSUE THREAD

**Issue by jedioncrk** [F5Networks/f5-ansible#2060]
##### COMPONENT NAME

bigip_pool_member

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = None
  configured module search path = ['/home/deploy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.4
  Build       0.0.11
  Edition     Final
  Date        Thu Feb 11 19:05:03 PST 2021
```
##### OS / ENVIRONMENT

CentOS Linux release 7.7.1908 (Core)

##### SUMMARY

Running the bigip_pool_member module results in a KeyError: 'selfLink' error.

##### STEPS TO REPRODUCE

```
    - name: toggle pool members
      bigip_pool_member:
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ f5.deploy.username }}"
          password: "{{ f5.deploy.password }}"
          validate_certs: no
        state: "{{ state }}"
        name: "{{ item.0.name }}"
        address: "{{ item.0.host }}"
        port: "{{ item.0.port | default(8800) }}"
        pool: "{{ item.0.pool }}"
      loop: "{{ nodepools[group] | subelements('env') }}"
      when: item.1 == group_names[0]
      delegate_to: localhost
```

##### EXPECTED RESULTS

The pool member should have changed state.

##### ACTUAL RESULTS

```
TASK [toggle pool members] ***************************************************************
task path: /opt/bdc/gansible/f5/toggle-pool.yml:25
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: deploy
<localhost> EXEC /bin/sh -c 'echo ~deploy && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/deploy/.ansible/tmp `"&& mkdir "` echo /home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478 `" && echo ansible-tmp-1624552963.8670416-245402-141155813776478="` echo /home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.bigip_pool_member to f5networks.f5_modules.bigip_pool_member
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
Using module file /usr/local/lib/python3.6/site-packages/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py
<localhost> PUT /home/deploy/.ansible/tmp/ansible-local-245387fw1kj6sp/tmpv6jls6u_ TO /home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/ /home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py", line 102, in <module>
    _ansiballz_main()
  File "/home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool_member', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py", line 1671, in <module>
  File "/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py", line 1664, in main
  File "/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py", line 1038, in exec_module
  File "/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 564, in tmos_version
KeyError: 'selfLink'
fatal: [loadbalancer]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/deploy/.ansible/tmp/ansible-tmp-1624552963.8670416-245402-141155813776478/AnsiballZ_bigip_pool_member.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool_member', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py\", line 1671, in <module>\n  File \"/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py\", line 1664, in main\n  File \"/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool_member.py\", line 1038, in exec_module\n  File \"/tmp/ansible_bigip_pool_member_payload_r4h7_6wp/ansible_bigip_pool_member_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 564, in tmos_version\nKeyError: 'selfLink'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by jedioncrk** [comment]
Ok, after using a full admin user, instead of a resource admin, the command completed successfully.
