### ISSUE TITLE
bigip_pool - aggregate with replace_all_with:yes doesn't work

### ISSUE THREAD

**Issue by tsuyo-o** [F5Networks/f5-ansible#2097]
##### COMPONENT NAME

bigip_pool

##### ANSIBLE VERSION

```
ansible 2.10.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 12 2021, 20:44:22) [GCC 10.3.1 20210424]

/home/xxx # ansible-galaxy collection list | grep f5
f5networks.f5_modules     1.7.1  
f5networks.f5_modules 1.11.0 
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.5
  Build       0.18.8
  Edition     Engineering Hotfix
  Date        Wed Sep  2 05:16:30 PDT 2020
```
##### SUMMARY

bigip_pool with aggregate and replace_all_with:yes fails.
but without replace_all_with, it works.

##### STEPS TO REPRODUCE

```
- name: Create pools with aggregate option
  hosts: all
  connection: local

  vars:
    provider:
      user: admin
      password: xxxxxxxxx
      server: '[ipv6_addr]'
      validate_certs: no
      server_port: 443

  tasks:
     - name: Add pools Aggregate
       bigip_pool:
         aggregate:
           - name: my-pool
             partition: Common
             lb_method: least-connections-member
             slow_ramp_time: 120
           - name: my-pool2
             partition: Common
             lb_method: least-sessions
             slow_ramp_time: 120
         provider: "{{ provider }}"
         replace_all_with: yes
       delegate_to: localhost
```

##### EXPECTED RESULTS

ansible-playbook completes without error

##### ACTUAL RESULTS

ansible-playbook aborts with error

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1629960050.1308024-4807-162097914351212/AnsiballZ_bigip_pool.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1629960050.1308024-4807-162097914351212/AnsiballZ_bigip_pool.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1629960050.1308024-4807-162097914351212/AnsiballZ_bigip_pool.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1261, in <module>
  File "/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1254, in main
  File "/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 810, in exec_module
  File "/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 950, in purge
  File "/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1131, in purge_from_device
  File "/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 297, in __exit__
Exception   
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1629960050.1308024-4807-162097914351212/AnsiballZ_bigip_pool.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1629960050.1308024-4807-162097914351212/AnsiballZ_bigip_pool.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1629960050.1308024-4807-162097914351212/AnsiballZ_bigip_pool.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool', init_globals=None, run_
name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 1261, in <module>\n  File \"/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 1254, in main\n  File \"/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 810, in exec_module\n  File \"/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 950, in purge\n  File \"/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 1131, in purge_from_device\n  File \"/tmp/ansible_bigip_pool_payload_xm0l26q0/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 297, in __exit__\nException\n",                                                                             
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1 
}           
```

**Comment by trinaths** [comment]
@tsuyo-o - We have a testcase for validating this. https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_pool/tasks/issue-01158.yaml#L19. There are no issues with the module. Please reverify at your end.

**Comment by tsuyo-o** [comment]
@trinaths Thank you for your replay. Yes, I noticed there were some pools on the bigip and could not be removed due to dependancies. After removing them manually,  it works as expected.
Though the ansible logs didn't help me this time,   /var/log/restjavad-audit.0.log helped me to identify the cause of error.
