### ISSUE TITLE
urllib.error.URLError: <urlopen error timed out> 

### ISSUE THREAD

**Issue by tristaneniyan** [F5Networks/f5-ansible#2115]
ISSUE TYPE
 
- Bug Report
##### COMPONENT NAME
bigip_pool,
bigip_pool_member,
bigip_virtual_server:

##### ANSIBLE VERSION

ansible [core 2.11.6]
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

##### BIGIP VERSION

BIG-IP 15.1.0.2 Build 0.0.9 Point Release 2

##### CONFIGURATION

[defaults]
inventory = ./hosts
host_key_checking =  false
gathering_facts = false
timeout = 5
collections_paths = ./collections

##### OS / ENVIRONMENT

ubuntu 20.04LTS

##### SUMMARY
 I have a test linux(ansible ctrl node) make ansible scripts to automate virtual F5, I have both control node and virtual f5 in intranet their IPs respectively 10.21.74.163 & 10.21.12.250. When i try to run basic playbook from F5 site "https://clouddocs.f5.com/products/orchestration/ansible/devel/usage/playbook_tutorial.html" I'm getting urllib.error.URLError: <urlopen error timed out> . my inventory files has just localhost in it. and i have added my config file on top. i also searched some of previous bugs and added no_teem_f5 : yes to the provider yet no diff from the error which I'm getting.

##### STEPS TO REPRODUCE
```

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local

  vars:
    provider:
      password: our vm pwd
      server: 10.21.12.250
      user: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      with_items:
        - host: 10.10.10.56
          name: web01
        - host: 10.10.10.70
          name: web02
      delegate_to: localhost

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip
        destination: 172.16.10.108
        name: vip-1
        pool: web
        port: 80
        snat: Automap
        profiles:
          - http
          - clientssl
      delegate_to: localhost

```

##### EXPECTED RESULTS
```
PLAY [Create a VIP, pool and pool members] ***********************************************

TASK [Gathering Facts] *******************************************************************
ok: [localhost]

TASK [Create a pool] *********************************************************************
changed: [localhost -> localhost]

TASK [Add members to pool] ***************************************************************
changed: [localhost -> localhost] => (item={u'host': u'10.10.10.10', u'name': u'web01'})
changed: [localhost -> localhost] => (item={u'host': u'10.10.10.20', u'name': u'web02'})

TASK [Create a VIP] **********************************************************************
changed: [localhost -> localhost]

PLAY RECAP *******************************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0    skipped=0 
```

##### ACTUAL RESULTS

```
PLAY [Create a VIP, pool and pool members] *******************************************************************************

TASK [Gathering Facts] ***************************************************************************************************
[DEPRECATION WARNING]: Distribution ubuntu 20.04 on host localhost should use /usr/bin/python3, but is using
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using
the discovered platform python for this host. See https://docs.ansible.com/ansible-
core/2.11/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version
2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]

TASK [Create a pool] *****************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: urllib.error.URLError: <u                                                                                                                   rlopen error timed out>
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  Fil                                                                                                                   e \"/usr/lib/python3.8/urllib/request.py\", line 1354, in do_open\n    h.request(req.get_method(), req.selector, req.data,                                                                                                                    headers,\n  File \"/usr/lib/python3.8/http/client.py\", line 1252, in request\n    self._send_request(method, url, body,                                                                                                                    headers, encode_chunked)\n  File \"/usr/lib/python3.8/http/client.py\", line 1298, in _send_request\n    self.endheaders(b                                                                                                                   ody, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.8/http/client.py\", line 1247, in endheaders\n    self._sen                                                                                                                   d_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.8/http/client.py\", line 1007, in _send_o                                                                                                                   utput\n    self.send(msg)\n  File \"/usr/lib/python3.8/http/client.py\", line 947, in send\n    self.connect()\n  File \"/                                                                                                                   usr/lib/python3.8/http/client.py\", line 1414, in connect\n    super().connect()\n  File \"/usr/lib/python3.8/http/client.                                                                                                                   py\", line 918, in connect\n    self.sock = self._create_connection(\n  File \"/usr/lib/python3.8/socket.py\", line 808, i                                                                                                                   n create_connection\n    raise err\n  File \"/usr/lib/python3.8/socket.py\", line 796, in create_connection\n    sock.conn                                                                                                                   ect(sa)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (mo                                                                                                                   st recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1634631250.0058408-60381-235340808072299/AnsiballZ_bigip_po                                                                                                                   ol.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1634631250.0058408-60381-23                                                                                                                   5340808072299/AnsiballZ_bigip_pool.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_P                                                                                                                   ARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1634631250.0058408-60381-235340808072299/AnsiballZ_bigip_pool.py\", line 4                                                                                                                   0, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool',                                                                                                                    init_globals=dict(_module_fqn='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool', _modlib_path=modlib                                                                                                                   _path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals,                                                                                                                    run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals                                                                                                                   , init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp                                                                                                                   /ansible_bigip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modu                                                                                                                   les/bigip_pool.py\", line 1261, in <module>\n  File \"/tmp/ansible_bigip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.                                                                                                                   zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 1254, in main\n  File \"/tmp/ansible_b                                                                                                                   igip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_                                                                                                                   pool.py\", line 798, in exec_module\n  File \"/tmp/ansible_bigip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansi                                                                                                                   ble_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 551, in tmos_version\n  File \"/tmp/ansible                                                                                                                   _bigip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils                                                                                                                   /bigip.py\", line 31, in api\n  File \"/tmp/ansible_bigip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansible_col                                                                                                                   lections/f5networks/f5_modules/plugins/module_utils/bigip.py\", line 52, in connect_via_token_auth\n  File \"/tmp/ansible_                                                                                                                   bigip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/                                                                                                                   icontrol.py\", line 239, in post\n  File \"/tmp/ansible_bigip_pool_payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansible                                                                                                                   _collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 194, in send\n  File \"/tmp/ansible_bigip_pool                                                                                                                   _payload_ood7_hxy/ansible_bigip_pool_payload.zip/ansible/module_utils/urls.py\", line 1446, in open\n  File \"/usr/lib/pyt                                                                                                                   hon3.8/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.8/                                                                                                                   urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.8/urllib/request.p                                                                                                                   y\", line 542, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/usr/lib/python3.8                                                                                                                   /urllib/request.py\", line 502, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_pool_payload_ood7_hx                                                                                                                   y/ansible_bigip_pool_payload.zip/ansible/module_utils/urls.py\", line 582, in https_open\n  File \"/usr/lib/python3.8/urll                                                                                                                   ib/request.py\", line 1357, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error timed out>\n", "mod                                                                                                                   ule_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ***************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


```

**after using -vvv i get the following error**

```
TASK [Create a pool] ************************************************************************************************************************************************************************************************************************
task path: /ansible/playbook.yaml:16
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116 `" && echo ansible-tmp-1634632478.9153419-61922-38643095072116="` echo /root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.bigip_pool to f5networks.f5_modules.bigip_pool
Using module file /ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py
<localhost> PUT /root/.ansible/tmp/ansible-local-61832jy6dh6nd/tmpffb91jvd TO /root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/ /root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1414, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 918, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py", line 100, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool', init_globals=dict(_module_fqn='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1261, in <module>
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1254, in main
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 798, in exec_module
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 551, in tmos_version
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip.py", line 31, in api
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip.py", line 52, in connect_via_token_auth
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 239, in post
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 194, in send
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible/module_utils/urls.py", line 1446, in open
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible/module_utils/urls.py", line 582, in https_open
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3.8/urllib/request.py\", line 1354, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers,\n  File \"/usr/lib/python3.8/http/client.py\", line 1252, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib/python3.8/http/client.py\", line 1298, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.8/http/client.py\", line 1247, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.8/http/client.py\", line 1007, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.8/http/client.py\", line 947, in send\n    self.connect()\n  File \"/usr/lib/python3.8/http/client.py\", line 1414, in connect\n    super().connect()\n  File \"/usr/lib/python3.8/http/client.py\", line 918, in connect\n    self.sock = self._create_connection(\n  File \"/usr/lib/python3.8/socket.py\", line 808, in create_connection\n    raise err\n  File \"/usr/lib/python3.8/socket.py\", line 796, in create_connection\n    sock.connect(sa)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1634632478.9153419-61922-38643095072116/AnsiballZ_bigip_pool.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool', init_globals=dict(_module_fqn='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_pool', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 1261, in <module>\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 1254, in main\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py\", line 798, in exec_module\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 551, in tmos_version\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip.py\", line 31, in api\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/bigip.py\", line 52, in connect_via_token_auth\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 239, in post\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 194, in send\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible/module_utils/urls.py\", line 1446, in open\n  File \"/usr/lib/python3.8/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.8/urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.8/urllib/request.py\", line 542, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/usr/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_pool_payload_90ojif13/ansible_bigip_pool_payload.zip/ansible/module_utils/urls.py\", line 582, in https_open\n  File \"/usr/lib/python3.8/urllib/request.py\", line 1357, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error timed out>\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by trinaths** [comment]
@tristaneniyan - This is related to connection issues in your setup environment. Nothing with Ansible.

**Comment by asrivastav-aag** [comment]
These are the basic checks you can do...
- Reachability between Ansible server to F5 - Switching (L2) or routing (L3).
- Firewall needs to allow the connection from Ansible Server to F5 Mgmt IP on destination port 443 or 22.
- F5 should allow the connection from Ansible Server.
- F5 mgmt should be enabled.
