### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration (system-info in bigip_device_info)

### ISSUE THREAD

**Issue by narcotico-g** [F5Networks/f5-ansible#2117]
##### COMPONENT NAME
```
<!--- Name of the module/role/task -->
- name: Get all config from F5
      bigip_device_info:
        gather_subset: 
          - system-info
          provider:
          server: "{{ ansible_host }}"
          user: "{{ user }}"
          password: "{{ password }}"
          validate_certs: no
```
### Environment
```
Env vars not used
```
##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /home/narciso/scripts/ansible/f5collect-v2/ansible.cfg
  configured module search path = ['/home/narciso/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.4.3
  Build       0.0.8
  Edition     Point Release 3
  Date        Tue May 18 06:18:01 PDT 2021

```
##### CONFIGURATION

Not used

##### OS / ENVIRONMENT

Ubuntu 20.04.3 LTS
##### SUMMARY

When I try get device-info (gather_subset) in bigip_device_info I always get next error (if I try get vlans or profiles, all it is working fine, but no with device-info).

##### STEPS TO REPRODUCE

```
---
- hosts: <IP/hostname>
  connection: local
  gather_facts: no
  tasks:
    - name: Get info from F5
      bigip_device_info:
        gather_subset: 
          - system-info
        provider:
          server: "{{ ansible_host }}"
          user: <user>
          password: <pass>
          validate_certs: no
      register: output
      
    - name: Print all info
      debug:
        var: output
```

##### EXPECTED RESULTS

System info from device
##### ACTUAL RESULTS

```
PLAYBOOK: test.yml ******************************************************************************************************************************************************
1 plays in test.yml

PLAY [IP] ****************************************************************************************************************************
META: ran handlers

TASK [Get info from F5] *************************************************************************************************************************************************
task path: /home/narciso/scripts/ansible/f5collect-v2/test.yml:6
<IP> ESTABLISH LOCAL CONNECTION FOR USER: narciso
<IP> EXEC /bin/sh -c 'echo ~narciso && sleep 0'
<IP> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513 `" && echo ansible-tmp-1634819913.8666525-97418308558513="` echo /home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513 `" ) && sleep 0'
<IP> Attempting python interpreter discovery
<IP> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<IP> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/network/f5/bigip_device_info.py
<IP> PUT /home/narciso/.ansible/tmp/ansible-local-41208qc5gq93t/tmpjp7dnsxa TO /home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py
<IP> EXEC /bin/sh -c 'chmod u+x /home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/ /home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py && sleep 0'
<IP> EXEC /bin/sh -c '/usr/bin/python3 /home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py && sleep 0'
<IP> EXEC /bin/sh -c 'rm -f -r /home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py", line 102, in <module>
    _ansiballz_main()
  File "/home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16266, in <module>
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16259, in main
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15999, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16078, in execute_managers
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13445, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13451, in _exec_module
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 7092, in to_return
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13391, in hardware_information
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13400, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13400, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13405, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13397, in _transform_name_attribute
RuntimeError: dictionary keys changed during iteration
fatal: [IP]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py", line 102, in <module>
        _ansiballz_main()
      File "/home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/narciso/.ansible/tmp/ansible-tmp-1634819913.8666525-97418308558513/AnsiballZ_bigip_device_info.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16266, in <module>
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16259, in main
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15999, in exec_module
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16078, in execute_managers
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13445, in exec_module
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13451, in _exec_module
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 7092, in to_return
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13391, in hardware_information
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13400, in _transform_name_attribute
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13400, in _transform_name_attribute
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13405, in _transform_name_attribute
      File "/tmp/ansible_bigip_device_info_payload_ryvsumry/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13397, in _transform_name_attribute
    RuntimeError: dictionary keys changed during iteration
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP **************************************************************************************************************************************************************
IP : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by trinaths** [comment]
@narcotico-g - With the latest available devel build we see no issues with the module. Suggest to retry with collection upgrade.
