### ISSUE TITLE
bigip_data_group failes when looping a list

### ISSUE THREAD

**Issue by shariaty59** [F5Networks/f5-ansible#2127]
##### COMPONENT NAME

bigip_data_group.py

##### ANSIBLE VERSION

```
ansible 2.10.0
  config file = /home/ashariaty/my_ansible/API_TEST/ansible.cfg
  configured module search path = ['/home/ashariaty/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.0.1.2
  Build       0.0.8
  Edition     Point Release 2
  Date        Wed Jul  7 12:24:53 PDT 2021
```
##### OS / ENVIRONMENT

[defaults]
inventory = inventory
deprecation_warnings = False
host_key_checking = False
timeout = 5

##### SUMMARY

I am trying to add key nd values to the data group. it works when provided manually under records but it doesnt when trying to loop a list.

I am passing a variable YML file that contains the list below:

whitelist:
   - key: 10.10.10.10
     value: IP_1
   - key: 10.10.10.11
     value: IP_2
   - key: 10.10.10.12
     value: IP_3

##### STEPS TO REPRODUCE

```
   - name: CREATING THE WHITE-LIST
     f5networks.f5_modules.bigip_data_group:
       provider: "{{ provider }}"
       name: "test_whitelist"
       internal: yes
       records:
         - key: "{{ item.key }}"
         - value: "{{ item.value }}"
       type: address
     loop: "{{whitelist}}"
     delegate_to: localhost
```

##### EXPECTED RESULTS

fot the whitelist to be created.

##### ACTUAL RESULTS

```
TASK [CREATING THE WHITE-LIST] **********************************************************************************************************************************************************************************************************
task path: /home/ashariaty/my_ansible/API_TEST/wafDeployRM.yml:54
Loading collection ansible.netcommon from /home/ashariaty/.ansible/collections/ansible_collections/ansible/netcommon
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ashariaty
<localhost> EXEC /bin/sh -c 'echo ~ashariaty && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ashariaty/.ansible/tmp `"&& mkdir "` echo /home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317 `" && echo ansible-tmp-1635970547.2347271-70246-187841881119317="` echo /home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317 `" ) && sleep 0'
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.network.common.config to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.config
redirecting module_util ansible.module_utils.network.common.config to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.config
redirecting module_util ansible.module_utils.network.common.config to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.config
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.compat.ipaddress to ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
Using module file /home/ashariaty/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py
<localhost> PUT /home/ashariaty/.ansible/tmp/ansible-local-69854a5ysj98j/tmp3te6_u18 TO /home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/ /home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_data_group', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 1461, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 1454, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 1397, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 920, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 967, in present
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 999, in update
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 909, in should_update
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 952, in _update_changed_options
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 851, in compare
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 879, in records
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 808, in records
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 718, in records_src
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 726, in _write_records_to_file
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 385, in encode
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 391, in encode_dict
  File "/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py", line 429, in encode_address_from_dict
KeyError: 'key'
failed: [ftbc-f5-dev1] (item={'key': '10.10.10.10', 'value': 'IP_1'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "key": "10.10.10.10",
        "value": "IP_1"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ashariaty/.ansible/tmp/ansible-tmp-1635970547.2347271-70246-187841881119317/AnsiballZ_bigip_data_group.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_data_group', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 1461, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 1454, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 1397, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 920, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 967, in present\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 999, in update\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 909, in should_update\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 952, in _update_changed_options\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 851, in compare\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 879, in records\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 808, in records\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 718, in records_src\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 726, in _write_records_to_file\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 385, in encode\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 391, in encode_dict\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_data_group_payload_rpc4hw88/ansible_f5networks.f5_modules.bigip_data_group_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py\", line 429, in encode_address_from_dict\nKeyError: 'key'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by wojtek0806** [comment]
The parameter is a list of dictionaries what you have there is a dictionary:
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py#L84
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py#L164
