### ISSUE TITLE
when running syslog and snmp module on version "f5networks.f5_modules 1.13.0" they fails

### ISSUE THREAD

**Issue by rabindra-chauhan** [F5Networks/f5-ansible#2153]
##### COMPONENT NAME
 syslog and snmp 

##### ANSIBLE VERSION

```

```
##### BIGIP VERSION

```

```
##### SUMMARY

when  i am running syslog and snmp module on version "f5networks.f5_modules 1.13.0" they fails by giving below error 
"msg": "Destination directory ../tmp/syslog does not exist"" when i downgrade it to  "f5networks.f5_modules:==1.11.0 " it starts working

below is error 
from master 0\r\n')
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1641483336.7719424-23880-144431859641026/AnsiballZ_bigip_snmp_community.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1641483336.7719424-23880-144431859641026/AnsiballZ_bigip_snmp_community.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1641483336.7719424-23880-144431859641026/AnsiballZ_bigip_snmp_community.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_snmp_community', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_snmp_community.py", line 923, in <module>
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_snmp_community.py", line 916, in main
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_snmp_community.py", line 510, in exec_module
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_snmp_community.py", line 583, in exec_module
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 134, in send_teem
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 70, in send
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 45, in prepare_request
  File "/tmp/ansible_bigip_snmp_community_payload_ei4duq/ansible_bigip_snmp_community_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 92, in build_telemetry
TypeError: split() takes no keyword arguments
fatal: [eu-ru-1-lb214a]: FAILED! => {
    "changed": false,

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by rgonzal1** [comment]
This bug appears to be impacting the bigip_software_image module as well.

From a look at the lines referenced in the traceback, this looks to be related to the split commands that may have been introduced with #2140
`.split('/', maxsplit=1)[0]`

It looks like python 2.x does not support keywords on the split() command, where python 3.x does allow them.

Also, it appears that python 2.x support is being depricated for this module collection, which version of the modules is the last to support python 2.x?

#### Ansible Environment
ansible-playbook 2.9.7
python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

#### Traceback
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1642181402.9-110-204109997822011/AnsiballZ_bigip_software_image.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1642181402.9-110-204109997822011/AnsiballZ_bigip_software_image.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1642181402.9-110-204109997822011/AnsiballZ_bigip_software_image.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_software_image', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_software_image_payload_AVF5Mv/ansible_bigip_software_image_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_image.py", line 489, in <module>
  File "/tmp/ansible_bigip_software_image_payload_AVF5Mv/ansible_bigip_software_image_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_image.py", line 482, in main
  File "/tmp/ansible_bigip_software_image_payload_AVF5Mv/ansible_bigip_software_image_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_software_image.py", line 262, in exec_module
  File "/tmp/ansible_bigip_software_image_payload_AVF5Mv/ansible_bigip_software_image_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 134, in send_teem
  File "/tmp/ansible_bigip_software_image_payload_AVF5Mv/ansible_bigip_software_image_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 70, in send
  File "/tmp/ansible_bigip_software_image_payload_AVF5Mv/ansible_bigip_software_image_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 45, in prepare_request
  File "/tmp/ansible_bigip_software_image_payload_AVF5Mv/ansible_bigip_software_image_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 92, in build_telemetry
TypeError: split() takes no keyword arguments

**Comment by wojtek0806** [comment]
Python 2.x is deprecated you need to move to 3.x if you want to continue using this collection

**Comment by rabindra-chauhan** [comment]
> Python 2.x is deprecated you need to move to 3.x if you want to continue using this collection
i am using python 3.8.10 and  f5_modules 1.11.0 . Is there something to do with F5 module compatibility 
python --version
Python 3.8.10

**Comment by rgonzal1** [comment]
@rabindra-chauhan 

We had to specify the correct python path within the ansible.cfg file. The following code was needed, you'll need to update the path to match your environment.
```
[defaults]
interpreter_python= /path/to/environment/bin/python
```

It looks like you're encountering a similar issue where ansible is attempting to use version 2.7. The following is listed in your error:
`/usr/lib/python2.7/runpy.py`
