### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

### ISSUE THREAD

**Issue by olguarabaci** [F5Networks/f5-ansible#2159]
Hi Everyone,

I try to use bigip_ssl_pkcs12 module which is about F5 in Ansible. I shared my outputs below. I got the error on subject. I couldn't find any solution neither in community nor in others. Because, As I know this module is new and under development.--

##### COMPONENT NAME
f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12 

##### ANSIBLE VERSION
ansible 2.9.1
  config file = /home/<username>/ansible.cfg
  configured module search path = [u'/home/<username>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] 
```

```
##### BIGIP VERSION
13.1.3.4
```

```
##### OS / ENVIRONMENT
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"

##### SUMMARY
I couldn't use the module properly. You can see the error. By the way, I also did not understand source filed in the task configuration. Where does this field point to? Is this a path which will be looked up in my linux system or f5 device?

##### STEPS TO REPRODUCE
---
- name: Certificate import test
  hosts: all
  connection: httpapi
  collections:
    - f5networks.f5_bigip
  gather_facts: false

  vars:
    ansible_host: "host_ip"
    ansible_user: "user"
    ansible_httpapi_password: "pass"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes

  tasks:
    - name: Install PKCS12 cert and key
      bigip_ssl_pkcs12:
        source: /root/cert_name.pfx
        state: present

```

```

##### ACTUAL RESULTS
ansible-playbook playbooks/import_pkcs12_cert.yaml -vvv

The full traceback is:
Traceback (most recent call last):
  File "/home/sa35623/.ansible/tmp/ansible-local-96926XQBzOQ/ansible-tmp-1642523503.79-129515818256199/AnsiballZ_bigip_ssl_pkcs12.py", line 102, in <module>
    _ansiballz_main()
  File "/home/sa35623/.ansible/tmp/ansible-local-96926XQBzOQ/ansible-tmp-1642523503.79-129515818256199/AnsiballZ_bigip_ssl_pkcs12.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/sa35623/.ansible/tmp/ansible-local-96926XQBzOQ/ansible-tmp-1642523503.79-129515818256199/AnsiballZ_bigip_ssl_pkcs12.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_bigip.plugins.modules.bigip_ssl_pkcs12', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 389, in <module>
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 382, in main
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 230, in exec_module
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 243, in present
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 272, in exists
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/module_utils/client.py", line 24, in wrap
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/module_utils/client.py", line 48, in get
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_I4MAww/ansible_bigip_ssl_pkcs12_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Could not connect to https://<IP_adress>:443/mgmt/tm/sys/file/ssl-cert/~Common~cert.name: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
```

```

**Comment by trinaths** [comment]
@olguarabaci  - Please share complete info to further understand the issue.

**Comment by olguarabaci** [comment]
> @olguarabaci - Please share complete info to further understand the issue.

Hi Trinaths,

I update my issue's content.

**Comment by trinaths** [comment]
@olguarabaci - looks like its your infra connection issue not from ansible. please reverify the connectivity.

> SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

**Comment by olguarabaci** [comment]
> @olguarabaci - looks like its your infra connection issue not from ansible. please reverify the connectivity.
> 
> > SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

Could you please share more detail about this issue. I am using other f5 modules for configuration my devices. And I don't get any error from that modules. Ansible also use port 443 on that modules like now while connecting to the devices. So, How can i handle this error? Is there any setting like httpapi which i should do on my f5 devices?

**Comment by olguarabaci** [comment]
I add "ansible_httpapi_validate_certs: no" into my playbook. And now I am getting this error.

The full traceback is:
Traceback (most recent call last):
  File "/home/sa35623/.ansible/tmp/ansible-local-16502_6XSMu/ansible-tmp-1642690827.82-83439598324323/AnsiballZ_bigip_ssl_pkcs12.py", line 102, in <module>
    _ansiballz_main()
  File "/home/sa35623/.ansible/tmp/ansible-local-16502_6XSMu/ansible-tmp-1642690827.82-83439598324323/AnsiballZ_bigip_ssl_pkcs12.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/sa35623/.ansible/tmp/ansible-local-16502_6XSMu/ansible-tmp-1642690827.82-83439598324323/AnsiballZ_bigip_ssl_pkcs12.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_bigip.plugins.modules.bigip_ssl_pkcs12', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 389, in <module>
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 382, in main
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 230, in exec_module
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 243, in present
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py", line 272, in exists
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/module_utils/client.py", line 24, in wrap
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/module_utils/client.py", line 48, in get
  File "/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: addinfourl instance has no attribute 'getheaders'

fatal: [10.113.251.54]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/sa35623/.ansible/tmp/ansible-local-16502_6XSMu/ansible-tmp-1642690827.82-83439598324323/AnsiballZ_bigip_ssl_pkcs12.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/sa35623/.ansible/tmp/ansible-local-16502_6XSMu/ansible-tmp-1642690827.82-83439598324323/AnsiballZ_bigip_ssl_pkcs12.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sa35623/.ansible/tmp/ansible-local-16502_6XSMu/ansible-tmp-1642690827.82-83439598324323/AnsiballZ_bigip_ssl_pkcs12.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_bigip.plugins.modules.bigip_ssl_pkcs12', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py\", line 389, in <module>\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py\", line 382, in main\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py\", line 230, in exec_module\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py\", line 243, in present\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_ssl_pkcs12.py\", line 272, in exists\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/module_utils/client.py\", line 24, in wrap\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible_collections/f5networks/f5_bigip/plugins/module_utils/client.py\", line 48, in get\n  File \"/tmp/ansible_bigip_ssl_pkcs12_payload_WTO8QU/ansible_bigip_ssl_pkcs12_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\n**ansible.module_utils.connection.ConnectionError: addinfourl instance has no attribute 'getheaders'**\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by wojtek0806** [comment]
I would suggest upgrading to the latest ansible version or at least latest 2.9 and retry this error comes from the ansible part of code

**Comment by KrithikaChidambaram** [comment]
Hi, have you tried upgrading to the latest version of Ansible? Thanks!

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
