### ISSUE TITLE
Monitor modules fail when destination in BigIP conf uses '.' as a delimiter, instead of ':'

### ISSUE THREAD

**Issue by erichyde** [F5Networks/f5-ansible#2163]
##### COMPONENT NAME
bigip_monitor_https

##### ANSIBLE VERSION

```
ansible 2.9.25
  config file = /home/<profile>/f5/loadbalancer_general/ansible.cfg
  configured module search path = ['/home/<profile>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<profile>/venv/web_f5/lib/python3.8/site-packages/ansible
  executable location = /home/<profile>/venv/web_f5/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.3.1
  Build       0.0.18
  Edition     Point Release 1
  Date        Mon Jul 12 23:47:21 PDT 2021
```
##### CONFIGURATION

collections_paths = collections

##### OS / ENVIRONMENT
N/A

##### SUMMARY
bigip_monitor_https expects a monitor's destination to be configured as: 
```
destination IP:port
```

I have several monitors, all configured with an Alias port that follow a different format, please note IP and port are delimited by a '.':
```
destination IP.port
```

The underlying Python code for the bigip_monitor_https module attempts to extract the IP and Port, by splitting off of a ':' character, which does not exist in BigIP Conf when the monitor is configured with an Alias port.

##### STEPS TO REPRODUCE

```
---
- name: experiment with monitors
  hosts: localhost
  gather_facts: False
  vars:
    f5_partition: Common
    f5_provider:
      user: '{{ f5_user }}'
      password: '{{ f5_password }}'
      server: corp7-adc-cr-1ab-pilot.net.example.com
      server_port: 443
      validate_certs: no


  tasks:
    - name: set mon dictionary
      set_fact:
        mon:
          type: https
          name: xld-test-4516
          full_path: '/{{ f5_partition }}/xld-test-4516'
          interval: 10
          ip: '*'
          parent: '/Common/https'
          port: 4516
          receive_string: "HTTP/1.(0|1) 204"
          reverse: no
          send_string: "GET /deployit/ha/health HTTP/1.0\\r\\nHost: xld.test.example.com \\r\\nConnection: Close\\r\\n\\r\\n"
          time_until_up: 0
          timeout: 16
          up_interval: 0


    - name: Create HTTPS Monitor
      bigip_monitor_https:
        name: '{{ mon.name }}'
        description: '{{ mon.description | default(omit) }}'
        state: present
        interval: '{{ mon.interval }}'
        ip: '{{ mon.ip }}'
        cipher_list: '{{ mon.cipher_list | default(omit) }}'
        parent: '{{ mon.parent }}'
        partition: '{{ f5_partition }}'
        port: '{{ mon.port }}'
        receive: '{{ mon.receive_string }}'
        receive_disable: '{{ mon.receive_disable | default(omit) }}'
       reverse: '{{ mon.reverse }}'
        send: '{{ mon.send_string }}'
        ssl_profile: '{{ mon.ssl_profile | default(omit) }}'
        target_password: '{{ mon.target_password | default(omit) }}'
        target_username: '{{ mon.target_username | default(omit) }}'
        time_until_up: '{{ mon.time_until_up }}'
        timeout: '{{ mon.timeout }}'
        up_interval: '{{ mon.up_interval }}'
        provider: '{{ f5_provider }}'
      when: mon.type == 'https'
      register: monitor_result
     collections:
       - f5networks.f5_modules

```

##### EXPECTED RESULTS
I expect bigip_monitor_https to report no change, since the monitor already exists on the F5.

##### ACTUAL RESULTS

```
TASK [Create HTTPS Monitor name={{ mon.name }}, description={{ mon.description | default(omit) }}, state=present, interval={{ mon.interval }}, ip={{ mon.ip }}, cipher_list={{ mon.cipher_list | default(omit) }}, parent={{ mon.parent }}, partition={{ f5_partition }}, port={{ mon.port }}, receive={{ mon.receive_string }}, receive_disable={{ mon.receive_disable | default(omit) }}, send={{ mon.send_string }}, ssl_profile={{ mon.ssl_profile | default(omit) }}, target_password={{ mon.target_password | default(omit) }}, target_username={{ mon.target_username | default(omit) }}, time_until_up={{ mon.time_until_up }}, timeout={{ mon.timeout }}, up_interval={{ mon.up_interval }}, provider={{ f5_provider }}] ***
task path: /home/<username>/f5/loadbalancer_general/f5_support.yml:34
<127.0.0.1> Using network group action bigip for bigip_monitor_https
<127.0.0.1> connection transport is rest
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: <username>
<127.0.0.1> EXEC /bin/sh -c 'echo ~<username> && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/<username>/.ansible/tmp `"&& mkdir "` echo /home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054 `" && echo ansible-tmp-1643139837.6932404-1038-35536528232054="` echo /home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054 `" ) && sleep 0'
Using module file /home/<username>/venv/web_f5/lib/python3.8/site-packages/ansible/modules/network/f5/bigip_monitor_https.py
<127.0.0.1> PUT /home/<username>/.ansible/tmp/ansible-local-1032jp83zjnv/tmp_wgdj_3u TO /home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/ /home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/<username>/venv/web_f5/bin/python3 /home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py", line 102, in <module>
    _ansiballz_main()
  File "/home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_monitor_https', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py", line 746, in <module>
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py", line 739, in main
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py", line 543, in exec_module
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py", line 564, in present
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py", line 584, in update
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py", line 693, in read_current_from_device
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/module_utils/network/f5/common.py", line 505, in __init__
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/module_utils/network/f5/common.py", line 538, in update
  File "/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py", line 301, in destination
ValueError: not enough values to unpack (expected 2, got 1)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/<username>/.ansible/tmp/ansible-tmp-1643139837.6932404-1038-35536528232054/AnsiballZ_bigip_monitor_https.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_monitor_https', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py\", line 746, in <module>\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py\", line 739, in main\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py\", line 543, in exec_module\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py\", line 564, in present\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py\", line 584, in update\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py\", line 693, in read_current_from_device\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/module_utils/network/f5/common.py\", line 505, in __init__\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/module_utils/network/f5/common.py\", line 538, in update\n  File \"/tmp/ansible_bigip_monitor_https_payload_sokyd27n/ansible_bigip_monitor_https_payload.zip/ansible/modules/network/f5/bigip_monitor_https.py\", line 301, in destination\nValueError: not enough values to unpack (expected 2, got 1)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by amolari** [comment]
I do see the same issue with the bigip_monitor_http

**Comment by trinaths** [comment]
Created [INFRAANO-664] for internal tracking.
