### ISSUE TITLE
Ansible Error: X-F5-Auth-Token has expired when running bigip_device_info

### ISSUE THREAD

**Issue by vaderisback77** [F5Networks/f5-ansible#2199]
##### COMPONENT NAME
Ansible Module: **bigip_device_info**

https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_device_info_module.html#bigip-device-info-module-2

##### ANSIBLE VERSION
```
>> ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red
Hat 4.8.5-44.0.3)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.7]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]
  jinja version = 3.0.3
  libyaml = True
[root@13c961e212d6 app]$
```
##### BIGIP VERSION

```
This error is seen for two different BIGIP LTM code versions 
# Chassis 1
# show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018

#Chassis 2  
show sys version

Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.4
  Build    2.0.291
  Edition  Hotfix HF2
  Date     Thu Jul 21 16:10:24 PDT 2016

Hotfix List
ID566361-2  ID584717    ID571183-3  ID566908-3   ID579085-7  ID559541-3
ID527145-3  ID538761-1  ID592854-2  ID483665-3   ID549086-3  ID564521-2
ID577811    ID406001-5  ID558946-3  ID446493-3   ID558779-5  ID564427-1
ID586878-1  ID372473-3  ID548053-1  ID557281-3   ID581770-1  ID564111-2
ID481806-4  ID579874    ID531983-4  ID555039-1   ID530812-5  ID582295
ID591908-6  ID462268-1  ID580596-5  ID551287-3   ID596603-5  ID575671-1
ID575569-1  ID519217-2  ID518275-3  ID575292-2   ID559975-4  ID466007-3
ID575631-2  ID580421-4  ID575027-3  ID606293     ID558631-6  ID576305-1
ID574781-3  ID554228-4  ID530242-4  ID510580-3   ID575619-1  ID520088-1
ID513083-2  ID565169-1  ID482202-2  ID580340-4   ID492780-3  ID570667-10
ID555457-4  ID559034-3  ID579559-4  ID487859-2   ID563064-5  ID591894-6
ID451089-1  ID554993-1  ID473344-7  ID563670-5   ID458563-3  ID515322-2
ID575726-1  ID513530-3  ID557645-1  ID517020-4   ID527168-3  ID466612-2
ID552151-1  ID425980-2  ID534111-2  ID575571-1   ID463202-6  ID562044-1
ID453949-3  ID572600    ID559055    ID483228-8   ID585412-1  ID556774-1
ID562919-1  ID565534-3  ID533658-3  ID554340-2   ID574214-2  ID588243-5
ID560405-5  ID579975-4  ID400456-2  ID591806-4   ID540996-4  ID508076-1
ID416372-3  ID565895-3  ID574262    ID598983-5   ID579284-5  ID564482-3
ID551767-2  ID569521-2  ID554967-2  ID562775-3   ID579955-4  ID566646-2
ID486725-1  ID500786-4  ID564496-2  ID546747-4   ID570053-1  ID558602-2
ID569642-3  ID539784-2  ID549543-2  ID572563-4   ID492122-4  ID551189-2
ID339825-2  ID560975-1  ID516816-2  ID579237-4   ID521711-3  ID552937-2
ID577814    ID552198-3  ID556694-6  ID474194-4   ID548385-1  ID574318-4
ID575708-1  ID569236-2  ID555272-3  ID556597-3   ID418664-3  ID549971-3
ID453640-2  ID570640-4  ID561539-1  ID574116-3   ID461084-2  ID561814-4
ID567379-2  ID490174-3  ID291469-3  ID573406-2   ID517209-6  ID568889-5
ID549868-2  ID580303-2  ID581834-3  ID572133-3   ID577826-3  ID575626-6
ID336255-8  ID536746-2  ID529484-3  ID571019-2   ID445633-2  ID554626
ID536575-2  ID555549-2  ID505071-2  ID557062-3   ID576069-1  ID445471-1
ID577823-3  ID510979-2  ID575499-3  ID553925-3   ID540893-3  ID533480-4
ID512954-1  ID454071-1  ID458872-1  ID541156-3   ID569467-2  ID490936-1
ID468471-1  ID595874-3  ID572224    ID579829-4   ID491716-3  ID536191-3
ID542742-3  ID528548-1  ID563227-4  ID551481-4   ID529899-3  ID552498-2
ID478812-4  ID574073    ID579919    ID535544-7   ID417006-5  ID571344-2
ID575587-1  ID553649    ID553795-3  ID541231-1   ID531809-1  ID600662-5
ID573529    ID575582-1  ID541134-3  ID583936-1   ID541126-1  ID458348-3
ID507499-2  ID388274-2  ID596488-5  ID481003-1   ID528139-4  ID520408-1
ID547942    ID553688-3  ID518550-5  ID544325-2   ID452900-3  ID549406-3
ID513213-4  ID499795-3  ID519059-2  ID579371-1   ID552865-5  ID550536-4
ID534795-6  ID548583-5  ID487625-4  ID579909-3   ID546640-1  ID591918-6
ID556252    ID459671-1  ID486791-3  ID419217-1   ID552931-2  ID557519-1
ID488811-4  ID569356-5  ID542654    ID573581-2   ID449231-1  ID548680-3
ID451494-1  ID469627-2  ID552352-3  ID575735-1   ID531979-4  ID564253-6
ID547532-6  ID582952    ID569958-3  ID570667-15  ID539125-1  ID454583-4
ID575557-2  ID582683-1  ID576318    ID569337-4   ID553174-2  ID569472-3
ID570617-5  ID571003-4  ID571090-1  ID585045     ID488989-4  ID550689-3
ID551742-1  ID580817-4  ID401893-2  ID575612-4   ID575321-1  ID464687-1
ID575716-1  ID572543-4  ID573124-5  ID478215-5   ID589298    ID571573-3
ID529141-4  ID486512-8  ID599168-5  ID572922-3   ID509416-4  ID372118-1
ID565231-1  ID541316-5  ID527742-1  ID533820-3   ID405611-2  ID452659-1
ID540571-4  ID524641-4  ID569972-3  ID470627-4   ID551927-3  ID472446-4
ID532685-5  ID540568-4  ID515667-6  ID452318-2   ID515736-5  ID519216-3
ID539466-3  ID579085-3  ID575609-4  ID556103-2   ID563443-3  ID517613-2
ID551349-1  ID409323-2  ID569306-5  ID559138-4   ID583285-2  ID561433-6
ID404141-3  ID544375-2  ID540576-2  ID540213-4   ID437285-4  ID471467-1
ID506199-8  ID505089-3  ID569255-5  ID575564-1   ID565810-5  ID572893-5
ID452487-5  ID496679-3  ID558612-3  ID554041-4   ID566758-3  ID564262-3
ID399732-2  ID576296-1  ID573429-2  ID583631-1   ID516219-2  ID578844-3
ID575608-1  ID523471-3  ID580313-4  ID550596-2   ID570064-4  ID458737-1
ID577828-4  ID557783-3  ID457811-1  ID468791-3   ID554563-2  ID591881-5
ID548563-3  ID574045-3  ID575565-1  ID554074-3   ID472969-3  ID529900-4
ID562566-3  ID560748    ID570716-1  ID559939-3   ID405635-5  ID421971-7
ID457109-3  ID571210-3  ID563419-3  ID524281-1   ID569288-4  ID558573-3
ID557144-1  ID569349-3  ID556560-1  ID490801-3   ID576350-3  ID586056
ID556380-3  ID547537-4  ID563475-1  ID468949-1   ID551010-3  ID547732-3
ID579047    ID579220-2  ID550782-2  ID555905-1   ID558870-4  ID563591-3
  
```
##### CONFIGURATION

```
gathering = explicit
log_path = ./logs/ansible.log
nocows = 1
```

##### OS / ENVIRONMENT

```
Docker container
[root@13c961e212d6 ansible]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

##### SUMMARY
When running ansible task, **bigip_device_info**, against a given set of options on BIGIP LTM, seeing X5-Auth Token has expired error every-time this task is run. 
So, far we have seen this only on the LTM 8900 chassis

##### STEPS TO REPRODUCE

```
# Ansible Code
---

- name: Get device info
  bigip_device_info:
    provider: "{{ provider }}"
    gather_subset:
      - client-ssl-profiles
      - devices
      - device-groups
      - ltm-pools
      - monitors
      - partitions
      - self-ips
      - ssl-certs
      - ssl-keys
      - sync-status
      - virtual-servers
  register: device_info
  delegate_to: "{{ delegate_server }}"
  check_mode: no
  no_log: true  # The ansible_facts JSON output is just too long for display
```

##### EXPECTED RESULTS
the device task should run successfully gathering the device configuration details as specified by the bigip_device_info gather_subset sub-command

##### ACTUAL RESULTS

The ansible task fails every-time when run. 

```
ok: [DEVICE -> localhost]TASK [Get device info] ***************************************************************************************************************************************************************************************************************************************************************************
[WARNING]: Collection ansible.netcommon does not support Ansible version 2.11.5
[WARNING]: Collection ansible.netcommon does not support Ansible version 2.11.5
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@fatal: [DEVICE -> BASTION]: FAILED! => {"changed": false, "msg": "{\"code\":401,\"message\":\"X-F5-Auth-Token has expired.\",\"referer\":\"10.92.184.166\",\"restOperationId\":17091985997,\"errorStack\":[\"java.lang.SecurityException: X-F5-Auth-Token has expired.\",\"at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:236)\",\"at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:111)\",\"at com.f5.rest.workers.EvaluatePermissions.access$000(EvaluatePermissions.java:22)\",\"at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:88)\",\"at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:84)\",\"at com.f5.rest.common.RestOperation.complete(RestOperation.java:2261)\",\"at com.f5.rest.workers.AuthTokenWorker.onGet(AuthTokenWorker.java:209)\",\"at com.f5.rest.common.RestCollectionWorker.callDerivedRestMethod(RestCollectionWorker.java:801)\",\"at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)\",\"at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1348)\",\"at com.f5.rest.common.RestServer.access$000(RestServer.java:45)\",\"at com.f5.rest.common.RestServer$1.run(RestServer.java:309)\",\"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)\",\"at java.util.concurrent.FutureTask.run(FutureTask.java:262)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)\",\"at java.lang.Thread.run(Thread.java:748)\\n\"],\"kind\":\":resterrorresponse\"}"}
^@fatal: [DEVICE -> BASTION]: FAILED! => {"changed": false, "msg": "{\"code\":401,\"message\":\"X-F5-Auth-Token has expired.\",\"referer\":\"10.92.184.166\",\"restOperationId\":15326727,\"errorStack\":[\"java.lang.SecurityException: X-F5-Auth-Token has expired.\",\"at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:236)\",\"at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:111)\",\"at com.f5.rest.workers.EvaluatePermissions.access$000(EvaluatePermissions.java:22)\",\"at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:88)\",\"at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:84)\",\"at com.f5.rest.common.RestOperation.complete(RestOperation.java:2261)\",\"at com.f5.rest.workers.AuthTokenWorker.onGet(AuthTokenWorker.java:209)\",\"at com.f5.rest.common.RestCollectionWorker.callDerivedRestMethod(RestCollectionWorker.java:801)\",\"at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)\",\"at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1348)\",\"at com.f5.rest.common.RestServer.access$000(RestServer.java:45)\",\"at com.f5.rest.common.RestServer$1.run(RestServer.java:309)\",\"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)\",\"at java.util.concurrent.FutureTask.run(FutureTask.java:262)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)\",\"at java.lang.Thread.run(Thread.java:748)\\n\"],\"kind\":\":resterrorresponse\"}"}PLAY RECAP 

***************************************************************************************************************************************************************************************************************************************************************************************
DEVICE : ok=6    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
auto_rollback=True --check failed: None
```

**Comment by trinaths** [comment]
Created [INFRAANO-713] for internal tracking.

**Comment by vaderisback77** [comment]
minus my comment about BIGIP version: 11.5.4 since icontrol REST API is not supported in this revision. I only care about the LB pair running 12.1.3.7

**Comment by RavinderReddyF5** [comment]
@vaderisback77, By default, a token expires after 1,200s (20 min). is this module run from your playbook taking more than (20min) of time? also it is better to isolate which subset is taking more time. 
You can extend the token lifespan by modifying the "timeout" property in the token object. The maximum lifespan is 36,000s (10 hrs). anyway we are trying to add timeout parameter in provider for increasing token expiry.
