### ISSUE TITLE
bigip_device_info ValueError: invalid literal for int() with base 10: 'ttl'

### ISSUE THREAD

**Issue by gdicheck** [F5Networks/f5-ansible#2263]
The bigip_device_info module fails and raises "ValueError: invalid literal for int() with base 10: 'ttl'" when gathering data for LTM nodes if there are nodes with an FQDN instead of an IP address.

```
Traceback (most recent call last):
  File "/home/example/.ansible/tmp/ansible-tmp-1666276277.9098308-11836-118385680822381/AnsiballZ_bigip_device_info.py", line 102, in <module>
    _ansiballz_main()
  File "/home/example/.ansible/tmp/ansible-tmp-1666276277.9098308-11836-118385680822381/AnsiballZ_bigip_device_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/example/.ansible/tmp/ansible-tmp-1666276277.9098308-11836-118385680822381/AnsiballZ_bigip_device_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 18352, in <module>
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 18336, in main
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 18019, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 18126, in execute_managers
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13339, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13347, in _exec_module
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 7621, in to_return
  File "/tmp/ansible_bigip_device_info_payload_GWX67y/ansible_bigip_device_info_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py", line 13267, in fqdn_up_interval
ValueError: invalid literal for int() with base 10: 'ttl'
```

The defect arises because the option "interval" is an integer like 3600 for IP address nodes. In contrast, FQDN nodes have a Boolean value for "Use Interval" in the UI and store the text "ttl" for the "interval" option when "Use Interval" is checked (true).

bigip_device_info.py expects "interval" to be an integer and casts its value to "int" inside "def fqdn_up_interval(self)". The invalid casting causes the exception because the string "ttl" cannot be casted to an integer:

```
ValueError: invalid literal for int() with base 10: 'ttl'
```

Code snippet from bigip_device_info.py at line 13267, which uses collection version 1.20:

```
@property
def fqdn_up_interval(self):
    if self._values['fqdn'] is None:
        return None
    result = self._values['fqdn'].get('interval', None)
    if result:
        return int(result)
```

Simplest solution is remove the cast to int:

```
def fqdn_up_interval(self):
    if self._values['fqdn'] is None:
        return None
    result = self._values['fqdn'].get('interval', None)
    if result:
        # Defective original line:
        # return int(result)
        #
        # Corrected line:
        return result
```

**Comment by KrithikaChidambaram** [comment]
Hi, internal ID to track this item is: INFRAANO-979, thanks!
