### ISSUE TITLE
module failure caused by teem

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible#2264]
##### COMPONENT NAME
`f5networks/f5_modules/plugins/module_utils/teem.py`

##### ANSIBLE VERSION
```
ansible --version
/usr/local/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
ansible 2.9.27
  config file = /ansible/ansible.cfg
  configured module search path = [u'/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.18 (default, Apr 20 2020, 19:27:10) [GCC 8.3.0]


```
##### BIGIP VERSION

```
16.1.6
```
##### CONFIGURATION

```yaml
    - name: Save the running configuration of the BIG-IP
      f5networks.f5_modules.bigip_config:
        save: yes
        provider:
          server: 10.1.1.245
          user: admin
          password: 'secret'
          validate_certs: no
          server_port: 443
          no_f5_teem: no # <---- teem enabled
      delegate_to: localhost
```

##### SUMMARY

module fails with the below traceback:

```
Traceback (most recent call last):
  File "/ansible/.ansible/tmp/ansible-tmp-1666717657.54-591-73620469700041/AnsiballZ_bigip_config.py", line 102, in <module>
    _ansiballz_main()
  File "/ansible/.ansible/tmp/ansible-tmp-1666717657.54-591-73620469700041/AnsiballZ_bigip_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/ansible/.ansible/tmp/ansible-tmp-1666717657.54-591-73620469700041/AnsiballZ_bigip_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_config.py", line 412, in <module>
  File "/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_config.py", line 405, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_config.py", line 172, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 165, in send_teem
  File "/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 73, in send
  File "/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 48, in prepare_request
  File "/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 96, in build_telemetry
TypeError: split() takes no keyword arguments
fatal: [bigip16 -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/ansible/.ansible/tmp/ansible-tmp-1666717657.54-591-73620469700041/AnsiballZ_bigip_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/ansible/.ansible/tmp/ansible-tmp-1666717657.54-591-73620469700041/AnsiballZ_bigip_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/ansible/.ansible/tmp/ansible-tmp-1666717657.54-591-73620469700041/AnsiballZ_bigip_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/local/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/local/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_config.py\", line 412, in <module>\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_config.py\", line 405, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_config.py\", line 172, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 165, in send_teem\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 73, in send\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 48, in prepare_request\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_config_payload_lSjDuQ/ansible_f5networks.f5_modules.bigip_config_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 96, in build_telemetry\nTypeError: split() takes no keyword arguments\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

https://github.com/F5Networks/f5-ansible/blob/7829d4a14ba4048ecbdb9bd4cc002dd66ecfe981/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py#L96

Python 2.7 does not accept `maxsplit=` as a kwarg, it expects positional args.

https://docs.python.org/2.7/library/stdtypes.html?highlight=split#str.split

##### STEPS TO REPRODUCE

```
Use the configuration above with python 2.7 and ansible 2.9.
```

Example Dockerfile to reproduce the problem:

```dockerfile
FROM python:2.7.18-buster

RUN useradd ansible -d /ansible -M -u 1000

RUN apt update; apt upgrade -y;
RUN apt install -y \
            less \
            vim \
            iproute2 \
            rpm \
            ;

RUN pip install \
            ansible==2.9.27 \
            "ansible-lint" \
            yamllint \
            ;

RUN \
echo '    UserKnownHostsFile /dev/null' >> /etc/ssh/ssh_config; \
echo '    StrictHostKeyChecking no' >> /etc/ssh/ssh_config;

USER ansible

WORKDIR /ansible
```

**Workaround: Disable teem in the provider config**

```yaml
    - name: Save the running configuration of the BIG-IP
      f5networks.f5_modules.bigip_config:
        save: yes
        provider:
          server: 10.1.1.245
          user: admin
          password: 'secret'
          validate_certs: no
          server_port: 443
          no_f5_teem: yes # <---- teem disabled
      delegate_to: localhost
```

##### EXPECTED RESULTS

```
Module does not fail.
```

##### ACTUAL RESULTS

```
Module fails.
```

**Comment by wojtek0806** [comment]
We dropped  support for python 2.7 ages ago use python 3.6 and above

**Comment by wojtek0806** [comment]
The error is related to python 2.7 split() function.

**Comment by G-gonzalezjimenez** [comment]
Closed, because of unsupported python version. Closing this item
