### ISSUE TITLE
bigip_irule does not turn off ssl cert verification when validate_certs = False

### ISSUE THREAD

**Issue by spopplewell** [F5Networks/f5-ansible#231]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_irule

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /usr/local/csapps/jenkins/workspace/deploy_development_pivotal/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION

```
BIG-IP 12.1.2 Build 0.93.249 Engineering Hotfix
```

##### CONFIGURATION

[defaults]
host_key_checking=False
inventory=inventory

##### OS / ENVIRONMENT

SUSE 12

##### SUMMARY

bigip_irule will not turn off ssl verification.

##### STEPS TO REPRODUCE

```
- name: Add the iRule contained in static file irule.tcl to the LTM module
  bigip_irule:
      module: "ltm"
      name: "MyiRule"
      password: "{{ f5_password }}"
      server: "{{ f5_server_ip }}"
      content: "when HTTP_REQUEST {HTTP::respond 200 content 'Good Request'}\n"
      state: "present"
      user: "{{ f5_user }}"
      validate_certs: False
  delegate_to: localhost
```

##### EXPECTED RESULTS

Task to succeed with changed: true
##### ACTUAL RESULTS

Fatal error.

```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_Wim3vo/ansible_module_bigip_irule.py\", line 389, in <module>\n    main()\n  File \"/tmp/ansible_Wim3vo/ansible_module_bigip_irule.py\", line 377, in main\n    obj = BigIpiRule(check_mode=module.check_mode, **module.params)\n  File \"/tmp/ansible_Wim3vo/ansible_module_bigip_irule.py\", line 165, in __init__\n    port=kwargs['server_port'])\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 124, in __init__\n    self.post_configuration_setup()\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 91, in post_configuration_setup\n    self._get_tmos_version()\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 96, in _get_tmos_version\n    response = connect.get(base_uri)\n  File \"/usr/lib/python2.7/site-packages/icontrol/session.py\", line 272, in wrapper\n    raise iControlUnexpectedHTTPError(error_message, response=response)\nicontrol.exceptions.iControlUnexpectedHTTPError: 401 Unexpected Error: F5 Authorization Required for uri: https://10.180.1.46:443/mgmt/tm/sys/\nText: u'{\"code\":401,\"message\":\"Authorization failed: user=https://localhost/mgmt/shared/authz/users/spopplewell resource=/mgmt/tm/sys verb=GET uri:http://localhost:8100/mgmt/tm/sys/ referrer:10.17.116.27 sender:10.17.116.27\",\"referer\":\"10.17.116.27\",\"restOperationId\":20010366,\"errorStack\":[\"java.lang.SecurityException: Authorization failed: user=https://localhost/mgmt/shared/authz/users/spopplewell resource=/mgmt/tm/sys verb=GET uri:http://localhost:8100/mgmt/tm/sys/ referrer:10.17.116.27 sender:10.17.116.27\",\"at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:236)\",\"at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:198)\",\"at com.f5.rest.workers.EvaluatePermissions.evaluatePermission(EvaluatePermissions.java:78)\",\"at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:227)\",\"at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:492)\",\"at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1061)\",\"at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)\",\"at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1362)\",\"at com.f5.rest.common.RestServer.access$000(RestServer.java:45)\",\"at com.f5.rest.common.RestServer$1.run(RestServer.java:323)\",\"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\",\"at java.util.concurrent.FutureTask.run(FutureTask.java:262)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\",\"at java.lang.Thread.run(Thread.java:745)\\\\n\"],\"kind\":\":resterrorresponse\"}'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by caphrim007** [comment]
@spopplewell what role does this user have? The error usually indicates incorrect username, password, or a role that doesnt have access to the API.

**Comment by spopplewell** [comment]
The f5 user has Manager permissions.

I can successfully remove and add members to pools using the same credentials and server using the bigip_pool_member.

**Comment by spopplewell** [comment]
The F5 user I am using is able to create an iRule using the iControl REST API.

I am really hoping to take advantage of this ansible module.

**Comment by caphrim007** [comment]
@spopplewell can you try using the module in this repository instead of the one that ships with Ansible? It appears we have a module with newer code and it may work for you

**Comment by spopplewell** [comment]
Thanks Tim. That was worked for me. What is the process for submitting the newer version to ansible?

Thank you for all of your work. It has helped me tremendously!

**Comment by caphrim007** [comment]
@spopplewell I will make sure this is fully tested and pushed upstream before the 2.4 release

**Comment by caphrim007** [comment]
@spopplewell the updated module has been upstreamed and will be released with ansible 2.4. thank you for finding this issue!

**Comment by m2harshanalore** [comment]
@spopplewell : I still get the error after upgrading to ansible to 2.4.2.0. Can you assist me ? I even did validate_certs: False in my playbook.

**Comment by caphrim007** [comment]
@m2harshanalore please do not comment on old issues. file a new issue with your specific details and we will address it there
