### ISSUE TITLE
bigip_device_info - RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by ashleytayles** [F5Networks/f5-ansible#2325]
##### COMPONENT NAME
bigip_device_info

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /home/[redacted]/ansible2.9_sandbox/[redacted]/ansible.cfg
  configured module search path = ['/home/[redacted]/ansible2.9_sandbox/[redacted]/library']
  ansible python module location = /home/[redacted]/ansible2.9_sandbox/.direnv/python-3.8.10/lib/python3.8/site-packages/ansible
  executable location = /home/[redacted]/ansible2.9_sandbox/.direnv/python-3.8.10/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.0
  Build       0.0.19
  Edition     Final
  Date        Tue Jun 22 23:52:22 PDT 2021
```
##### CONFIGURATION

```
    - name: Collect F5 Facts
      bigip_device_info:
        gather_subset:
          - system-info
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          validate_certs: false
      delegate_to: localhost
      register: f5_facts
```

##### OS / ENVIRONMENT

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"

##### SUMMARY
When running bigip_device_info on Ansible 2.9 with subset 'system-info', it fails with a fatal exception.

Running the same exact playbook on the same machine using a venv running Ansible 2.12, the module works fine.

I have tested with:
latest devel build
1.23.0
1.22.1
1.21.0

##### STEPS TO REPRODUCE

Run the following playbook in Ansible 2.9.

```
    - name: Collect F5 Facts
      bigip_device_info:
        gather_subset:
          - system-info
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          validate_certs: false
      delegate_to: localhost
      register: f5_facts
```

##### EXPECTED RESULTS
Gather system-info facts.

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/home/[redacted]/.ansible/tmp/ansible-tmp-1681809896.841817-589907-96399158978580/AnsiballZ_bigip_device_info.py", line 102, in <module>
    _ansiballz_main()
  File "/home/[redacted]/.ansible/tmp/ansible-tmp-1681809896.841817-589907-96399158978580/AnsiballZ_bigip_device_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/[redacted]/.ansible/tmp/ansible-tmp-1681809896.841817-589907-96399158978580/AnsiballZ_bigip_device_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16266, in <module>
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16259, in main
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15999, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16078, in execute_managers
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13445, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13451, in _exec_module
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 7092, in to_return
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13391, in hardware_information
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13400, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13400, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13405, in _transform_name_attribute
  File "/tmp/ansible_bigip_device_info_payload_u7mlv6ft/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 13397, in _transform_name_attribute
RuntimeError: dictionary keys changed during iteration
```

**Comment by pgouband** [comment]
Hi @ashleytayles,

Version 2.9 is End of Life so we recommend using the latest version.
