### ISSUE TITLE
Module Error with f5networks.f5_modules.bigip_ssl_key_cert

### ISSUE THREAD

**Issue by evanatuo** [F5Networks/f5-ansible#2333]
##### COMPONENT NAME

f5networks.f5_modules.bigip_ssl_key_cert

##### ANSIBLE VERSION

```
ansible [core 2.13.9]
  config file = /certsvc/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /certsvc/ansible/lib64/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /certsvc/ansible/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.8
  Build       0.0.7
  Edition     Final
  Date        Fri Oct  7 07:25:45 PDT 2022
```
##### CONFIGURATION

My ansible.cfg:

```
[defaults]
roles_path          = ./roles
stdout_callback     = yaml
log_path            = ./ansible.log
nocows              = true
inventory_plugins   = ./inventory_plugins

[inventory]
enable_plugins = auto
```

##### OS / ENVIRONMENT

This is running in a kubernetes container.

I'm using a [RHEL Universal Base Image Container](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8)

Container Image: `registry.access.redhat.com/ubi8/ubi-minimal`

Running Python3.8 (3.8.13) in a venv with the following packages:
- ansible
- hvac 
- requests

Ansible Galaxy Collection: f5networks.f5_modules

##### SUMMARY

Was having an issue with SSL Certificate Validation, but then after it was disabled, it turned into this very generic error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception
fatal: [hostname.redacted.net -> localhost]: FAILED! => changed=false 
  attempts: 10
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1684438636.7275171-1617-2330686518037/AnsiballZ_bigip_ssl_key_cert.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1684438636.7275171-1617-2330686518037/AnsiballZ_bigip_ssl_key_cert.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1684438636.7275171-1617-2330686518037/AnsiballZ_bigip_ssl_key_cert.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_ssl_key_cert', init_globals=dict(_module_fqn='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_ssl_key_cert', _modlib_path=modlib_path),
      File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 822, in <module>
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 815, in main
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 410, in exec_module
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 426, in present
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 460, in create
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 656, in create_on_device
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 297, in __exit__
    Exception
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

##### STEPS TO REPRODUCE

```
- name: Process Redeployment Requests
  hosts: redeploy
  gather_facts: no
  become: no
  collections:
    - community.crypto
    - community.general
    - f5networks.f5_modules
  tasks:
    - name: Deploy Certificate to Sandbox LTM
      f5networks.f5_modules.bigip_ssl_key_cert:
        key_name: "{{ certificate_name }}"
        cert_name: "{{ certificate_name }}"
        state: present
        provider:
          user: "{{ f5_username }}"
          password: "{{ f5_password }}"
          server: REDACTED
          validate_certs: "{{ f5_validate }}" # Default True
          server_port: "{{ f5_httpport }}" # Default 443
      connection: local
      delegate_to: localhost
      register: _sandbox_deploy_result
      until: _sandbox_deploy_result is succeeded
      retries: 10
      delay: 10
      when: lifecycle_environment == "sandbox" and zone == "int"
```

##### EXPECTED RESULTS

Expected X.509/Certificate private/public key to be deployed on the LTM.

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception
fatal: [hostname.redacted.net -> localhost]: FAILED! => changed=false 
  attempts: 10
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1684438636.7275171-1617-2330686518037/AnsiballZ_bigip_ssl_key_cert.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1684438636.7275171-1617-2330686518037/AnsiballZ_bigip_ssl_key_cert.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1684438636.7275171-1617-2330686518037/AnsiballZ_bigip_ssl_key_cert.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_ssl_key_cert', init_globals=dict(_module_fqn='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_ssl_key_cert', _modlib_path=modlib_path),
      File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 822, in <module>
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 815, in main
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 410, in exec_module
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 426, in present
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 460, in create
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ssl_key_cert.py", line 656, in create_on_device
      File "/tmp/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload_mmc4n62a/ansible_f5networks.f5_modules.bigip_ssl_key_cert_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 297, in __exit__
    Exception
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by evanatuo** [comment]
From restjavad.0.log:

```
[I][7065][18 May 2023 20:34:23 UTC][8100/shared/authz/tokens AuthTokenWorker] Writing auth-token file succeeded.
[I][7072][18 May 2023 20:34:24 UTC][8100/shared/authz/tokens AuthTokenWorker] tokenfile is deleted!
```

From restjavad-audit.0.log:

```
[I][7120][18 May 2023 20:35:33 UTC][ForwarderPassThroughWorker] {"user":"local/null","method":"POST","uri":"http://localhost:8100/mgmt/shared/authn/login","status":200,"from":"10.10.10.10"}
[I][7121][18 May 2023 20:35:33 UTC][ForwarderPassThroughWorker] {"user":"tmos/username_redacted","method":"GET","uri":"http://localhost:8100/mgmt/tm/sys/file/ssl-key/~Common~auto_redacted_key_name_https_ssl.key","status":404,"from":"10.10.10.10"}
[I][7122][18 May 2023 20:35:33 UTC][ForwarderPassThroughWorker] {"user":"tmos/username_redacted","method":"POST","uri":"http://localhost:8100/mgmt/tm/transaction/","status":200,"from":"10.10.10.10"}
[I][7123][18 May 2023 20:35:33 UTC][ForwarderPassThroughWorker] {"user":"tmos/username_redacted","method":"POST","uri":"http://localhost:8100/mgmt/tm/sys/file/ssl-key/","status":200,"from":"10.10.10.10"}
[I][7124][18 May 2023 20:35:33 UTC][ForwarderPassThroughWorker] {"user":"tmos/username_redacted","method":"POST","uri":"http://localhost:8100/mgmt/tm/sys/file/ssl-cert/","status":200,"from":"10.10.10.10"}
[I][7125][18 May 2023 20:35:33 UTC][ForwarderPassThroughWorker] {"user":"tmos/username_redacted","method":"PATCH","uri":"http://localhost:8100/mgmt/tm/transaction/1684442133584184","status":400,"from":"10.10.10.10"}
[I][7127][18 May 2023 20:35:33 UTC][ForwarderPassThroughWorker] {"user":"tmos/username_redacted","method":"DELETE","uri":"http://localhost:8100/mgmt/shared/authz/tokens/JWAKCQBEXKYHQPPV7FTESHDXOV","status":200,"from":"10.10.10.10"}
```

**Comment by evanatuo** [comment]
Was missing payload from task, that was why it was failing. Should be like

```
    - name: Deploy Certificate to Sandbox LTM
      f5networks.f5_modules.bigip_ssl_key_cert:
        key_content: "{{ key_cert_final }}"
        key_name: "{{ certificate_name }}"
        cert_content: "{{ signed_cert_final }}"
        cert_name: "{{ certificate_name }}"
        state: present
        provider:
          user: "{{ f5_username }}"
          password: "{{ f5_password }}"
          server: redacted
          validate_certs: "{{ f5_validate }}"
          server_port: "{{ f5_httpport }}"
      connection: local
      register: _sandbox_deploy_result
      until: _sandbox_deploy_result is succeeded
      retries: 10
      delay: 10
      when: lifecycle_environment == "sandbox" and zone == "int"
```

This is resolved.
