### ISSUE TITLE
Timeout error bigip_ucs_fetch - Hard Coded Timeout in icontrol.py 

### ISSUE THREAD

**Issue by JHilsberg** [F5Networks/f5-ansible#2335]
##### COMPONENT NAME

bigip_ucs_fetch ansible module
icontrol.py ansible module util

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = None
  configured module search path = ['/home/automation/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 30 2019, 13:27:23) [GCC]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.5.3
  Build       0.0.5
  Edition     Point Release 3
  Date        Sun Dec 25 15:50:28 PST 2022

```
##### SUMMARY

When creating a backup file with the bigip_ucs_fetch module the execution is running into a timeout, always two minutes.
After checking the trace and the used module utils I found that there is hard coded time out value of 120 seconds in the icontrol.py class iControlRestSession:

https://github.com/F5Networks/f5-ansible/blob/79dcef20bb2cd7d68e9d06267920c36e4a59eb99/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py#L136

I assume this is the problem the execution fails. I set all timeout values in ansible to a higher value and also adopted the REST timeouts in the big IP system according to K94602685 (https://my.f5.com/manage/s/article/K94602685)

It only happens sometimes when the Big-IP system has CPU load through other processes and the creation of the UCS file needs longer then 2 minutes.
The UCS is also successfully created on the Big-IP device but the ansible task failed because the file was not created in time.

##### STEPS TO REPRODUCE

```
- name: Create UCS on F5 devices
  hosts: "f5_devices"

- tasks:
  - name: Only create new UCS in Big-IP device, no download
    bigip_ucs_fetch:
      provider: "{{ nw_f5_provider }}"
      src: f5-backup.ucs
      only_create_file: yes
      async_timeout: 600
    delegate_to: localhost
    vars:
        ansible_command_timeout: 600
        ansible_connect_timeout: 600
```

##### EXPECTED RESULTS

UCS file is created and task finish succesfully
##### ACTUAL RESULTS

UCS file is created but task failed

```
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1684757286.3974924-21156-145807655623349/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1684757286.3974924-21156-145807655623349/AnsiballZ_bigip_ucs_fetch.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1684757286.3974924-21156-145807655623349/AnsiballZ_bigip_ucs_fetch.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1684757286.3974924-21156-145807655623349/AnsiballZ_bigip_ucs_fetch.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_ucs_fetch', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 756, in <module>
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 749, in main
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 332, in exec_module
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 369, in exec_module
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 383, in present
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 443, in create
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 451, in create_on_device
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 505, in async_wait
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 233, in get
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 194, in send
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible/module_utils/urls.py", line 1294, in open
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible/module_utils/urls.py", line 467, in https_open
  File "/usr/lib64/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 968, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 830, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 587, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
fatal: [xxx -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/root/.ansible/tmp/ansible-tmp-1684757286.3974924-21156-145807655623349/AnsiballZ_bigip_ucs_fetch.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/root/.ansible/tmp/ansible-tmp-1684757286.3974924-21156-145807655623349/AnsiballZ_bigip_ucs_fetch.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/root/.ansible/tmp/ansible-tmp-1684757286.3974924-21156-145807655623349/AnsiballZ_bigip_ucs_fetch.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_ucs_fetch', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 205, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 756, in <module>\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 749, in main\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 332, in exec_module\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 369, in exec_module\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 383, in present\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 443, in create\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 451, in create_on_device\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py\\", line 505, in async_wait\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\\", line 233, in get\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\\", line 194, in send\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible/module_utils/urls.py\\", line 1294, in open\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 223, in urlopen\\n    return opener.open(url, data, timeout)\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 526, in open\\n    response = self._open(req, data)\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 544, in _open\\n    '_open', req)\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 504, in _call_chain\\n    result = func(*args)\\n  File \\"/tmp/ansible_bigip_ucs_fetch_payload_xyuvseti/ansible_bigip_ucs_fetch_payload.zip/ansible/module_utils/urls.py\\", line 467, in https_open\\n  File \\"/usr/lib64/python3.6/urllib/request.py\\", line 1321, in do_open\\n    r = h.getresponse()\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 1346, in getresponse\\n    response.begin()\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 307, in begin\\n    version, status, reason = self._read_status()\\n  File \\"/usr/lib64/python3.6/http/client.py\\", line 268, in _read_status\\n    line = str(self.fp.readline(_MAXLINE + 1), \\"iso-8859-1\\")\\n  File \\"/usr/lib64/python3.6/socket.py\\", line 586, in readinto\\n    return self._sock.recv_into(b)\\n  File \\"/usr/lib64/python3.6/ssl.py\\", line 968, in recv_into\\n    return self.read(nbytes, buffer)\\n  File \\"/usr/lib64/python3.6/ssl.py\\", line 830, in read\\n    return self._sslobj.read(len, buffer)\\n  File \\"/usr/lib64/python3.6/ssl.py\\", line 587, in read\\n    v = self._sslobj.read(len, buffer)\\nsocket.timeout: The read operation timed out\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by pgouband** [comment]
Hi @JHilsberg,

Have your tried using the declarative collection? https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_ucs_fetch_module.html#bigip-ucs-fetch-module-2

Timeout feature is available.

**Comment by JHilsberg** [comment]
Hi @pgouband ,

yes I already tried the declaritive collection but had there another problem. The execution of the playbook proceed with the next task even when the ucs file is not created and I set a poll value for the async task >0. Because i want to only create the UCS file with option "only_create_file: yes" and after completion save it to a remote host via SCP I need to wait for completion of the  UCS creation.

With the imperative collection I had no problems in the task execution behavior. The only thing is now this timeout occurred on the active BIG-IP cluster member. On the secondary and our test devices (where the UCS file is much smaller) It still runs successfully. 

BR Julian

**Comment by pgouband** [comment]
Hi @JHilsberg,

To troubleshoot the connection issue, could you do a tcpdump with decryption so that we can determine whether it's the BIG-IP or the Ansible client that's reseting the connection.
If you need help, you can open a ticket at https://my.f5.com/.

**Comment by JHilsberg** [comment]
Hi Patrick,

I made a TCPdump and checked the output and it looks that ansible is closing the connection exactly 120 seconds after sending the UCS generation command:
![image](https://github.com/F5Networks/f5-ansible/assets/5940911/0a156f41-48a4-4767-8c05-38f7f912f4b6)
10.1.45.2 is the ansible host
10.1.45.109 the Big-IP host

Do you want the complete capture file? I would share with you privately.

Thanks and regards
Julian

**Comment by pgouband** [comment]
Hi @JHilsberg,

Have you tried the following?
Timeout at provider level should override the timeout of 120s.

'''ansible
vars:
    nw_f5_provider:
      server: "{{ ansible_host }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      validate_certs: no
      server_port: "{{ bigip_port }}"
      timeout: 600

- tasks:
  - name: Only create new UCS in Big-IP device, no download
    bigip_ucs_fetch:
      provider: "{{ nw_f5_provider }}"
      src: f5-backup.ucs
      only_create_file: yes
    delegate_to: localhost
'''

**Comment by JHilsberg** [comment]
Hi @pgouband,

yes I already had set the timeout value in the provider variable to 300 seconds. 
But since 6. of June I didn't get any timeout issue anymore. Could it be related to pull request _#2330 - Added timeout fix for long running commands in bigip_command_?

I just tested some more times now also with additional CPU load on the Big-IP appliance but it now seems to be working even if the creation of the file takes longer as 120 seconds.

So for me it would be okay if we close the case. I will open a new one if we experience the issue again.

Thanks for your help.

Regards, Julian
