### ISSUE TITLE
bigip_view: Error: 'NoneType' object has no attribute 'flush'

### ISSUE THREAD

**Issue by christian2600** [F5Networks/f5-ansible#292]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_view

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       2.0.1671
  Edition     Hotfix HF2
  Date        Fri Apr 28 20:36:43 PDT 2017
```

##### CONFIGURATION

Default configuration

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core)

##### SUMMARY

Execute ansible-playbook "bigip_view" to create a View without zones, but it returns an error about:
The error was: AttributeError: 'NoneType' object has no attribute 'flush'

##### STEPS TO REPRODUCE

1) Download ansible
2) Add on modules: /usr/lib/python2.7/site-packages/ansible/modules/network/f5 github libraries for F5 https://github.com/F5Networks/f5-ansible.git
3) Execute ansible playbook 

```
- name: Create View ISP2s
  hosts: f5-test
  connection: local
  
  environment:
      F5_SERVER: "{{ inventory_hostname }}"
      F5_USER: "admin"
      F5_PASSWORD: "admin"
      F5_VALIDATE_CERTS: "false"
      F5_SERVER_PORT: 443

  vars:
      view_name: "ISP2"
      view_order: 0

  tasks:
       - name: create a view with name ISP2
         local_action:
                module: "bigip_view"
                view_name: "{{ view_name }}"
                view_order: "{{ view_order }}"

```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_c4OGys/ansible_module_bigip_view.py", line 348, in <module>
    main()
  File "/tmp/ansible_c4OGys/ansible_module_bigip_view.py", line 337, in main
    result = obj.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

fatal: [10.32.247.239 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_c4OGys/ansible_module_bigip_view.py\", line 348, in <module>\n    main()\n  File \"/tmp/ansible_c4OGys/ansible_module_bigip_view.py\", line 337, in main\n    result = obj.flush()\nAttributeError: 'NoneType' object has no attribute 'flush'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by thomsonjames** [comment]
Attempted in version 12.1.2 and see the same issue.  I actually don't see any requests leave my Ansible client so the error looks contained in the module itself.  In looking at the code, I think this is bigsuds-based since I don't believe this function is available in REST yet.  So, it could be a bigsuds issue.

**Comment by caphrim007** [comment]
@thomsonjames @christian2600 this module is not complete. Therefore, i would not expect it to work.
