### ISSUE TITLE
iControlUnexpectedHTTPError using bigip_partition

### ISSUE THREAD

**Issue by john3exonets** [F5Networks/f5-ansible#299]
##### ISSUE TYPE

 - Bug Report
??

##### COMPONENT NAME

bigip_partition

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/ubuntu/Ansible/ansible.cfg
  configured module search path = [u'./lib']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### PYTHON VERSION

```
Python 2.7.6
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### OS / ENVIRONMENT

 Ubuntu 14.04.5 LTS

##### SUMMARY

Trying to use 'big_partition', but getting an error.  Don't know if its operator error or a bug.  I am using a non-MGMT interface to get to the BIGIP.

##### STEPS TO REPRODUCE

Playbook I'm using:
```
- name: Setup BIGIP for CC4CF Demo
  hosts: bigip1
  connection: ssh
  gather_facts: false

  tasks:
      - name: Setup Partition
        bigip_partition:
                name: "cf"
                password: "{{ bigip_pass }}"
                server: "{{ inventory_hostname }}"
                user: "{{ bigip_user }}"
                state: "present"
                validate_certs: "no"
        delegate_to: localhost
```
Nothing fancy, just trying to get Ansible to work with BIGIP.

##### EXPECTED RESULTS

OK

##### ACTUAL RESULTS

```
$ ansible-playbook ./CC_Setup.yaml -i ./hosts -vvv
Using /home/ubuntu/Ansible/ansible.cfg as config file

PLAYBOOK: CC_Setup.yaml ***************************************************************************************************************************************************
1 plays in ./CC_Setup.yaml

PLAY [Setup BIGIP for CC4CF Demo] *****************************************************************************************************************************************
META: ran handlers

TASK [Setup Partition] ****************************************************************************************************************************************************
task path: /home/ubuntu/Ansible/CC_Setup.yaml:7
Using module file /home/ubuntu/Ansible/lib/bigip_partition.py
<10.105.174.233> ESTABLISH SSH CONNECTION FOR USER: root
<10.105.174.233> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/5a547716f2 10.105.174.233 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<10.105.174.233> (0, '/root\n', '')
<10.105.174.233> ESTABLISH SSH CONNECTION FOR USER: root
<10.105.174.233> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/5a547716f2 10.105.174.233 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863 `" && echo ansible-tmp-1502204912.54-145630385455863="` echo /root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863 `" ) && sleep 0'"'"''
<10.105.174.233> (0, 'ansible-tmp-1502204912.54-145630385455863=/root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863\n', '')
<10.105.174.233> PUT /tmp/tmpdO_qD5 TO /root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863/bigip_partition.py
<10.105.174.233> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/5a547716f2 '[10.105.174.233]'
<10.105.174.233> (0, 'sftp> put /tmp/tmpdO_qD5 /root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863/bigip_partition.py\n', '')
<10.105.174.233> ESTABLISH SSH CONNECTION FOR USER: root
<10.105.174.233> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/5a547716f2 10.105.174.233 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863/ /root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863/bigip_partition.py && sleep 0'"'"''
<10.105.174.233> (0, '', '')
<10.105.174.233> ESTABLISH SSH CONNECTION FOR USER: root
<10.105.174.233> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/5a547716f2 -tt 10.105.174.233 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863/bigip_partition.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1502204912.54-145630385455863/" > /dev/null 2>&1 && sleep 0'"'"''
<10.105.174.233> (0, 'Traceback (most recent call last):\r\n  File "/tmp/ansible_9ARbx4/ansible_module_bigip_partition.py", line 392, in <module>\r\n    main()\r\n  File "/tmp/ansible_9ARbx4/ansible_module_bigip_partition.py", line 378, in main\r\n    f5_product_name=spec.f5_product_name\r\n  File "/tmp/ansible_9ARbx4/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 242, in __init__\r\nNameError: global name \'iControlUnexpectedHTTPError\' is not defined\r\n', 'Shared connection to 10.105.174.233 closed.\r\n')
fatal: [10.105.174.233]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Shared connection to 10.105.174.233 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_9ARbx4/ansible_module_bigip_partition.py\", line 392, in <module>\r\n    main()\r\n  File \"/tmp/ansible_9ARbx4/ansible_module_bigip_partition.py\", line 378, in main\r\n    f5_product_name=spec.f5_product_name\r\n  File \"/tmp/ansible_9ARbx4/ansible_modlib.zip/ansible/module_utils/f5_utils.py\", line 242, in __init__\r\nNameError: global name 'iControlUnexpectedHTTPError' is not defined\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/home/ubuntu/Ansible/CC_Setup.retry

PLAY RECAP ****************************************************************************************************************************************************************
10.105.174.233             : ok=0    changed=0    unreachable=0    failed=1
```

Thank You for your help :)

**Comment by caphrim007** [comment]
I think this is suggesting that one of the following imports is failing

```
    from f5.bigip import ManagementRoot as BigIpMgmt
    from f5.bigip.contexts import TransactionContextManager as BigIpTxContext

    from f5.bigiq import ManagementRoot as BigIqMgmt

    from f5.iworkflow import ManagementRoot as iWorkflowMgmt
    from icontrol.exceptions import iControlUnexpectedHTTPError
```

Can you try copy/pasting those imports above into a `python` interpreter on your device to make sure they are all importable?

**Comment by john3exonets** [comment]
They seem to all work:

```
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from f5.bigip import ManagementRoot as BigIpMgmt
>>> from f5.bigip.contexts import TransactionContextManager as BigIpTxContext
>>> from f5.bigiq import ManagementRoot as BigiqMgmt
>>> from f5.iworkflow import ManagementRoot as iWorkflowMgmt
>>> from icontrol.exceptions import iControlUnexpectedHTTPError
>>>
```

**Comment by caphrim007** [comment]
@john3exonets do you have a file called f5.py on your system?

`locate f5.py`

**Comment by john3exonets** [comment]
```
$ locate f5.py
/usr/lib/python2.7/dist-packages/ansible/utils/module_docs_fragments/f5.py
/usr/lib/python2.7/dist-packages/ansible/utils/module_docs_fragments/f5.pyc
```

**Comment by caphrim007** [comment]
@john3exonets ahh ok, good. delete those 2 files and try again

**Comment by caphrim007** [comment]
@john3exonets hmm. well, neither of those two files should be raising an error.

Are you running Ansible in a virtualenv?

**Comment by john3exonets** [comment]
No....Base Ubuntu.

**Comment by caphrim007** [comment]
@john3exonets lemme create a VM and see

**Comment by caphrim007** [comment]
@john3exonets does your non-mgmt interface have the appropriate acls allowing for remote connections to it? the default is to deny everything.

**Comment by john3exonets** [comment]
Yes it does.....that is how I get to the Admin GUI

**Comment by caphrim007** [comment]
@john3exonets does an upgrade to v2.4.0 of Ansible change anything?

**Comment by john3exonets** [comment]
No Change: Same issue as before:
$ ansible-playbook -i ./hosts CC_Setup.yaml

PLAY [Setup BIGIP for CC4CF Demo]
***************************************************************************************************************

TASK [Setup Partition]
**************************************************************************************************************************
fatal: [10.105.174.233]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 10.105.174.233 closed.\r\n",
"module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_KKnX_K/ansible_module_bigip_partition.py\", line 392, in
<module>\r\n    main()\r\n  File \"/tmp/ansible_KKnX_K/ansible_module_bigip_partition.py\", line 378, in main\r\n
f5_product_name=spec.f5_product_name\r\n  File \"/tmp/ansible_KKnX_K/ansible_modlib.zip/ansible/module_utils/f5_utils.py\", line 239, in
__init__\r\nNameError: global name 'iControlUnexpectedHTTPError' is not defined\r\n", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/home/ubuntu/Ansible/CC_Setup.retry

PLAY RECAP
**************************************************************************************************************************************
10.105.174.233             : ok=0    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment]
@john3exonets if you change to "connection: local" what happens then?

**Comment by john3exonets** [comment]
Hurray!   That seems to work.  No errors, My new partition was on the BIGIP.

$ ansible-playbook -i ./hosts CC_Setup.yaml

PLAY [Setup BIGIP for CC4CF Demo] ***************************************************************************************************************

TASK [Setup Partition] **************************************************************************************************************************
changed: [10.105.174.233]

PLAY RECAP **************************************************************************************************************************************
10.105.174.233             : ok=1    changed=1    unreachable=0    failed=0

**Comment by caphrim007** [comment]
hmm. This should not be happening.

**Comment by caphrim007** [comment]
closing this for now because you've been able to move forward
