### ISSUE TITLE
bigip_license "NameError: global name 'F5ModuleError' is not defined"

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-ansible#415]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_license.py

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /home/snops/cayer-ansible_f5/ansible.cfg
  configured module search path = [u'/home/snops/cayer-ansible_f5/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
```

##### PYTHON VERSION
```
Python 2.7.13
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### CONFIGURATION
```
no change - I did not modify ansible.cfg
```

##### OS / ENVIRONMENT
```
F5 Super NetOps Docker Container

docker run -p 8080:80 -p 2222:22 --rm -it -v /Users/cayer/tmp/user_repos.json:/tmp/user_repos.json -e SNOPS_GH_BRANCH=develop --name f5-snops-eps-lab f5devcentral/f5-super-netops-container:develop-ansible
```

##### SUMMARY
```
I'm running into an issue similar to issue #81, where bigip_license fails. I am trying to use it to install a new base reg key and activate a big-ip, but I haven't been able to figure out how to resolve this issue on my own.
I'm also getting a DEPRECATION WARNING message when I run the playbook...
```

##### STEPS TO REPRODUCE
```
[snops@f5-super-netops] [~/cayer-ansible_f5] $  more roles/onboarding/tasks/main.yml
---
- include: bigip_license/license.yml 
  vars:
    - key: "{{base_key}}"
...
[snops@f5-super-netops] [~/cayer-ansible_f5] $  more roles/onboarding/tasks/bigip_license/license.yml 
---
- name: License BIG-IP, overwrite reg key if necessary
  bigip_license:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    key: "{{ key }}"
    state: "latest"
    validate_certs: "no"
  delegate_to: localhost
...
[snops@f5-super-netops] [~/cayer-ansible_f5] $ 

[snops@f5-super-netops] [~/cayer-ansible_f5] $ ansible-playbook playbooks/onboarding.yml --check --ask-vault-pass -e @password.yml -vvv

```

##### EXPECTED RESULTS
I expected Base Registration Key to be installed and activated on the BIG-IP.

##### ACTUAL RESULTS
```
[snops@f5-super-netops] [~/cayer-ansible_f5] $ ansible-playbook playbooks/onboarding.yml --check --ask-vault-pass -e @password.yml -vvv
ansible-playbook 2.5.0
  config file = /home/snops/cayer-ansible_f5/ansible.cfg
  configured module search path = [u'/home/snops/cayer-ansible_f5/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
Using /home/snops/cayer-ansible_f5/ansible.cfg as config file
Vault password: 
Parsed /home/snops/cayer-ansible_f5/hosts inventory source with ini plugin
**[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic 
inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more 
about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.**
statically imported: /home/snops/cayer-ansible_f5/roles/onboarding/tasks/bigip_license/license.yml

PLAYBOOK: onboarding.yml *****************************************************************************************************************************
1 plays in playbooks/onboarding.yml

PLAY [all] *******************************************************************************************************************************************
META: ran handlers

TASK [onboarding : License BIG-IP, overwrite reg key if necessary] ***********************************************************************************
task path: /home/snops/cayer-ansible_f5/roles/onboarding/tasks/bigip_license/license.yml:2
Using module file /home/snops/cayer-ansible_f5/library/bigip_license.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: snops
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294 `" && echo ansible-tmp-1509672315.07-208641735612294="` echo /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294 `" ) && sleep 0'
<localhost> PUT /tmp/tmpoAbIO0 TO /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/bigip_license.py
<localhost> PUT /tmp/tmpnoxUJG TO /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/args
<localhost> EXEC /bin/sh -c 'chmod u+x /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/ /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/bigip_license.py /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/args && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/bigip_license.py /home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/args; rm -rf "/home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/" > /dev/null 2>&1 && sleep 0'
**The full traceback is:
Traceback (most recent call last):
  File "/home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/bigip_license.py", line 549, in <module>
    main()
  File "/home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/bigip_license.py", line 544, in main
    except F5ModuleError as e:
NameError: global name 'F5ModuleError' is not defined

fatal: [dan_ve -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/bigip_license.py\", line 549, in <module>\n    main()\n  File \"/home/snops/.ansible/tmp/ansible-tmp-1509672315.07-208641735612294/bigip_license.py\", line 544, in main\n    except F5ModuleError as e:\nNameError: global name 'F5ModuleError' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}**

PLAY RECAP *******************************************************************************************************************************************
dan_ve                     : ok=0    changed=0    unreachable=0    failed=1   

[snops@f5-super-netops] [~/cayer-ansible_f5] $ 
```

**Comment by danielcayer** [comment]
Hi Tim, can you invite me to the Slack Channel please?

**Comment by caphrim007** [comment]
@danielcayer sent invite to your work addy

**Comment by caphrim007** [comment]
I conveniently broke this module recently when I was on a mission to fix it up for inclusion in 2.5. You can get an unbroke version here

https://github.com/F5Networks/f5-ansible/blob/369a589c529a90fc5cb477fc13d7aaadaaab6898/library/bigip_license.py

**Comment by danielcayer** [comment]
Thanks Tim! My issue is resolved now. The unbroken version you provided works perfect for me! Will you be updating the repo accordingly?

**Comment by caphrim007** [comment]
@danielcayer this is a development repo so, no. instead, the work will continue to make the license module upstreamable
