### ISSUE TITLE
bigip_license not able to license a new ve ltm

### ISSUE THREAD

**Issue by mleklund** [F5Networks/f5-ansible#46]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_license

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016
```

##### CONFIGURATION
```
retry_files_enabled = False
host_key_checking=False
```
##### OS / ENVIRONMENT
Alpine 3.4 (Docker Container)

##### SUMMARY
undefined global variable issue when attempting to license an unlicensed bigip ltm.

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_W7EbhA/ansible_module_bigip_license.py", line 685, in <module>
    main()
  File "/tmp/ansible_W7EbhA/ansible_module_bigip_license.py", line 651, in main
    if obj.present():
  File "/tmp/ansible_W7EbhA/ansible_module_bigip_license.py", line 586, in present
    if not lic_server and lic_status == 'STATE_DISABLED':
NameError: global name 'lic_status' is not defined

fatal: [hostname.here]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_license"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_W7EbhA/ansible_module_bigip_license.py\", line 685, in <module>\n    main()\n  File \"/tmp/ansible_W7EbhA/ansible_module_bigip_license.py\", line 651, in main\n    if obj.present():\n  File \"/tmp/ansible_W7EbhA/ansible_module_bigip_license.py\", line 586, in present\n    if not lic_server and lic_status == 'STATE_DISABLED':\nNameError: global name 'lic_status' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
```

##### STEPS TO REPRODUCE

```
  - name: Set LTM license
      bigip_license:
        password: "{{ bigip_password }}"
        server: "{{ inventory_hostname }}"
        key: "{{ ltm_license }}"
        state: "present"
        user: "{{ bigip_username }}"
        validate_certs: "{{ validate_certs }}"
```

##### EXPECTED RESULTS
I expected it to license the bigip

##### ACTUAL RESULTS

```
TASK [Set LTM license] *********************************************************
task path: /playbooks/bigip_license.yaml:4
Using module file /playbooks/library/bigip_license.py
<hostname.here> ESTABLISH LOCAL CONNECTION FOR USER: root
<hostname.here> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_W7EbhA/ansible_module_bigip_license.py", line 685, in <module>
    main()
  File "/tmp/ansible_W7EbhA/ansible_module_bigip_license.py", line 651, in main
    if obj.present():
  File "/tmp/ansible_W7EbhA/ansible_module_bigip_license.py", line 586, in present
    if not lic_server and lic_status == 'STATE_DISABLED':
NameError: global name 'lic_status' is not defined

fatal: [hostname.here]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_license"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_W7EbhA/ansible_module_bigip_license.py\", line 685, in <module>\n    main()\n  File \"/tmp/ansible_W7EbhA/ansible_module_bigip_license.py\", line 651, in main\n    if obj.present():\n  File \"/tmp/ansible_W7EbhA/ansible_module_bigip_license.py\", line 586, in present\n    if not lic_server and lic_status == 'STATE_DISABLED':\nNameError: global name 'lic_status' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
	to retry, use: --limit @/playbooks/bigip_network_bootstrap.retry

PLAY RECAP *********************************************************************
hostname.here    : ok=9    changed=1    unreachable=0    failed=1
```

**Comment by caphrim007** [comment]
@mleklund i've pushed an update. can you retry?

**Comment by mleklund** [comment]
looks good to me.
