### ISSUE TITLE
bigip_dns_record not complete

### ISSUE THREAD

**Issue by hanej** [F5Networks/f5-ansible#48]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_dns_record

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       0.0.401
  Edition     Final
  Date        Mon Aug 11 21:08:03 PDT 2014
```

##### OS / ENVIRONMENT

Red Hat 7.2

##### SUMMARY

There are a few objects missing from the module.  Also the documentation in the module doesn't line up with the code.

##### STEPS TO REPRODUCE

On a related note, it seems the module documentation expects the F5 hostname to be the "server" parameter whereas the code expects "hostname".  Same thing with "options: hostname".  The documentation expects to see "options: domain_name".

var_file:
```
f5_dns:
  jhane.myzone:
    f5: 10.1.10.2
    type: A
    view: myview
    zone: myzone.
    ip_address: 10.10.10.10
```

Task:
```
  - name: add dns entry
    bigip_dns_record:
      user: "{{ f5_user }}"
      password: "{{ f5_password }}"
      server: "{{ item.value.f5 }}"
      type: "{{ item.value.type }}"
      view: "{{ item.value.view }}"
      zone: "{{ item.value.zone }}"
      state: "{{ item.value.state | default('present') }}"
      options:
        domain_name: "{{ item.key }}"
        ip_address: "{{ item.value.ip_address }}"
    with_dict: "{{ f5_dns }}"
    delegate_to: localhost
```

##### EXPECTED RESULTS

DNS entry to be created in the zone

##### ACTUAL RESULTS

It seems the BigIpApiFactory object isn't located in this module.

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible__BNVgm/ansible_module_bigip_dns_record.py", line 532, in <module>
    main()
  File "/tmp/ansible__BNVgm/ansible_module_bigip_dns_record.py", line 501, in main
    obj = BigIpApiFactory.factory(module)
NameError: global name 'BigIpApiFactory' is not defined
```

After I copied it from another module it then complained about missing the flush method.

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_PwyWtS/ansible_module_bigip_dns_record.py", line 548, in <module>
    main()
  File "/tmp/ansible_PwyWtS/ansible_module_bigip_dns_record.py", line 518, in main
    result = obj.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

**Comment by caphrim007** [comment]
@hanej I can say with certainty that this module is not complete. I'll work on that and update you along the way

**Comment by caphrim007** [comment]
closing to track in #139
