### ISSUE TITLE
bigip_selfip run results in MODULE FAILURE for floating self IP

### ISSUE THREAD

**Issue by penghon** [F5Networks/f5-ansible#536]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
bigip_selfip

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/ansible/demo2/ansible.cfg
  configured module search path = [u'/home/ansible/demo2/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### PYTHON VERSION

```
[ansible@testbox demo2]$ python -V
Python 2.7.5

```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       0.0.1645
  Edition     Final
  Date        Tue Jan 31 16:59:50 PST 2017

```

##### LIBRARY VERSIONS

```
[ansible@testbox demo2]$ pip freeze | egrep '(f5-sdk|bigsuds)'
bigsuds==1.0.4
f5-sdk==3.0.6

```

##### CONFIGURATION

[ansible@testbox demo2]$ cat ansible.cfg
[defaults]
library = ./library
retry_files_enabled = False
host_key_checking = False
roles_path = ./roles

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Issue similar to closed #420. While the module works for local_traffic_group (or absence of a floating traffic group), MODULE FAILURE occurs for creation of self IP assigned to floating traffic group like traffic-group-1.
The parameter seems to be the issue for floating self IP:
  allow_service: "default"
Remove the above and the playbook works.

##### STEPS TO REPRODUCE

```
***Self IP must not exist before running the task*** 

    - name: Create Floating Self IP on Prod vlan
      bigip_selfip:
        validate_certs: "{{ validate_certs }}"
        user: "{{ vault_username }}"
        password: "{{ vault_password }}"
        server: "{{ ansible_host }}"
        address: "{{ selfip2_3 }}"
        netmask: "{{ netmask }}"
        name: "v1244_floating"
        vlan: "{{ Prod_vlan_name }}"
        allow_service: "default"
        traffic_group: "traffic-group-1"

```

##### EXPECTED RESULTS

Self IP is created regardless of whether traffic_group is specified, allow the specification of "default" for port lockdown/allow_service.
##### ACTUAL RESULTS

```
TASK [Create Floating Self IP on Prod vlan] ***********************************************************************************************
task path: /home/ansible/demo2/playbooks/site.yaml:121
Using module file /home/ansible/demo2/library/bigip_selfip.py
<172.28.77.16> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<172.28.77.16> EXEC /bin/sh -c 'echo ~ && sleep 0'
<172.28.77.16> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1513509031.58-8788806646888 `" && echo ansible-tmp-1513509031.58-8788806646888="` echo /home/ansible/.ansible/tmp/ansible-tmp-1513509031.58-8788806646888 `" ) && sleep 0'
<172.28.77.16> PUT /tmp/tmpzep2sr TO /home/ansible/.ansible/tmp/ansible-tmp-1513509031.58-8788806646888/bigip_selfip.py
<172.28.77.16> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1513509031.58-8788806646888/ /home/ansible/.ansible/tmp/ansible-tmp-1513509031.58-8788806646888/bigip_selfip.py && sleep 0'
<172.28.77.16> EXEC /bin/sh -c '/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1513509031.58-8788806646888/bigip_selfip.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1513509031.58-8788806646888/" > /dev/null 2>&1 && sleep 0'
skipping: [B7200-R78-S18.com] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py", line 795, in <module>
    main()
  File "/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py", line 786, in main
    results = mm.exec_module()
  File "/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py", line 533, in exec_module
    changed = self.present()
  File "/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py", line 548, in present
    changed = self.create()
  File "/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py", line 604, in create
    self.create_on_device()
  File "/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py", line 615, in create_on_device
    **params
  File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 1002, in create
    return self._create(**kwargs)
  File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 968, in _create
    response = session.post(_create_uri, json=kwargs, **requests_params)
  File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 257, in wrapper
    response = method(self, REST_uri, **kwargs)
  File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 512, in post
    return self.session.post(uri, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 458, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set(['default']) is not JSON serializable

fatal: [B7200-R77-S16.com]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py\", line 795, in <module>\n    main()\n  File \"/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py\", line 786, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py\", line 533, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py\", line 548, in present\n    changed = self.create()\n  File \"/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py\", line 604, in create\n    self.create_on_device()\n  File \"/tmp/ansible_a4aULa/ansible_module_bigip_selfip.py\", line 615, in create_on_device\n    **params\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/resource.py\", line 1002, in create\n    return self._create(**kwargs)\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/resource.py\", line 968, in _create\n    response = session.post(_create_uri, json=kwargs, **requests_params)\n  File \"/usr/lib/python2.7/site-packages/icontrol/session.py\", line 257, in wrapper\n    response = method(self, REST_uri, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/icontrol/session.py\", line 512, in post\n    return self.session.post(uri, data=data, json=json, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 555, in post\n    return self.request('POST', url, data=data, json=json, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 494, in request\n    prep = self.prepare_request(req)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 437, in prepare_request\n    hooks=merge_hooks(request.hooks, self.hooks),\n  File \"/usr/lib/python2.7/site-packages/requests/models.py\", line 308, in prepare\n    self.prepare_body(data, files, json)\n  File \"/usr/lib/python2.7/site-packages/requests/models.py\", line 458, in prepare_body\n    body = complexjson.dumps(json)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 243, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib64/python2.7/json/encoder.py\", line 207, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib64/python2.7/json/encoder.py\", line 270, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib64/python2.7/json/encoder.py\", line 184, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: set(['default']) is not JSON serializable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
META: ran handlers
META: ran handlers


```

**Comment by caphrim007** [comment]
@penghon i think this is now fixed.
