### ISSUE TITLE
bigip_software MODULE FAILURE TypeError: __init__() got an unexpected keyword argument 'module'

### ISSUE THREAD

**Issue by penghon** [F5Networks/f5-ansible#603]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_software
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/ansible/lab/ansible.cfg
  configured module search path = [u'/home/ansible/lab/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Product: BIG-IP
Version: 13.0.0
Build: 0.0.1645
Sequence: 13.0.0.0.0.1645.0
BaseBuild: 0.0.1645
Edition: Final
Date: Tue Jan 31 16:59:50 PST 2017
Built: 170131165950
Changelist: 2100458
JobID: 786643
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.9
```

##### CONFIGURATION

defaults]
library = ./library
retry_files_enabled = False
host_key_checking = False
roles_path = ./roles
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Unable to use the bigip_software module to upload images to BIGIP.
##### STEPS TO REPRODUCE

```
- name: Provising lab BIGIPs
  hosts: Test
  gather_facts: no
  connection: local

  vars:
    file: "/home/ansible/BIGIP-13.1.0.0.0.1868.iso"

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "-----"
    F5_PASSWORD: "-----"
    F5_VALIDATE_CERTS: no

  tasks:
    - name: Copying BIGIP software image to target BIGIP
      bigip_software:
        software: "{{ file }}"
        state: present
```

##### EXPECTED RESULTS

ISO file gets uploaded.
##### ACTUAL RESULTS

```
ASK [Copying BIGIP software image to target BIGIP] ***************************************************************************************************************************
task path: /home/ansible/lab/playbooks/testing3.yaml:18
<172.28.28.61> connection transport is rest
<172.28.28.66> connection transport is rest
Using module file /home/ansible/lab/library/bigip_software.py
<172.28.28.61> ESTABLISH LOCAL CONNECTION FOR USER: ansible
Using module file /home/ansible/lab/library/bigip_software.py
<172.28.28.66> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<172.28.28.66> EXEC /bin/sh -c 'echo ~ && sleep 0'
<172.28.28.61> EXEC /bin/sh -c 'echo ~ && sleep 0'
<172.28.28.66> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-157952422221283 `" && echo ansible-tmp-1517470762.05-157952422221283="` echo /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-157952422221283 `" ) && sleep 0'
<172.28.28.61> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-35831314210070 `" && echo ansible-tmp-1517470762.05-35831314210070="` echo /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-35831314210070 `" ) && sleep 0'
<172.28.28.66> PUT /home/ansible/.ansible/tmp/ansible-local-1609upqhva/tmpHrdZfD TO /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-157952422221283/bigip_software.py
<172.28.28.66> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-157952422221283/ /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-157952422221283/bigip_software.py && sleep 0'
<172.28.28.61> PUT /home/ansible/.ansible/tmp/ansible-local-1609upqhva/tmpLl7S1O TO /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-35831314210070/bigip_software.py
<172.28.28.61> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-35831314210070/ /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-35831314210070/bigip_software.py && sleep 0'
<172.28.28.66> EXEC /bin/sh -c 'F5_VALIDATE_CERTS=False F5_SERVER=172.28.28.66 F5_USER=admin F5_PASSWORD=admin /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-157952422221283/bigip_software.py && sleep 0'
<172.28.28.61> EXEC /bin/sh -c 'F5_VALIDATE_CERTS=False F5_SERVER=172.28.28.61 F5_USER=admin F5_PASSWORD=admin /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1517470762.05-35831314210070/bigip_software.py && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_SgoMRZ/ansible_module_bigip_software.py", line 1315, in <module>
    main()
  File "/tmp/ansible_SgoMRZ/ansible_module_bigip_software.py", line 1305, in main
    mm = ModuleManager(module=module, client=client)
TypeError: __init__() got an unexpected keyword argument 'module'
fatal: [test1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_SgoMRZ/ansible_module_bigip_software.py\", line 1315, in <module>\n    main()\n  File \"/tmp/ansible_SgoMRZ/ansible_module_bigip_software.py\", line 1305, in main\n    mm = ModuleManager(module=module, client=client)\nTypeError: __init__() got an unexpected keyword argument 'module'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ojUjUG/ansible_module_bigip_software.py", line 1315, in <module>
    main()
  File "/tmp/ansible_ojUjUG/ansible_module_bigip_software.py", line 1305, in main
    mm = ModuleManager(module=module, client=client)
TypeError: __init__() got an unexpected keyword argument 'module'
fatal: [test2]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ojUjUG/ansible_module_bigip_software.py\", line 1315, in <module>\n    main()\n  File \"/tmp/ansible_ojUjUG/ansible_module_bigip_software.py\", line 1305, in main\n    mm = ModuleManager(module=module, client=client)\nTypeError: __init__() got an unexpected keyword argument 'module'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by ArtiomL** [comment]
+1

**Comment by caphrim007** [comment]
at this time this error is expected. This module needs a rewrite

**Comment by penghon** [comment]
Thanks @caphrim007 for the confirmation

**Comment by adolphsons** [comment]
Any updates on the module re-write? I could really use this.

**Comment by caphrim007** [comment]
@adolphsons we're in the process of re-working it.

**Comment by neozoolook** [comment]
@caphrim007 @adolphsons I will add this to our master tracker as we want to leverage this module to support upgrades and patching on F5.

**Comment by caphrim007** [comment]
closing as this new module work is being tracked in #828
