### ISSUE TITLE
Attribute Error when creating a pool

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#612]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_pool

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016
```

##### LIBRARY VERSIONS

```
urllib3==1.22
bigsuds==1.0.6
f5-icontrol-rest==1.3.5
f5-sdk==3.0.10
netaddr==0.7.19
```

##### OS / ENVIRONMENT

Redhat
##### SUMMARY

When trying to create a pool I always get a module failure. I can create nodes and VIPs with no issues though. 

##### STEPS TO REPRODUCE

```
---

- name: Create a pool
  hosts: F5_Lab
  connection: local

  tasks:
      - name: Create a pool1
        bigip_pool:
           server: "f5test.example.com"
           user: "admin"
           password: "admin"
           name: "ansible_test_pool1"
           lb_method: "ratio_member"
           validate_certs: "false"
        delegate_to: localhost
        
```

##### EXPECTED RESULTS

Expected the pool to be created with no nodes. 

##### ACTUAL RESULTS

From what I can tell from the output below, a AttributeError causing a module failure.

```
TASK [Create a pool1] ********************************************************************************************************************************************************************
task path: /home/username/f5pool.yaml:8
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1518109597.85-247802715458084 `" && echo ansible-tmp-1518109597.85-247802715458084="` echo /root/.ansible/tmp/ansible-tmp-1518109597.85-247802715458084 `" ) && sleep 0'
<localhost> PUT /tmp/tmpfqYNyG TO /root/.ansible/tmp/ansible-tmp-1518109597.85-247802715458084/bigip_pool.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1518109597.85-247802715458084/ /root/.ansible/tmp/ansible-tmp-1518109597.85-247802715458084/bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1518109597.85-247802715458084/bigip_pool.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1518109597.85-247802715458084/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zD1_6u/ansible_module_bigip_pool.py", line 738, in <module>
    main()
  File "/tmp/ansible_zD1_6u/ansible_module_bigip_pool.py", line 726, in main
    f5_product_name=spec.f5_product_name
  File "/tmp/ansible_zD1_6u/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 237, in __init__
  File "/tmp/ansible_zD1_6u/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 262, in _get_mgmt_root
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 155, in __init__
    hostname, username, password, **kwargs
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 57, in __init__
    self.icrs = self._get_icr_session(**self.args)
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 91, in _get_icr_session
    result = iControlRESTSession(**params)
  File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 391, in __init__
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'urllib3'
fatal: [f5test.example.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_zD1_6u/ansible_module_bigip_pool.py\", line 738, in <module>\n    main()\n  File \"/tmp/ansible_zD1_6u/ansible_module_bigip_pool.py\", line 726, in main\n    f5_product_name=spec.f5_product_name\n  File \"/tmp/ansible_zD1_6u/ansible_modlib.zip/ansible/module_utils/f5_utils.py\", line 237, in __init__\n  File \"/tmp/ansible_zD1_6u/ansible_modlib.zip/ansible/module_utils/f5_utils.py\", line 262, in _get_mgmt_root\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 155, in __init__\n    hostname, username, password, **kwargs\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 57, in __init__\n    self.icrs = self._get_icr_session(**self.args)\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 91, in _get_icr_session\n    result = iControlRESTSession(**params)\n  File \"/usr/lib/python2.7/site-packages/icontrol/session.py\", line 391, in __init__\n    requests.packages.urllib3.disable_warnings()\nAttributeError: 'module' object has no attribute 'urllib3'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
        to retry, use: --limit @/home/username/f5pool.retry
```

**Comment by caphrim007** [comment]
@DerrickTJ that looks like an f5-sdk error. what version of python `requests` do you have?

**Comment by DerrickTJ** [comment]
requests==2.18.4

**Comment by caphrim007** [comment]
@DerrickTJ how about `pyOpenSSL`?

**Comment by DerrickTJ** [comment]
pyOpenSSL==17.5.0

**Comment by DerrickTJ** [comment]
If it makes any difference, I tested it against Python 3.4 as well and get a different error. All the libraries are running the same versions just like 2.7.

TypeError: the JSON object must be str, not 'bytes'

```
TASK [Create a pool1] ********************************************************************************************************************************************************************
task path: /home/username/f5pool.yaml:8
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1518115420.4-47168968885665 `" && echo ansible-tmp-1518115420.4-47168968885665="` echo /root/.ansible/tmp/ansible-tmp-1518115420.4-47168968885665 `" ) && sleep 0'
<localhost> PUT /tmp/tmpeaX8Pu TO /root/.ansible/tmp/ansible-tmp-1518115420.4-47168968885665/bigip_pool.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1518115420.4-47168968885665/ /root/.ansible/tmp/ansible-tmp-1518115420.4-47168968885665/bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.4 /root/.ansible/tmp/ansible-tmp-1518115420.4-47168968885665/bigip_pool.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1518115420.4-47168968885665/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py", line 738, in <module>
    main()
  File "/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py", line 731, in main
    results = mm.exec_module()
  File "/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py", line 450, in exec_module
    changed = self.present()
  File "/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py", line 512, in present
    return self.create()
  File "/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py", line 549, in create
    self.create_on_device()
  File "/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py", line 559, in create_on_device
    partition=self.want.partition, **params
  File "/usr/lib/python3.4/site-packages/f5/bigip/tm/ltm/pool.py", line 73, in create
    return super(Pool, self)._create(**kwargs)
  File "/usr/lib/python3.4/site-packages/f5/bigip/resource.py", line 970, in _create
    response = session.post(_create_uri, json=kwargs, **requests_params)
  File "/usr/lib/python3.4/site-packages/icontrol/session.py", line 263, in wrapper
    response = method(self, REST_uri, **kwargs)
  File "/usr/lib/python3.4/site-packages/icontrol/session.py", line 541, in post
    self._debug.append(debug_prepared_request(prepared))
  File "/usr/lib/python3.4/site-packages/icontrol/session.py", line 614, in debug_prepared_request
    kwargs = json.loads(request.body)
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
fatal: [f5test.example.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py\", line 738, in <module>\n    main()\n  File \"/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py\", line 731, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py\", line 450, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py\", line 512, in present\n    return self.create()\n  File \"/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py\", line 549, in create\n    self.create_on_device()\n  File \"/tmp/ansible_puxvrco0/ansible_module_bigip_pool.py\", line 559, in create_on_device\n    partition=self.want.partition, **params\n  File \"/usr/lib/python3.4/site-packages/f5/bigip/tm/ltm/pool.py\", line 73, in create\n    return super(Pool, self)._create(**kwargs)\n  File \"/usr/lib/python3.4/site-packages/f5/bigip/resource.py\", line 970, in _create\n    response = session.post(_create_uri, json=kwargs, **requests_params)\n  File \"/usr/lib/python3.4/site-packages/icontrol/session.py\", line 263, in wrapper\n    response = method(self, REST_uri, **kwargs)\n  File \"/usr/lib/python3.4/site-packages/icontrol/session.py\", line 541, in post\n    self._debug.append(debug_prepared_request(prepared))\n  File \"/usr/lib/python3.4/site-packages/icontrol/session.py\", line 614, in debug_prepared_request\n    kwargs = json.loads(request.body)\n  File \"/usr/lib64/python3.4/json/__init__.py\", line 312, in loads\n    s.__class__.__name__))\nTypeError: the JSON object must be str, not 'bytes'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
        to retry, use: --limit @/username/f5pool.retry
```

**Comment by caphrim007** [comment]
@DerrickTJ can you put this in a python interpreter and tell me if either of them fail? I seem to have the same library versions that you do (and i dont see the error) but there may be a workaround if one of these blobs works.

```
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

or

```
import requests
requests.packages.urllib3.disable_warnings()
```

Try both and tell me one way or another what happens when you run them. Ideally they both pass, but if one fails, then I at least have a proposed workaround

**Comment by DerrickTJ** [comment]
```
>>> import urllib3
>>> urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
>>> 
>>> import requests
>>> requests.packages.urllib3.disable_warnings()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'urllib3'
```

**Comment by caphrim007** [comment]
ok, if the first one works, then i need to do a little bit of a switch-a-roo on the f5-sdk. one second

**Comment by DerrickTJ** [comment]
Thank you :)

**Comment by caphrim007** [comment]
@DerrickTJ try doing this.

`pip install --upgrade https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0`

And lemme know if you see any change in behavior

**Comment by DerrickTJ** [comment]
error 404 Client Error: Not Found for url

**Comment by caphrim007** [comment]
oh yeah i forgot the git part

`pip install --upgrade git+https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0`

**Comment by DerrickTJ** [comment]
Looks like I still got the same error.

```
TASK [Create a pool1] ********************************************************************************************************************************************************************
task path: /home/username/f5pool.yaml:8
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1518121638.27-169767146199878 `" && echo ansible-tmp-1518121638.27-169767146199878="` echo /root/.ansible/tmp/ansible-tmp-1518121638.27-169767146199878 `" ) && sleep 0'
<localhost> PUT /tmp/tmplJIcK2 TO /root/.ansible/tmp/ansible-tmp-1518121638.27-169767146199878/bigip_pool.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1518121638.27-169767146199878/ /root/.ansible/tmp/ansible-tmp-1518121638.27-169767146199878/bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1518121638.27-169767146199878/bigip_pool.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1518121638.27-169767146199878/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_FKYwOm/ansible_module_bigip_pool.py", line 738, in <module>
    main()
  File "/tmp/ansible_FKYwOm/ansible_module_bigip_pool.py", line 726, in main
    f5_product_name=spec.f5_product_name
  File "/tmp/ansible_FKYwOm/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 237, in __init__
  File "/tmp/ansible_FKYwOm/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 262, in _get_mgmt_root
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 155, in __init__
    hostname, username, password, **kwargs
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 57, in __init__
    self.icrs = self._get_icr_session(**self.args)
  File "/usr/lib/python2.7/site-packages/f5/bigip/__init__.py", line 91, in _get_icr_session
    result = iControlRESTSession(**params)
  File "/usr/lib/python2.7/site-packages/icontrol/session.py", line 391, in __init__
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'urllib3'
fatal: [f5test.example.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_FKYwOm/ansible_module_bigip_pool.py\", line 738, in <module>\n    main()\n  File \"/tmp/ansible_FKYwOm/ansible_module_bigip_pool.py\", line 726, in main\n    f5_product_name=spec.f5_product_name\n  File \"/tmp/ansible_FKYwOm/ansible_modlib.zip/ansible/module_utils/f5_utils.py\", line 237, in __init__\n  File \"/tmp/ansible_FKYwOm/ansible_modlib.zip/ansible/module_utils/f5_utils.py\", line 262, in _get_mgmt_root\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 155, in __init__\n    hostname, username, password, **kwargs\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 57, in __init__\n    self.icrs = self._get_icr_session(**self.args)\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/__init__.py\", line 91, in _get_icr_session\n    result = iControlRESTSession(**params)\n  File \"/usr/lib/python2.7/site-packages/icontrol/session.py\", line 391, in __init__\n    requests.packages.urllib3.disable_warnings()\nAttributeError: 'module' object has no attribute 'urllib3'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
        to retry, use: --limit @/home/username/f5pool.retry
```

**Comment by caphrim007** [comment]
umm, you've got something amiss. because there is no code like that on line 391 (as mentioned in the error).

What is the checksum of your icontrol/session.py file?

are you running this in a virtualenv?

**Comment by caphrim007** [comment]
md5 of this file `/usr/lib/python2.7/site-packages/icontrol/session.py` is what i mean

**Comment by DerrickTJ** [comment]
93555ec85b0e2d78fcbfae1901b7e4bf  session.py

I do not believe I'm using a virtual environment for this. Just running it from the terminal on redhat. I'm not linux savvy enough to figure out virtual environments.

**Comment by caphrim007** [comment]
ok, you have the wrong file in place. for some reason....

can you pip uninstall that f5-icontrol-rest library first and then install the github one?

**Comment by DerrickTJ** [comment]
I ended up with the same MD5 hash lol

```
[root@ansible icontrol]# cd ~
[root@ansible ~]# pip uninstall f5-icontrol-rest
Uninstalling f5-icontrol-rest-1.3.5:
  /usr/lib/python3.4/site-packages/f5_icontrol_rest-1.3.5-py3.4.egg-info
  /usr/lib/python3.4/site-packages/icontrol/__init__.py
  /usr/lib/python3.4/site-packages/icontrol/__pycache__/__init__.cpython-34.pyc
  /usr/lib/python3.4/site-packages/icontrol/__pycache__/authtoken.cpython-34.pyc
  /usr/lib/python3.4/site-packages/icontrol/__pycache__/exceptions.cpython-34.pyc
  /usr/lib/python3.4/site-packages/icontrol/__pycache__/session.cpython-34.pyc
  /usr/lib/python3.4/site-packages/icontrol/authtoken.py
  /usr/lib/python3.4/site-packages/icontrol/exceptions.py
  /usr/lib/python3.4/site-packages/icontrol/session.py
Proceed (y/n)? y
  Successfully uninstalled f5-icontrol-rest-1.3.5
[root@ansible ~]# pip install --upgrade git+https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0
Collecting git+https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0
  Cloning https://github.com/F5Networks/f5-icontrol-rest-python.git (to 1.0) to /tmp/pip-spfh_500-build
Requirement already up-to-date: requests<3,>=2.5.0 in /usr/lib/python3.4/site-packages (from f5-icontrol-rest==1.3.5)
Requirement already up-to-date: urllib3 in /usr/lib/python3.4/site-packages (from f5-icontrol-rest==1.3.5)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/lib/python3.4/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest==1.3.5)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/lib/python3.4/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest==1.3.5)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.4/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest==1.3.5)
Installing collected packages: f5-icontrol-rest
  Running setup.py install for f5-icontrol-rest ... done
Successfully installed f5-icontrol-rest-1.3.5
[root@ansible ~]# cd ..
[root@ansible /]# cd /usr/lib/python2.7/site-packages/icontrol/
[root@ansible icontrol]# ls
authtoken.py  authtoken.pyc  exceptions.py  exceptions.pyc  __init__.py  __init__.pyc  session.py  session.pyc
[root@ansible icontrol]# md5sum session.py
93555ec85b0e2d78fcbfae1901b7e4bf  session.py
```

**Comment by caphrim007** [comment]
maybe we have the @ syntax wrong. lemme look

**Comment by caphrim007** [comment]
@DerrickTJ in your OP, you mentioned you were running "Python 2.7.5" but the above output shows you removing it from python 3.4

which one is it?

**Comment by DerrickTJ** [comment]
I found that odd as well. I don't quite understand what is happening because if I want to do anything with version 3 I have to do python3 or pip3. pip should just be doing everything with python 2 was my thought.

**Comment by DerrickTJ** [comment]
I went into this planning on only looking at python2.

**Comment by caphrim007** [comment]
do the pip install from github by try using pip3 instead.

**Comment by DerrickTJ** [comment]
```
[root@ansible ~]# pip3 install --upgrade git+https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0
Collecting git+https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0
  Cloning https://github.com/F5Networks/f5-icontrol-rest-python.git (to 1.0) to /tmp/pip-ghc3icv9-build
Requirement already up-to-date: requests<3,>=2.5.0 in /usr/lib/python3.4/site-packages (from f5-icontrol-rest==1.3.5)
Requirement already up-to-date: urllib3 in /usr/lib/python3.4/site-packages (from f5-icontrol-rest==1.3.5)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.4/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest==1.3.5)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/lib/python3.4/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest==1.3.5)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/lib/python3.4/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest==1.3.5)
Installing collected packages: f5-icontrol-rest
  Found existing installation: f5-icontrol-rest 1.3.5
    Uninstalling f5-icontrol-rest-1.3.5:
      Successfully uninstalled f5-icontrol-rest-1.3.5
  Running setup.py install for f5-icontrol-rest ... done
Successfully installed f5-icontrol-rest-1.3.5
```

**Comment by caphrim007** [comment]
hash the file that is at /usr/lib/python3.4/site-packages/icontrol/session.py

**Comment by DerrickTJ** [comment]
Same
```
[root@ansible icontrol]# md5sum session.py
93555ec85b0e2d78fcbfae1901b7e4bf  session.py
```

**Comment by DerrickTJ** [comment]
[root@ansible /]# md5sum /usr/lib/python3.4/site-packages/icontrol/session.py
5146f5e71a32eb5e91e5101ed81d0756  /usr/lib/python3.4/site-packages/icontrol/session.py

**Comment by caphrim007** [comment]
514 is the correct hash. what happened?

**Comment by DerrickTJ** [comment]
Looks like python3.4 is the only one taking the update and pip isn't installing to python2 for some reason.

**Comment by caphrim007** [comment]
is the pip command aliased to pip3?

**Comment by DerrickTJ** [comment]
How do I check that?

**Comment by caphrim007** [comment]
"ls -l `which pip`"

**Comment by DerrickTJ** [comment]
My linux ignorance is really going to shine here ... lol

`[root@ansible /]# ls -l which pip
ls: cannot access which: No such file or directory
ls: cannot access pip: No such file or directory`

**Comment by caphrim007** [comment]
put backticks around the "which pip"

**Comment by DerrickTJ** [comment]
`[root@ansible /]# ls -l "which pip"
ls: cannot access which pip: No such file or directory`

**Comment by caphrim007** [comment]
```
ls -l `which pip`
```

like i have above

**Comment by DerrickTJ** [comment]
derp...

`[root@ansible /]# ls -l `which pip`
-rwxr-x---. 1 root root 284 Feb  6 08:14 /bin/pip`

`[root@ansible /]# ls -l `which pip3`
-rwxr-x---. 1 root root 286 Feb  6 08:14 /bin/pip3`

**Comment by caphrim007** [comment]
well, that seems fine. It would look like this if it was an alias

```
-rwxr-x---. 1 root root 284 Feb 6 08:14 pip -> /bin/pip3
```

**Comment by caphrim007** [comment]
what does this output? 2.7.5?

`python -V`

**Comment by DerrickTJ** [comment]
`[root@ansible /]# python -V
Python 2.7.5
[root@ansible /]# python3 -V
Python 3.4.5`

**Comment by caphrim007** [comment]
well, I guess a possible solution would be to set the ansible_python_interpreter to the location of python3.

what is the output of `which python3` ?

**Comment by DerrickTJ** [comment]
LOL I just did that and it worked. Was typing that up.

**Comment by DerrickTJ** [comment]
Before, python3 was erroring out with the JSON bytes error. Now it is working in python 3.

:)

**Comment by caphrim007** [comment]
fancy that. can you post your output where you see a success?

**Comment by caphrim007** [comment]
or at least a blurb of it. i dont need the whole thing, just a snippet for future readers to reference

**Comment by DerrickTJ** [comment]
`TASK [Create a pool1] ********************************************************************************************************************************************************************
task path: /home/username/f5pool.yaml:8
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1518124109.44-176930455748882 `" && echo ansible-tmp-1518124109.44-176930455748882="` echo /root/.ansible/tmp/ansible-tmp-1518124109.44-176930455748882 `" ) && sleep 0'
<localhost> PUT /tmp/tmpAJMjO6 TO /root/.ansible/tmp/ansible-tmp-1518124109.44-176930455748882/bigip_pool.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1518124109.44-176930455748882/ /root/.ansible/tmp/ansible-tmp-1518124109.44-176930455748882/bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.4 /root/.ansible/tmp/ansible-tmp-1518124109.44-176930455748882/bigip_pool.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1518124109.44-176930455748882/" > /dev/null 2>&1 && sleep 0'
ok: [f5test.example.com -> localhost] => {
    "changed": false, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "description": null, 
            "host": null, 
            "lb_method": "ratio-member", 
            "monitor_type": null, 
            "monitors": null, 
            "name": "ansible_test_pool1", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": "f5test.example.com", 
            "server_port": 443, 
            "service_down_action": null, 
            "slow_ramp_time": null, 
            "state": "present", 
            "user": "admin", 
            "validate_certs": false
        }
    }, 
    "partition": "Common"
}
META: ran handlers
META: ran handlers`

**Comment by DerrickTJ** [comment]
`TASK [Create a pool1] ********************************************************************************************************************************************************************
changed: [f5test.example.com -> localhost]

PLAY RECAP *******************************************************************************************************************************************************************************
f5test.example.com.com     : ok=2    changed=1    unreachable=0    failed=0`

**Comment by caphrim007** [comment]
awesome. thanks @DerrickTJ. you're all ok now? that bugfix will be released as part of the official icontrol rest package next friday (next week)

**Comment by DerrickTJ** [comment]
Yep! Thanks for the help!!
