### ISSUE TITLE
Issue：bigip_license.py --- Generate a new BIG IP VE license report error.

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/f5-ansible#619]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

bigip_license.py
##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### PYTHON VERSION

```
Python 2.7.14
```

##### BIGIP VERSION

```
 Version     12.1.3
  Build       0.0.378
  Edition     Final

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.10
```

##### ISSUE
```
I hope that through the playbook file to activate a new  BIG-IP system( BIGIP VE at Vsphere platform ).
I only configured the BIGIP VE 's management interface ip and management interface gateway at BIGIP-VE.I test BIGIP-VE management interface can ping the my ansible.But I  run the playbook  display error.
```

##### Ansible hosts file
```
[bigip-a:vars]
#bigip_license_key=xxxx
bigip_username="admin"
bigip_password="admin"
bigip_port=443
validate_certs="no"
ansible_host=localhost
```
##### Ansible Play booke file -- active_license.yaml 
```
---

- name:  Generate a new BIG IP VE license
  hosts: bigip-a
  connection: local
 
  vars:
      bigip_license: "xxxx"

  tasks:
      - name: License a BIG-IP
        bigip_license:
            password: "{{ bigip_password }}"
            server: "{{ ansible_host }}"
            server_port: "{{ bigip_port }}"
            user: "{{ bigip_username }}"
            key: "{{ bigip_license }}"
            validate_certs: "{{ validate_certs }}"
        delegate_to: localhost
```

##### Error Information
```
[root@localhost ansible]# ansible-playbook active_license.yaml -vvv
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/library']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: active_license.yaml ***********************************************************************************************************************************************************************************************
1 plays in active_license.yaml

PLAY [Create a VIP, pool, pool members and nodes] ***************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.6/site-packages/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1518402129.77-30440903839214 `" && echo ansible-tmp-1518402129.77-30440903839214="` echo /root/.ansible/tmp/ansible-tmp-1518402129.77-30440903839214 `" ) && sleep 0'
<localhost> PUT /tmp/tmpxlBgDn TO /root/.ansible/tmp/ansible-tmp-1518402129.77-30440903839214/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1518402129.77-30440903839214/ /root/.ansible/tmp/ansible-tmp-1518402129.77-30440903839214/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1518402129.77-30440903839214/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1518402129.77-30440903839214/" > /dev/null 2>&1 && sleep 0'
ok: [192.168.0.170]
META: ran handlers

TASK [License a BIG-IP] *****************************************************************************************************************************************************************************************************
task path: /etc/ansible/active_license.yaml:11
Using module file /etc/ansible/library/bigip_license.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637 `" && echo ansible-tmp-1518402130.49-71967144075637="` echo /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637 `" ) && sleep 0'
<localhost> PUT /tmp/tmpxlBgDn TO /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/bigip_license.py
<localhost> PUT /tmp/tmp7jQOI5 TO /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/args
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/ /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/bigip_license.py /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/args && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2.6 /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/bigip_license.py /root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/args; rm -rf "/root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/bigip_license.py", line 515, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/bigip_license.py", line 510, in main
    except F5ModuleError as e:
NameError: global name 'F5ModuleError' is not defined

fatal: [192.168.0.170 -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/bigip_license.py\", line 515, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1518402130.49-71967144075637/bigip_license.py\", line 510, in main\n    except F5ModuleError as e:\nNameError: global name 'F5ModuleError' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************
192.168.0.170              : ok=1    changed=0    unreachable=0    failed=1   

[root@localhost ansible]# 

```

**Comment by caphrim007** [comment]
@lilongabc this is expected. bigip_license is not complete yet

**Comment by lilongabc** [comment]
@caphrim007  I got it， When is it possible to finish it?  Thanks

**Comment by caphrim007** [comment]
i have no eta for it.

**Comment by caphrim007** [comment]
but i should also add that someone is working on it

**Comment by lilongabc** [comment]
@caphrim007  ok：）
