### ISSUE TITLE
gather facts from Bigip Facts is not working 

### ISSUE THREAD

**Issue by santiagocs1** [F5Networks/f5-ansible#674]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_facts
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ssanjurjo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017

Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       5.0.429
  Edition     Hotfix HF5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.9
```

##### OS / ENVIRONMENT

Centos
##### SUMMARY

bigip_facts is not working, We are using F5 with VCMP in some of the Guest is working but in most of them not. 
##### STEPS TO REPRODUCE

```
ansible-playbook F5_GET_FACTS.yml --extra-vars "F5_SERVER=XXXXX user=XXXXX password=XXXXX" -vvvv

```

##### EXPECTED RESULTS

Facts would be gathered
##### ACTUAL RESULTS

```
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ssanjurjo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: F5_GET_FACTS.yml **********************************************************************************************************************************************
1 plays in F5_GET_FACTS.yml

PLAY [F5 Get Facts] *****************************************************************************************************************************************************
META: ran handlers

TASK [Collect BIG-IP facts] *********************************************************************************************************************************************
task path: /home/ssanjurjo/test_ansible/F5_GET_FACTS.yml:8
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_facts.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ssanjurjo
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ssanjurjo/.ansible/tmp/ansible-tmp-1521568246.59-211678062153352 `" && echo ansible-tmp-1521568246.59-211678062153352="` echo /home/ssanjurjo/.ansible/tmp/ansible-tmp-1521568246.59-211678062153352 `" ) && sleep 0'
<localhost> PUT /tmp/tmpoOw1jD TO /home/ssanjurjo/.ansible/tmp/ansible-tmp-1521568246.59-211678062153352/bigip_facts.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ssanjurjo/.ansible/tmp/ansible-tmp-1521568246.59-211678062153352/ /home/ssanjurjo/.ansible/tmp/ansible-tmp-1521568246.59-211678062153352/bigip_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/ssanjurjo/.ansible/tmp/ansible-tmp-1521568246.59-211678062153352/bigip_facts.py; rm -rf "/home/ssanjurjo/.ansible/tmp/ansible-tmp-1521568246.59-211678062153352/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_1sq5G3/ansible_module_bigip_facts.py", line 1666, in main
    saved_active_folder = f5.get_active_folder()
  File "/tmp/ansible_1sq5G3/ansible_module_bigip_facts.py", line 148, in get_active_folder
    return self.api.System.Session.get_active_folder()
  File "/usr/lib/python2.7/site-packages/bigsuds.py", line 379, in __getattr__
    client = self._client_creator('%s.%s' % (self._name, attr))
  File "/usr/lib/python2.7/site-packages/bigsuds.py", line 189, in _create_client

fatal: [XXXX -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "filter": null, 
            "include": [
                "device", 
                "device_group"
            ], 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server": "XXXX", 
            "server_port": 443, 
            "session": false, 
            "state": "present", 
            "user": "XXXX", 
            "validate_certs": false
        }
    }, 

  "msg": "received exception: <urlopen error [Errno -2] Name or service not known>\ntraceback: 
Traceback (most recent call last):\n  File \"/tmp/ansible_1sq5G3/ansible_module_bigip_facts.py\",
 line 1666, in main\n    saved_active_folder = f5.get_active_folder()\n  File 
\"/tmp/ansible_1sq5G3/ansible_module_bigip_facts.py\", line 148, in get_active_folder\n    return 
self.api.System.Session.get_active_folder()\n  File \"/usr/lib/python2.7/site-packages/bigsuds.py\", 
line 379, in __getattr__\n    client = self._client_creator('%s.%s' % (self._name, attr))\n  File 
\"/usr/lib/python2.7/site-packages/bigsuds.py\", line 189, in _create_client\n    raise 
ConnectionError(str(e))\nConnectionError: <urlopen error [Errno -2] Name or service not known>\n"
}

Playbook:

---

- name: F5 Get Facts
  hosts: "{{ F5_SERVER }}" 
  gather_facts: no
  tasks:
   - name: Collect BIG-IP facts
     bigip_facts:
      server: "{{ F5_SERVER }}"
      user: "{{ user }}"
      password: "{{ password }}"
      include: "device,device_group"
      validate_certs: "False"
     register: show
     delegate_to: localhost
     
   - debug: var=show
```

**Comment by caphrim007** [comment]
@santiagocs1 this error suggests that the login information you are providing is incorrect.

What is likely happening is your `hosts:` line is not being interpreted as an actual host by ansible, and is instead being interpreted as a plain string.

Is the value that you are assigning to F5_SERVER an IP address? FQDN? resolvable in DNS?

**Comment by caphrim007** [comment]
For example, when I run the following

```
ansible-playbook -i inventory/hosts test.yaml -e "F5_SERVER=f5-test[0] user=admin password=admin"
```

The `server` value received by the module is `f5-test[0]`. Ansible did no interpolation of the value, it just sent it straight to the playbook.

**Comment by santiagocs1** [comment]
Hello,

Thanks for your answer it is working now, like F5_SERVER value i was using a string defined in the /etc/ansible/hosts like:
F5-1 ansible_host=7.7.77

and then " F5_SERVER=F5-1"
when i configured this value also in the /etc/hosts it worked.. Many thanks for your help
