### ISSUE TITLE
bigip_gtm_pool_member on 11.6.2

### ISSUE THREAD

**Issue by rowco** [F5Networks/f5-ansible#698]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_gtm_pool_member

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /home/isxrc/ansible/ansible.cfg
  configured module search path = [u'/home/isxrc/ansible/f5-ansible/library/modules']
  ansible python module location = /home/isxrc/venv/lib/python2.7/site-packages/ansible
  executable location = /home/isxrc/venv/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### PYTHON VERSION

```
Python 2.7.5
sl
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.2
  Build       1.0.507
  Edition     Hotfix HF1
  Date        Mon Nov 13 18:40:11 PST 2017

Hotfix List
ID694058      ID693211-4

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.14

```

##### CONFIGURATION

library = ./f5-ansible/library/modules
module_utils = ./f5-ansible/library/module_utils
action_plugins = ./f5-ansible/library/plugins/action
network_group_modules = bigip, bigiq

##### SUMMARY

Unable to add gtm pool members on earlier versions of bigip (works 12.1.2)

##### STEPS TO REPRODUCE

```
- name: Add members to pool
  bigip_gtm_pool_member:
    pool: "{{ pool.name }}"
    virtual_server: "{{ member.vs }}"
    server_name: "{{ member.server }}"
    member_order: "{{ member.order }}"
    type: "a"
  delegate_to: localhost

```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py", line 681, in <module>
    main()
  File "/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py", line 672, in main
    results = mm.exec_module()
  File "/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py", line 481, in exec_module
    changed = self.present()
  File "/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py", line 503, in present
    if self.exists():
  File "/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py", line 510, in exists
    collection = getattr(pools, self.want.collection)
  File "/home/isxrc/venv/lib/python2.7/site-packages/f5/bigip/mixins.py", line 102, in __getattr__
    raise AttributeError(error_message)
AttributeError: '<class 'f5.bigip.tm.gtm.pool.Pools'>' object has no attribute 'a_s'

fatal: [f5-demo-vip.netcomms -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py\", line 681, in <module>\n    main()\n  File \"/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py\", line 672, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py\", line 481, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py\", line 503, in present\n    if self.exists():\n  File \"/tmp/ansible_TnbavQ/ansible_module_bigip_gtm_pool_member.py\", line 510, in exists\n    collection = getattr(pools, self.want.collection)\n  File \"/home/isxrc/venv/lib/python2.7/site-packages/f5/bigip/mixins.py\", line 102, in __getattr__\n    raise AttributeError(error_message)\nAttributeError: '<class 'f5.bigip.tm.gtm.pool.Pools'>' object has no attribute 'a_s'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

**Comment by caphrim007** [comment]
@rowco the F5 Ansible modules require BIG-IP >= 12.0.0. In the event that anything works on less than 12, it was by chance. This is not one of those cases.

**Comment by caphrim007** [comment]
@rowco for cases where 11.x is still in use, but needs Ansible automation, the recommendation is to use `bigip_command`.

**Comment by rowco** [comment]
@caphrim007 that'll explain it. For info, everything I've done so far with these modules I've run on both 12.1+ and 11.6+, this is the first time I've found something that works on one and not on the other :(
