### ISSUE TITLE
bigip_software BigIpCommon#iso_info does not return result

### ISSUE THREAD

**Issue by festango** [F5Networks/f5-ansible#8]
Line 571 of bigip_software.py does not return result to collar that causes failure installtion. Adding 'return result' to the function seem to fix the issue.

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1457994186.08-15355698835389/bigip_software", line 2827, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1457994186.08-15355698835389/bigip_software", line 1096, in main
    result = obj.flush()
  File "/root/.ansible/tmp/ansible-tmp-1457994186.08-15355698835389/bigip_software", line 587, in flush
    changed = self.activated()
  File "/root/.ansible/tmp/ansible-tmp-1457994186.08-15355698835389/bigip_software", line 848, in activated
    if self.is_activated() and volume == self.get_active_volume():
  File "/root/.ansible/tmp/ansible-tmp-1457994186.08-15355698835389/bigip_software", line 699, in is_activated
    return self.software_active(True)
  File "/root/.ansible/tmp/ansible-tmp-1457994186.08-15355698835389/bigip_software", line 740, in software_active
    pbuild = psoftware['build']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by caphrim007** [comment]
I think I've fixed this now. Thanks!
