### ISSUE TITLE
bigip_license throws NameError exception for HTTPSTransportNoVerify

### ISSUE THREAD

**Issue by loudsong** [F5Networks/f5-ansible#81]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_license.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/myuser/dev/my_proj/ansible.cfg
  configured module search path = ['./library']
```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### CONFIGURATION

I'm using the master branch of f5-ansible (pulled from github today)

##### OS / ENVIRONMENT

Controller: Ubuntu Xenial

##### SUMMARY

A python exception is being thrown when trying to use the bigip_license module. Looking at the code, it doesn't seem that `HTTPSTransportNoVerify` is imported before it is referenced.

##### STEPS TO REPRODUCE

```
- name: License BIG-IP using default license options
  bigip_license:
      server: "{{ inventory_hostname }}"
      #server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      validate_certs: "{{ validate_certs }}"
      key: "{{ registration_key }}"
  delegate_to: localhost

```

##### EXPECTED RESULTS

Expected the module to run successfully or fail gracefully.

##### ACTUAL RESULTS

Exception was thrown during execution.

```
TASK [tmos_common : License BIG-IP using default license options] **************
task path: /home/awalker/dev/repro_lib/roles/tmos_common/tasks/license.yml:13
Using module file /home/awalker/dev/repro_lib/f5-ansible/library/bigip_license.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awalker
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487370953.83-78240884154141 `" && echo ansible-tmp-1487370953
.83-78240884154141="` echo ~/.ansible/tmp/ansible-tmp-1487370953.83-78240884154141 `" ) && sleep 0'
<localhost> PUT /tmp/tmpH6Vcsy TO /home/awalker/.ansible/tmp/ansible-tmp-1487370953.83-78240884154141/bigip_license.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/awalker/.ansible/tmp/ansible-tmp-1487370953.83-78240884154141/ /home/awalker/.ansible/tmp/ansible-tmp-14
87370953.83-78240884154141/bigip_license.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/awalker/dev/repro_lib/bin/python /home/awalker/.ansible/tmp/ansible-tmp-1487370953.83-78240884154141/bigip_license
.py; rm -rf "/home/awalker/.ansible/tmp/ansible-tmp-1487370953.83-78240884154141/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_GxOuC6/ansible_module_bigip_license.py", line 666, in <module>
    main()
  File "/tmp/ansible_GxOuC6/ansible_module_bigip_license.py", line 642, in main
    if obj.present():
  File "/tmp/ansible_GxOuC6/ansible_module_bigip_license.py", line 569, in present
    lic_server = self.test_license_server()
  File "/tmp/ansible_GxOuC6/ansible_module_bigip_license.py", line 218, in test_license_server
    transport = HTTPSTransportNoVerify(
NameError: global name 'HTTPSTransportNoVerify' is not defined

fatal: [10.3.90.41 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "bigip_license"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_GxOuC6/ansible_module_bigip_license.py\", line 666, in <module>\n    
main()\n  File \"/tmp/ansible_GxOuC6/ansible_module_bigip_license.py\", line 642, in main\n    if obj.present():\n  File \"/tmp/ansible_GxOuC6/ansib$
e_module_bigip_license.py\", line 569, in present\n    lic_server = self.test_license_server()\n  File \"/tmp/ansible_GxOuC6/ansible_module_bigip_li$
ense.py\", line 218, in test_license_server\n    transport = HTTPSTransportNoVerify(\nNameError: global name 'HTTPSTransportNoVerify' is not defined$
n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

**Comment by caphrim007** [comment]
@loudsong try this version. I believe its fixed here https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_license.py

**Comment by loudsong** [comment]
Thanks, switched to the devel branch, and it works great:

```
TASK [tmos_common : License BIG-IP using default license options] **************  
task path: /home/awalker/dev/repro_lib/roles/tmos_common/tasks/license.yml:13
Using module file /home/awalker/dev/repro_lib/f5-ansible/library/bigip_license.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awalker
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487373393.24-151581342779186 `" && echo ansible-tmp-1487373393.24-151581342779186="` echo ~/.ansible/tmp/ansible-tmp-1487373393.24-151581342779186 `" ) && sleep 0'
<localhost> PUT /tmp/tmp4ML5zY TO /home/awalker/.ansible/tmp/ansible-tmp-1487373393.24-151581342779186/bigip_license.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/awalker/.ansible/tmp/ansible-tmp-1487373393.24-151581342779186/ /home/awalker/.ansible/tmp/ansible-tmp-1487373393.24-151581342779186/bigip_license.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/awalker/dev/repro_lib/bin/python /home/awalker/.ansible/tmp/ansible-tmp-1487373393.24-151581342779186/bigip_license.py; rm -rf "/home/awalker/.ansible/tmp/ansible-tmp-1487373393.24-151581342779186/" > /dev/null 2>&1 && sleep 0'
changed: [10.3.90.41 -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "dossier_file": null, 
            "key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "license_file": null, 
            "license_options": null, 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server": "10.3.90.41", 
            "server_port": 443, 
            "state": "present", 
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": false, 
            "wsdl": null
        },   
        "module_name": "bigip_license"
    }
}  
```

You can close this out.
