### ISSUE TITLE
bigip_ucs_fetch produces unhandled exception: "ValueError: too many values to unpack"

### ISSUE THREAD

**Issue by dtlowe** [F5Networks/f5-ansible#84]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
```bigip_ucs_fetch```

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/dlowery/test_ansible/ansible.cfg
  configured module search path = ['./library']
```

##### PYTHON VERSION

```
Python 2.6.6
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.0
  Build       1.0.1447
  Edition     Hotfix HF1
  Date        Wed Jun  8 13:41:59 PDT 2016

Hotfix List
ID582374-1    ID591039    ID547053-1  ID590345-1  ID590795-1  ID592682-1
ID592363      ID583631-2  ID569121-1  ID590993    ID588140    ID581834-5
ID591894-2    ID544477    ID582629-1  ID569467-5  ID590428-1  ID590779
ID591918-2    ID565137    ID576478    ID554713-2  ID592699-3  ID591908-2
ID588399-1    ID594302-1  ID587791-1  ID590601-2  ID591806-8  ID592354
ID592854-1    ID591881-1  ID531979-6  ID585905-1
```

##### CONFIGURATION

/etc/ansible/ansible.cfg contains all defaults. Testing folder contains local ansible.cfg with the following default overrides. I've successfully managed to configure Ansible to back up a Cisco switch and an ASA. I came across a blog or two that seemed to imply **paramiko** was needed for transport which is why that is configured as default here.
```
[defaults]
transport               = paramiko
hostfile                = ./hosts
host_key_checking       = false
timeout                 = 5
library                 = ./library
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 6.8 (Santiago)

##### SUMMARY

I'm working on trying to automate the creation of UCS backups for the BIG-IPs we have in our environment. I've tried interchanging ```src``` and ```backup``` to no avail. 

##### STEPS TO REPRODUCE

Attempt to generate a new UCS backup on your BIG-IP. 

**NOTE**: I have validate_certs set to false because I received a warning that the current version of Python installed (Python 2.6.6) is unable to perform this function.

```
  tasks:
    - name: F5 | Generate UCS
      bigip_ucs_fetch:
        server:         "{{ server }}"
        user:           "{{ user }}"
        password:       "{{ password }}"
        src:            "/var/local/ucs/test.ucs"
        dest:           "./test.ucs"
        validate_certs: false
```

##### EXPECTED RESULTS

I expected /var/local/ucs/test.ucs to be generated on the BIG-IP and for test.ucs to be generated in the current directory on the Ansible host.

##### ACTUAL RESULTS

```
[dlowery@rhserver test_ansible]$ ansible-playbook b_bigip.yml -vvv
Using /home/dlowery/test_ansible/ansible.cfg as config file

PLAYBOOK: b_bigip.yml **********************************************************
1 plays in b_bigip.yml
Enter password:

PLAY [Create new backup UCS] ***************************************************

TASK [F5 | Generate UCS] *******************************************************
task path: /home/dlowery/test_ansible/b_bigip.yml:13
Using module file /home/dlowery/test_ansible/library/bigip_ucs_fetch.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dlowery
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487889746.29-219424325362489 `" && echo ansible-tmp-1487889746.29-219424325362489="` echo ~/.ansible/tmp/ansible-tmp-1487889746.29-219424325362489 `" ) && sleep 0'
<localhost> PUT /tmp/tmpzZ_fnW TO /home/dlowery/.ansible/tmp/ansible-tmp-1487889746.29-219424325362489/bigip_ucs_fetch.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/dlowery/.ansible/tmp/ansible-tmp-1487889746.29-219424325362489/ /home/dlowery/.ansible/tmp/ansible-tmp-1487889746.29-219424325362489/bigip_ucs_fetch.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2.6 /home/dlowery/.ansible/tmp/ansible-tmp-1487889746.29-219424325362489/bigip_ucs_fetch.py; rm -rf "/home/dlowery/.ansible/tmp/ansible-tmp-1487889746.29-219424325362489/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_8CptRH/ansible_module_bigip_ucs_fetch.py", line 458, in <module>
    main()
  File "/tmp/ansible_8CptRH/ansible_module_bigip_ucs_fetch.py", line 357, in main
    (server, user, password, state, partition, validate_certs) = f5_parse_arguments(module)
ValueError: too many values to unpack

fatal: [crplb02 -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_ucs_fetch"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8CptRH/ansible_module_bigip_ucs_fetch.py\", line 458, in <module>\n    main()\n  File \"/tmp/ansible_8CptRH/ansible_module_bigip_ucs_fetch.py\", line 357, in main\n    (server, user, password, state, partition, validate_certs) = f5_parse_arguments(module)\nValueError: too many values to unpack\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
        to retry, use: --limit @/home/dlowery/test_ansible/b_bigip.retry

PLAY RECAP *********************************************************************
crplb02                    : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by delgadillo22** [comment]
Use the bigip_command module as workaround?

**Comment by caphrim007** [comment]
@dtlowe I believe this issue is now fixed. Can you test with the current modules and if there is still a problem, file a new issue? Thanks!
