### ISSUE TITLE
"Public URI path not registered"

### ISSUE THREAD

**Issue by ahamed-atypon** [F5Networks/f5-ansible#863]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.6.0

```

##### PYTHON VERSION

```
Python 2.7.15rc1

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Wed Feb 21 10:51:40 PST 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
bigsuds-with-jork==1.0.2
f5-sdk==3.0.14

```

##### SUMMARY

Public URI path not registered
##### STEPS TO REPRODUCE

```
ansible-playbook -i hosts playbook.yml
```

##### EXPECTED RESULTS

Create new pool.
##### ACTUAL RESULTS

Public URI path not registered

code  404
message  "Public URI path not registered"
referer  "10.20.0.20"
restOperationId  956887
errorStack   
 "com.f5.rest.common.RestWorkerUriNotFoundException: Public URI path not registered"
 "at com.f5.rest.workers.ForwarderPassThroughWorker.cloneAndForwardRequest(ForwarderPassThroughWorker.java:355)"
 "at com.f5.rest.workers.ForwarderPassThroughWorker.access$000(ForwarderPassThroughWorker.java:37)"
"at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:216)"
"at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:213)"
"at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:148)"
 "at com.f5.rest.workers.EvaluatePermissions.evaluatePermission(EvaluatePermissions.java:78)"
 "at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:227)"
 "at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:492)"
 "at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1061)"
 "at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)"
 "at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1348)"
 "at com.f5.rest.common.RestServer.access$000(RestServer.java:45)"
 "at com.f5.rest.common.RestServer$1.run(RestServer.java:309)"
 "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)"
 "at java.util.concurrent.FutureTask.run(FutureTask.java:262)"
"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)"
 "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)"
 "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)"
 "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)"
 "at java.lang.Thread.run(Thread.java:745)\n"
kind | ":resterrorresponse"

```

```

**Comment by caphrim007** [comment]
@ahamed-atypon you've provided no example re-production

**Comment by ahamed-atypon** [comment]
I ma just cloned you repository trying to run examples/0000-getting-started the output look like this 

```
The full traceback is:
  File "/tmp/ansible_QGgXyX/ansible_module_bigip_pool.py", line 956, in main
    results = mm.exec_module()
  File "/tmp/ansible_QGgXyX/ansible_module_bigip_pool.py", line 716, in exec_module
    changed = self.present()
  File "/tmp/ansible_QGgXyX/ansible_module_bigip_pool.py", line 764, in present
    if self.exists():
  File "/tmp/ansible_QGgXyX/ansible_module_bigip_pool.py", line 843, in exists
    return self.client.api.tm.ltm.pools.pool.exists(
  File "/tmp/ansible_QGgXyX/ansible_modlib.zip/ansible/module_utils/network/f5/bigip.py", line 61, in api
    raise F5ModuleError(error)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "description": null, 
            "lb_method": "ratio-member", 
            "metadata": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "ansible_test", 
            "partition": "Common", 
            "password": null, 
            "priority_group_activation": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "10.20.0.2", 
                "server_port": 443, 
                "ssh_keyfile": "/root/.ssh/id_rsa.pub", 
                "timeout": null, 
                "transport": "cli", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": null, 
            "server_port": null, 
            "service_down_action": null, 
            "slow_ramp_time": 120, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "Unable to connect to 10.20.02 on port 443. The reported error was \"400 Unexpected Error: Bad Request for uri: https://10.20.0.2:443/mgmt/shared/authn/login\nText: u'{\"code\":400,\"message\":\"loginProviderName is invalid.\",\"originalRequestBody\":\"{\\\\\"username\\\\\":\\\\\"admin\\\\\",\\\\\"loginProviderName\\\\\":\\\\\"tmos\\\\\",\\\\\"generation\\\\\":0,\\\\\"lastUpdateMicros\\\\\":0}\",\"referer\":\"10.20.0.20\",\"restOperationId\":971097,\"kind\":\":resterrorresponse\"}'\"."
```
Trying to open the link appeard in the error message using browser  https://10.20.0.2:443/mgmt/shared/authn/login It retrieve bellow error 

{"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/authn/login Referrer:10.20.0.20 Sender:10.20.0.20","referer":"10.20.0.20","restOperationId":974003,"errorStack":["java.lang.SecurityException: Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/authn/login Referrer:10.20.0.20 Sender:10.20.0.20","at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:236)","at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:142)","at com.f5.rest.workers.EvaluatePermissions.evaluatePermission(EvaluatePermissions.java:78)","at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:227)","at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:492)","at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1061)","at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)","at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1348)","at com.f5.rest.common.RestServer.access$000(RestServer.java:45)","at com.f5.rest.common.RestServer$1.run(RestServer.java:309)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:745)\n"],"kind":":resterrorresponse"}

**Comment by ahamed-atypon** [comment]
@caphrim007  Requested command result.
```
curl -ks -u *******:******** https://10.20.0.2/mgmt/tm/sys | jq .
    {
        "kind": "tm:sys:syscollectionstate",
        "selfLink": "https://localhost/mgmt/tm/sys?ver=12.1.3.2",
        "items": [
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/application?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/crypto?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/daemon-log-settings?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/disk?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/ecm?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/file?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/fpga?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/icall?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/ipfix?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/log-config?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/pfman?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/sflow?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/software?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/url-db?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/aom?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/autoscale-group?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/cluster?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/config?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/daemon-ha?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/datastor?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/db?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/dns?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/feature-module?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/folder?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/global-settings?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/ha-group?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/httpd?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/icontrol-soap?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/log-rotate?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/management-dhcp?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/management-ip?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/management-ovsdb?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/management-route?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/ntp?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/outbound-smtp?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/provision?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/scriptd?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/service?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/smtp-server?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/snmp?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/sshd?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/state-mirroring?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/syslog?ver=12.1.3.2"
            }
        },
        {
            "reference": {
                "link": "https://localhost/mgmt/tm/sys/ucs?ver=12.1.3.2"
            }
        }
        ]
    }

```

**Comment by caphrim007** [comment]
@ahamed-atypon can you provide an example task/play that shows this error?

**Comment by ahamed-atypon** [comment]
This is an example.
```
- name: Create a VIP, pool, pool members and nodes
  hosts: f5-test
  connection: local

  vars:
    provider:
      server: "{{ ansible_host }}"
      user: "{{ f5_username }}"
      passsword: "{{ f5_password }}"
      validate_certs: "{{ validate_certs }}"
      server_port: "{{ f5_server_port }}"

- name: Create a pool
    bigip_pool:
      provider: "{{ provider }}"
      lb_method: ratio-member
      name: web
      slow_ramp_time: 120
```

**Comment by ahamed-atypon** [comment]
@caphrim007  Do you have an updates on this please.

**Comment by caphrim007** [comment]
@ahamed-atypon your example does not logically reflect what your original error output should be showing.

In particular, the error output shows a transport of `cli`. However, this is not possible if you have `connection: local` and have not specifically set `transport: cli` in your provider.

Send the output of running your example playbook above.

**Comment by ahamed-atypon** [comment]
This is my playbook: 

```
- name: Create a VIP, pool, pool members and nodes
  hosts: f5-test 

  vars:
    provider:
      password: "{{ f5_password }}"
      server: "{{ ansible_host }}"
      user: "{{ f5_username }}"
      validate_certs: "{{ validate_certs }}"
      server_port: "{{ f5_server_port }}"
      transport: cli

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
```

And variables file

```
ansible_host: localhost
f5_username: ***********
f5_password: ***********   
f5_server_port: 443
validate_certs: no
```

This is inventory file. 

[f5-test]
10.20.0.2

The error appears now. 
```

`> FAILED! => {"changed": false, "msg": "Unable to connect to localhost on port 443. The reported error was \"HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /mgmt/shared/authn/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e94acbc10>: Failed to establish a new connection: [Errno 111] Connection refused',))\"."}`
```

If I add connection: local and remove transport: cli same error raised. 
Note: I am using correct username and password with admin privilege.  
```
{"changed": false, "msg": "Unable to connect to localhost on port 443. The reported error was \"HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /mgmt/shared/authn/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44013c3d90>: Failed to establish a new connection: [Errno 111] Connection refused',))\"."}
```

**Comment by focrensh** [comment]
I think your provider should use `server: "{{ inventory_hostname }}"`

`ansible_host` is telling the REST calls to target your local machine vs the BIG-IP

**Comment by wojtek0806** [comment]
@ahamed-atypon 
Can you tell us if this is still the problem after moving to 2.7.0. If so then looking at the error, can you tell me the exact tmos version for that BIGIP in question?
