### ISSUE TITLE
bigip_virtual_server "state: disabled" generates error on new vs creation

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#882]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server 
##### ANSIBLE VERSION

```
ansible 2.6.3
```

##### PYTHON VERSION

```
python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### BIGIP VERSION

```
Viprion 2150:
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

bigip_virtual_server "state: disabled" generates error on new vs creation.  I can pass "state: disabled" to a pre-existing vs with no issues.

##### STEPS TO REPRODUCE

task:
```
---
- name: create virtual server
 bigip_virtual_server:
   name: "{{ item.vs_name }}"
   destination: "{{ item.vs_dest }}"
   port: "{{ item.vs_port }}"
   description: "{{ item.vs_description|default(omit) }}"
   snat: "{{ item.vs_snat|default('Automap') }}"
   pool: "{{ item.vs_join_pool }}"
   profiles: "{{ item.vs_profiles }}"
   state: "{{ item.vs_state }}"
   provider: "{{ provider }}"
 loop: "{{ virtual_servers|default([]) }}"
 delegate_to: localhost
```

vars:
```
virtual_servers:
 - vs_name: "{{ env }}_{{ fqdn }}_{{ port }}_vs"
   vs_dest: "10.10.10.7"
   vs_port: "{{ port }}"
   vs_description: test vs creation with ansible
   vs_profiles:
     - name: "tcp-wan-optimized"
       context: client-side
     - name: "tcp-lan-optimized"
       context: server-side
     - name: "{{ env }}_{{ fqdn }}_{{ port }}_oneconnect"
     - name: "{{ env }}_{{ fqdn }}_{{ port }}_http"
     - name: "{{ env }}_{{ fqdn }}_clientssl"
   vs_state: disabled
   vs_join_pool: "{{ env }}_{{ fqdn }}_{{ port }}_pool"
```

##### EXPECTED RESULTS

VS should be created in disabled state.
##### ACTUAL RESULTS

Error generated.

```
The full traceback is:
Traceback (most recent call last):
 File "/tmp/ansible_MVSfJB/ansible_module_bigip_virtual_server.py", line 2737, in <module>
   main()
 File "/tmp/ansible_MVSfJB/ansible_module_bigip_virtual_server.py", line 2728, in main
   results = mm.exec_module()
 File "/tmp/ansible_MVSfJB/ansible_module_bigip_virtual_server.py", line 2499, in exec_module
   changed = self.present()
 File "/tmp/ansible_MVSfJB/ansible_module_bigip_virtual_server.py", line 2515, in present
   return self.create()
 File "/tmp/ansible_MVSfJB/ansible_module_bigip_virtual_server.py", line 2592, in create
   self.create_on_device()
 File "/tmp/ansible_MVSfJB/ansible_module_bigip_virtual_server.py", line 2623, in create_on_device
   **params
 File "/usr/lib/python2.7/site-packages/f5/bigip/tm/ltm/virtual.py", line 72, in create
   result = self._create(**kwargs)
 File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 998, in _create
   self._check_exclusive_parameters(**kwargs)
 File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 335, in _check_exclusive_parameters
   raise ExclusiveAttributesPresent(error)
f5.sdk_exception.ExclusiveAttributesPresent: Mutually exclusive arguments submitted. The following arguments cannot be set together: "disabled, enabled".
```

**Comment by caphrim007** [comment]
this appears to be being caused by the sdk. going to work on removing the sdk from the module to see if that fixes the issue
