### ISSUE TITLE
bigip_profile_client_ssl is not working as expected

### ISSUE THREAD

**Issue by m2harshanalore** [F5Networks/f5-ansible#885]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_profile_client_ssl

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /home/xxxxx/load-balancer-provisioning/ansible.cfg
  configured module search path = [u'/export/home/a604150/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### BIGIP VERSION

```
Big IP V 12.1.3.3
```

##### SUMMARY
bigip_profile_client_ssl is not working as expected.

##### STEPS TO REPRODUCE

```
---


- name: Create the certificate in the LTM
  bigip_ssl_certificate:
    name: cert_test.crt
    server: test.abc.com
    user: admin
    password: admin
    state: present
    cert_content: "{{ cert_content }}"
    validate_certs: no
  delegate_to: localhost

- name: Create the key in the LTM
  bigip_ssl_key:
    name: key_test.key
    server: test.abc.com
    user: admin
    password: admin
    state: present
    content: "{{ key_content }}"
    validate_certs: no
  delegate_to: localhost


- name: Create the Client SSL Profile
  bigip_profile_client_ssl:
    state: present
    server: test.abc.com
    user: admin
    password:admin
    name:"{{ fqdn }}"
    cert_key_chain:
        - cert_test.crt
        - key_test.key
    validate_certs: no
  delegate_to: localhost
```

##### EXPECTED RESULTS
Client SSL profile would get configured

##### ACTUAL RESULTS

```
ASK [Create the Client SSL Profile] ***********************************************************************************************
task path: /home/xxxxx/playbooks/ssl_test.yaml:31
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: a604150
<localhost> EXEC /bin/sh -c 'echo ~a604150 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /export/home/a604150/.ansible/tmp/ansible-tmp-1535135180.57-203360318068751 `" && echo ansible-tmp-1535135180.57-203360318068751="` echo /export/home/a604150/.ansible/tmp/ansible-tmp-1535135180.57-203360318068751 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_profile_client_ssl.py
<localhost> PUT /export/home/a604150/.ansible/tmp/ansible-local-22204C2bEGg/tmparVUm8 TO /export/home/a604150/.ansible/tmp/ansible-tmp-1535135180.57-203360318068751/bigip_profile_client_ssl.py
<localhost> EXEC /bin/sh -c 'chmod u+x /export/home/a604150/.ansible/tmp/ansible-tmp-1535135180.57-203360318068751/ /export/home/a604150/.ansible/tmp/ansible-tmp-1535135180.57-203360318068751/bigip_profile_client_ssl.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /export/home/a604150/.ansible/tmp/ansible-tmp-1535135180.57-203360318068751/bigip_profile_client_ssl.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /export/home/a604150/.ansible/tmp/ansible-tmp-1535135180.57-203360318068751/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py", line 532, in <module>
    main()
  File "/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py", line 523, in main
    results = mm.exec_module()
  File "/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py", line 376, in exec_module
    changed = self.present()
  File "/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py", line 401, in present
    return self.create()
  File "/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py", line 409, in create
    self.create_on_device()
  File "/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py", line 464, in create_on_device
    params = self.want.api_params()
  File "/tmp/ansible_71q7bx/ansible_modlib.zip/ansible/module_utils/network/f5/common.py", line 500, in api_params
  File "/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py", line 223, in cert_key_chain
    key = self._key_filename(item['key'])
TypeError: string indices must be integers, not str
fatal: [abc.xyz.com -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py\", line 532, in <module>\n    main()\n  File \"/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py\", line 523, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py\", line 376, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py\", line 401, in present\n    return self.create()\n  File \"/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py\", line 409, in create\n    self.create_on_device()\n  File \"/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py\", line 464, in create_on_device\n    params = self.want.api_params()\n  File \"/tmp/ansible_71q7bx/ansible_modlib.zip/ansible/module_utils/network/f5/common.py\", line 500, in api_params\n  File \"/tmp/ansible_71q7bx/ansible_module_bigip_profile_client_ssl.py\", line 223, in cert_key_chain\n    key = self._key_filename(item['key'])\nTypeError: string indices must be integers, not str\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

**Comment by caphrim007** [comment]
@m2harshanalore you're using the module wrong

refer to the examples here

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_profile_client_ssl_module.html#bigip-profile-client-ssl-module

specifically, your `cert_key_chain` parameter is incorrect

**Comment by m2harshanalore** [comment]
It worked as expected , thanks for your support.
