### ISSUE TITLE
bigip_data_group and version 11

### ISSUE THREAD

**Issue by crosson** [F5Networks/f5-ansible#914]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
bigip_data_group

##### ANSIBLE VERSION

```
ansible 2.6.1
```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.2
  Build    0.0.141
  Edition  Final
  Date     Fri Jan 30 14:50:39 PST 2015
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.19
```

##### OS / ENVIRONMENT

Any OS

##### STEPS TO REPRODUCE
bigip_data_group makes a call to `https://host.com/mgmt/shared/authn/login`

This path apparently doesn't exist on version 11. So while we can 
`curl -ks -u username -X GET https://host.com/mgmt/tm/ltm/`

all day long the authn/login fails. I suspect this is a new bigip version 12 thing

> fatal: [host.com -> localhost]: FAILED! => {"changed": false, "msg": "Unable to connect to host.com on port 443. The reported error was \"404 Unexpected Error: Not Found for uri: https://host.com:443/mgmt/shared/authn/login\nText: u'{\"code\":404,\"message\":\"http://localhost:8100/mgmt/shared/authn/login\",\"restOperationId\":9542987,\"errorStack\":[\"com.f5.rest.common.RestWorkerUriNotFoundException: http://localhost:8100/mgmt/shared/authn/login\",\"at com.f5.rest.common.RestServer.trySendInProcess(RestServer.java:231)\",\"at com.f5.rest.common.RestRequestReceiver.dispatchToService(RestRequestReceiver.java:93)\",\"at com.f5.rest.common.RestRequestReceiver.processNext(RestRequestReceiver.java:57)\",\"at com.f5.rest.common.RestHelper$2.run(RestHelper.java:1910)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\",\"at java.lang.Thread.run(Thread.java:722)\\\\n\"]}'\"."}

And also demonstrated via curl

> 
MBP:networking-ansible MBP$ curl -ksI -u apiuser -X GET https://host.com/mgmt/tm/ltm/ -H "Content-type: application/json"
Enter host password for user 'apiuser':
HTTP/1.1 200 OK
Date: 05 Sep 2018 20:55:27 UTC
Server: com.f5.rest.common.RestRequestSender
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache
Content-Length: 1846
Content-Type: application/json
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: default-src 'self'  'unsafe-inline' 'unsafe-eval'
Strict-Transport-Security: max-age=16070400; includeSubDomains

MBP:networking-ansible MBP$ curl -ksI -u apiuser -X GET https://host.com/mgmt/shared/authn/login -H "Content-type: application/json"
Enter host password for user 'apiuser':
HTTP/1.1 404 Not Found
Date: 05 Sep 2018 20:55:44 UTC
Server: com.f5.rest.common.RestRequestSender
Set-Cookie: BIGIPAuthCookie=A73608F0E83B5DCFE3FF9975E64854DD669D7D33; path=/; Secure; HttpOnly
Set-Cookie: BIGIPAuthUsernameCookie=apiuser; path=/; Secure; HttpOnly
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache
Content-Length: 737
Content-Type: application/json
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: default-src 'self'  'unsafe-inline' 'unsafe-eval'

This call is documented [here](https://devcentral.f5.com/wiki/iworkflow.apiref_shared_authn_login.ashx)

It does not state what version of bigip is needed. I believe 11 is still under support and bigip_data_group should use the method that is most widely supported for all the bigip verisons.

**Comment by caphrim007** [comment]
@crosson 11.x is not a supported version to use with the Ansible modules. Supported versions of F5 product can be found here

https://clouddocs.f5.com/products/orchestration/ansible/devel/usage/supported-versions.html

The error you are receiving is indeed an 11.x-ism

**Comment by crosson** [comment]
That makes sense. Please mark this as a documentation bug and add those notes to the official ansible documentation [here](https://docs.ansible.com/ansible/latest/modules/bigip_data_group_module.html#bigip-data-group-module)

Particularly version 12+ is required, as I noted above. Thanks again.
