### ISSUE TITLE
Error "coercing to Unicode: need string or buffer, NoneType found" for bigip_asm_policy 

### ISSUE THREAD

**Issue by jassouline** [F5Networks/f5-ansible#986]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_asm_policy

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jassouline/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### PYTHON VERSION

```
Python 2.7.6

```

##### BIGIP VERSION

```
12.1.2
```

##### LIBRARY VERSIONS

```
Babel==1.3
GitPython==0.3.2rc1
Jinja2==2.7.2
Mako==0.9.1
MarkupSafe==0.18
Pillow==2.3.0
PyChart==1.39
PyOpenGL==3.0.2
PyWebDAV==0.9.8
PyYAML==3.10
Pyrex==0.9.8.5
Werkzeug==0.9.4
ZSI==2.1a1
ansible==2.8.0.dev0
argparse==1.2.1
asn1crypto==0.24.0
async==0.6.1
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
colorama==0.2.5
cryptography==2.3.1
decorator==3.4.0
docutils==0.11
ecdsa==0.11
enum34==1.1.6
f5-icontrol-rest==1.3.11
f5-sdk==3.0.20
feedparser==5.1.3
gdata==2.0.18
git-review==1.23
gitdb==0.5.4
html5lib==0.999
httplib2==0.8
idna==2.7
ipaddress==1.0.22
ipython==1.2.1
lxml==3.3.3
mock==1.0.1
packaging==18.0
paramiko==1.15.1
pexpect==3.1
psutil==1.2.1
psycopg2==2.4.5
pyasn1==0.4.4
pycparser==2.19
pycrypto==2.6.1
pydot==1.0.28
pygobject==3.12.0
pyparsing==2.2.2
python-apt===0.9.3.5ubuntu2
python-dateutil==1.5
python-debian==0.1.27
python-ldap==2.4.10
python-openid==2.2.5
pytz==2012rc0
reportlab==3.0
requests==2.19.1
roman==2.0.0
simplegeneric==0.8.1
simplejson==3.3.1
six==1.11.0
smmap==0.8.2
unittest2==0.5.1
urllib3==1.23
vatnumber==1.1
virtualenv==16.0.0
vobject==0.8.1rc0
wsgiref==0.1.2
xlwt==0.7.5
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
When i'm trying to use the bigip_asm_policy module, i have always the same error message in ansible :

jassouline@jassouline-ubuntu14:~/f5$ sudo ansible-playbook -i hosts playbook.yml -vvvv
/usr/local/lib/python2.7/dist-packages/cryptography-2.3.1-py2.7-linux-x86_64.egg/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
ansible-playbook 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jassouline/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Set default localhost to 127.0.0.1
Parsed /home/jassouline/f5/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible-2.8.0.dev0-py2.7.egg/ansible/plugins/callback/default.pyc

PLAYBOOK: playbook.yml ******************************************************************************************************************
1 plays in playbook.yml

PLAY [Test] *****************************************************************************************************************************
META: ran handlers

TASK [Create Blank ASM Policy] **********************************************************************************************************
task path: /home/jassouline/f5/playbook.yml:8
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432 `" && echo ansible-tmp-1539002592.65-263059164054432="` echo /root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.8.0.dev0-py2.7.egg/ansible/modules/network/f5/bigip_asm_policy.py
<localhost> PUT /home/jassouline/.ansible/tmp/ansible-local-23912Pjf_oW/tmpqsQfit TO /root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/ /root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py", line 858, in <module>
  File "/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py", line 849, in main
  File "/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py", line 690, in exec_module
  File "/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py", line 468, in exec_module
  File "/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py", line 515, in present
  File "/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py", line 539, in create
  File "/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py", line 532, in _file_is_missing
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 858, in <module>\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 849, in main\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 690, in exec_module\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 468, in exec_module\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 515, in present\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 539, in create\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 532, in _file_is_missing\n  File \"/usr/lib/python2.7/genericpath.py\", line 18, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string or buffer, NoneType found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
        to retry, use: --limit @/home/jassouline/f5/playbook.retry

##### STEPS TO REPRODUCE

```
Playbook.yml :
---
- name: Test
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name : Create Blank ASM Policy
      bigip_asm_policy:
        name: 'new_template_policy'
        password: 'admin'
        server: '127.0.0.1'
        server_port: '8080'
        file:
        user: 'admin'
        active: no
        state: present
        validate_certs: no
        transport: rest
      delegate_to: localhost

I did a ssh tunnel from port 8080 to the f5 443 (other modules work correctly, just asm_policy doesn't work)
```

##### EXPECTED RESULTS

To have a new blank policy on my F5.

##### ACTUAL RESULTS

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1539002592.65-263059164054432/AnsiballZ_bigip_asm_policy.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 858, in <module>\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 849, in main\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 690, in exec_module\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 468, in exec_module\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 515, in present\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 539, in create\n  File \"/tmp/ansible_bigip_asm_policy_payload_csZ_w6/__main__.py\", line 532, in _file_is_missing\n  File \"/usr/lib/python2.7/genericpath.py\", line 18, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string or buffer, NoneType found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
        to retry, use: --limit @/home/jassouline/f5/playbook.retry

```

```
Thanks

**Comment by caphrim007** [comment]
@jassouline if you're not specifying a file, then don't include the `file` parameter

**Comment by jassouline** [comment]
@caphrim007 Ok, but how can i do to export my ASM policy then ? I don't need file or template parameter and on the https://docs.ansible.com/ansible/latest/modules/bigip_asm_policy_module.html#bigip-asm-policy-module page, sometimes neither file or template are used.
Thanks for your reply !

**Comment by wojtek0806** [comment]
@jassouline This module does not do policy exports I am afraid. This is for importing and creating policies for ASM only

**Comment by jassouline** [comment]
@caphrim007 So for now, there is no way to export ASM policy with ansible ?

**Comment by caphrim007** [comment]
@jassouline correct

**Comment by wojtek0806** [comment]
@jassouline 
You could utilise a combination of bigip_command module to execute tmsh and bash commands to export the policy, and move it to the desired folder on the bigip. then use ansible fetch module to do an scp transfer. It is a bit of work to do it but until we implement it this could be your only option.

(https://docs.ansible.com/ansible/2.7/modules/fetch_module.html#fetch-module)

**Comment by jmcalalang** [comment]
Not to hijack but if i can help.

This is absolutely 100% not from F5 support or @caphrim007, a few of us did try and create something which does an export, we highlighted it at Agility this year as a concept to see if it was being asked for from the field. If F5 support does develop one it may be very different! however if you were at Agility got to use this, and are now wondering where it was..

It has hard coded paths for export, and might need some massaging but it will get you really close really fast.

repo: https://github.com/F5-use-cases/f5-rs-waf 

follow the tasks and the library is contained in the repo you will find the hard coded paths.

sorry to hijack @caphrim007 @wojtek0806

**Comment by caphrim007** [comment]
@jmcalalang you have a lot of modules in your library there. Would you mind if we turned them into official modules?

**Comment by wojtek0806** [comment]
@jassouline do you have any further questions or can we close this issue as resolved ?

**Comment by jmcalalang** [comment]
@caphrim007 ill send you a note, but I want the original author to approve
